### ISSUE TITLE
Change settings location for appimage?

### ISSUE THREAD

**Issue by PaperOrb** [FreeTubeApp/FreeTube#1009]
**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [x] Setup
- [ ] Other. Please specify:

**Question**
I want to use the appimage like a portable installation for compatibility reasons, but it appears I lose the settings as well as subscriptions any time I hop computers. Is there a way to change where freetube stores its settings? Thanks.

**Comment by dennis1248** [comment]
On Unix-like operating systems every file has a place, you shouldn't start moving stuff around. It is also completely unnecessary to move files around since we can play with symbolic links and mount points.

I can think of two solutions.
1. Use a network storage device to backup your home directory or the `~/.config` / `~/.var/app/io.freetubeapp.FreeTube` sub directory. You can then mount this external storage device in the location where the configuration files are normally stored.
2. Replace `~/.config` / `~/.var/app/io.freetubeapp.FreeTube` with a symbolic link to the location you would like it to save it's data. It could be made to point to a USB flash drive for example.

**Comment by Svallinn** [comment]
dennis' answer is pretty much as best as it gets for workarounds, so I'll just add a few simple explanations

An AppImage is just a self-mounting filesystem image that executes whatever is inside it

This makes the application itself portable, but it can't bundle the data it typically stores in the user's filesystem with it (p.e. configuration files), since the location of those files is not determined by the format of the executable
