### ISSUE TITLE
New UI Concept

### ISSUE THREAD

**Issue by Donkey-Doug** [FreeTubeApp/FreeTube#1012]
Hi, I noticed some mentions about a redesign. I decided to make a mockup in Microsoft paint (yes, paint). This is what I came up with:

![tijdelijk](https://user-images.githubusercontent.com/50382414/106681800-89cdee00-65c1-11eb-955f-2bad00f9324e.jpg)

**Comment by Donkey-Doug** [comment]
Some remarks:

- I thought it would be nice to track the three most recently watched videos this session and show them in the sidebar.
- In my opinion, few options available at first with the option to expand by clicking "more" is cleaner and more user friendly.
- Highlight the currently selected page with the preferred accent color (in the example this is red).

**Comment by fsondej** [comment]
To be honest, I like the existing layout more. I don't need 3 recently watched videos, and also I like having all those options one click away.
The color highlight is a nice touch though.

**Comment by Tamnac** [comment]
Looks decent, however it's very inefficient with space. Looks more like a mobile app than a desktop one.

**Comment by zynexiz** [comment]
Think it looks better and more stylish than the one is has now. Always preferred a clean UI without clutter :) Maybe could add option to customize what to show in the sidebar?

**Comment by Agych** [comment]
Looks flat and minimalistic, like repeating the win10-mistake with it's tasteless design, would rather suggest to have a classic 3D/Vista/Win7/Aero-style

**Comment by GilgusMaximus** [comment]
Hi,
so this seems not to be that goal oriented at the moment, because everyone will have a different opinion, and sticking to this classic FreeTube layout for the moment is probably the best. 
However in the future we plan to support CSS theming, allowing everyone to customize colors and layouts as they like.

**Comment by Defreezer** [comment]
Would it be too outlandish to hope for a classic 2005/2006/2007/2008 Youtube layout design? Either as a custom CSS or otherwise. We haven't seen those old looks in so long. What a stylish program it'd be if it could have that at some point.

**Comment by PrestonN** [comment]
> Would it be too outlandish to hope for a classic 2005/2006/2007/2008 YouTube layout design? Either as a custom CSS or otherwise. We haven't seen those old looks in so long. What a stylish program it'd be if it could have that at some point.

It's _possible_ but yes it's a little unrealistic to implement. It would take a very long time to try and do this and even once implemented we'd have to make sure that every single new UI element we create looks good with each design. We can consider adding more customization for different things but full on copies is likely not going to happen.

Going to the design concept itself, the mentions of a redesign that you're talking about is something that we've already handled. The rewrite released in October of last year included the new design that we have come up with. Because of that, we don't actively have any plans to redesign anything again.

I do like some of the decisions made in your concept. Specifically I do like the colours used in it. I'd be open to trying to add a similar theme to the current layout.

Besides that, this issue can likely be closed.
