### ISSUE TITLE
Add some additional features

### ISSUE THREAD

**Issue by Hx2-code** [FreeTubeApp/FreeTube#1024]
The features of [The addon for youtube ](https://addoncrop.com/youtube-video-downloader/) would make the app more efficient.

**Comment by ckorder** [comment]
Please explain in which way. I guess you mean the download video feature which is not working at all. I mean it opens a browser with the mp4 stream...a web request file stream download would be better. So yeah could be a nice hint for improvement.

**Comment by Hx2-code** [comment]
Both features and some additional features like

Ability to capture screenshots of YouTube videos in high quality.

Pop-up video functionality to watch a video while doing other work like [Enhancer for YouTube](https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle)

Ability to loop videos or part of a video like in Enhancer for Youtube.

Float view (To view a video in popup mode while you are scrolling down).

Disable annotations (watch YouTube videos without any annoying annotations).

Enable copy to clipboard function (it will enable to download YouTube videos with the help of external download manager like IDM).

And I guess you can use [youtube-dl](http://ytdl-org.github.io/youtube-dl/) to enable download functionality.

**Comment by PrestonN** [comment]
Going to close this for a couple of reasons. The main reason is that vague titles and several suggestions in one thread makes it very difficult to keep track of which features we and others decide to work on. Please make new issues for each feature you'd like to see implement. Just saying "hey do all these things" makes it hard to stay organized.

The other reason is that a vast majority of these are already implemented in FreeTube.

> Pop-up video functionality to watch a video while doing other work like Enhancer for YouTube
> Float view (To view a video in popup mode while you are scrolling down).

We already offer a pop-up player

> Ability to loop videos or part of a video like in Enhancer for Youtube.

FreeTube already supports looping videos

> Disable annotations (watch YouTube videos without any annoying annotations).

FreeTube doesn't even support annotations, so they're already "disabled"

> Enable copy to clipboard function (it will enable to download YouTube videos with the help of external download manager like IDM).

There's already several ways to copy the video URL to your clipboard. There's a share button on the video page or you can use the 3 dot menu when looking through a list of videos.

> I guess you mean the download video feature which is not working at all. I mean it opens a browser with the mp4 stream...a web request file stream download would be better. So yeah could be a nice hint for improvement.

It was either the current implementation for downloads or wait a _very_ long time before I do anything else with it because anything more is going to require a lot of custom UI work for something that your browser can already handle. That's why it opens in your browser, so you can use that to download it. It isn't to most elegant but it saves me a lot of time. In the future I may add a built in function.

> Ability to capture screenshots of YouTube videos in high quality.

This is the only real feature out of the list here that isn't already included. This is something that I wouldn't be planning on working on any time soon. If someone is interested, I'd accept a pull request. If this is something you're really wanting, please create a new issue, along with new issues for any specific feature you're wanting. Please check for any existing issues before creating a new one.

**Comment by Hx2-code** [comment]
Sorry about that ... I made individual issues now
