### ISSUE TITLE
Ability to take screenshot of a video

### ISSUE THREAD

**Issue by Hx2-code** [FreeTubeApp/FreeTube#1027]
The feature will be useful.

**Comment by Murciegalo** [comment]
I can take this one if somebody assigne it to me

**Comment by GilgusMaximus** [comment]
Hi, thanks for your willingness to contribute that much !
If you need any help, let us know :)

**Comment by Murciegalo** [comment]
Just realized it is VUE.. sorry for the misunderstanding but freetube appeared as a ReactJS open source project when searching for..

**Comment by seascape** [comment]
Hello! I came here to request/suggest a screenshot feature, and found this existing request.

A few suggestions and observations based on experiences with browser add-ons that do this:

- Please offer lossless PNG capture. You may want to go further and add lossy JPEG too, but in my opinion if there can only be one, lossless is the way to go. The user can always compress a lossless PNG into a lossy JPEG, but they can't restore a lossy JPEG that already has artifacts.

- Many YouTube screencap browser add-ons derive screenshot resolution from the current size of the video in the browser rather than the total resolution of the video. This means the user has to toggle to fullscreen before capturing if they want a screenshot that's at least close to the video's true resolution. Therefore, I suggest it's better practice to derive screenshot resolution from the full resolution of the video, such as 1080p, 720p, etc.

- Two file-save procedures are possible: ask the user where to save to after every screenshot taken, or automatically save screenshots to a previously specified folder. The latter method is useful for allowing the user to take multiple screenshots in more rapid succession. It would be nice if that folder is user-selectable.

- In addition to a possible screenshot UI icon, a keyboard shortcut is useful as well.
