### ISSUE TITLE
Feasible to run FreeTube as a self hosted web app on a LAN?

### ISSUE THREAD

**Issue by v0n66** [FreeTubeApp/FreeTube#1034]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Just wondering how feasible is it to create a self hosted version of this as a web app that can be accessed over LAN from a web browser instead of a native Electron app. This will allow it to be used on iOS and Android devices. 

**Describe the solution you'd like to see implemented**
Just posing the question and wondering how feasible it is based on how FreeTube is designed, and separately how much work it would take.  

**Describe alternatives you've considered**
I guess native apps are also an option to use this on mobile devices. Would this be a larger effort than the self hosted web app option? I know NewPipe is available for Android so not so much need there. And iOS terms of service would never allow this, so the self hosted web app option might be a nice way to bring this to iOS and iPadOS!

**Comment by PrestonN** [comment]
Mobile ports for platforms like Android and iOS are never going to happen because of the reasons you mentioned. A web app version is possible however there's a lot of things that needs to be done before that can happen. Progress on this is currently tracked at #633.

Since this is a duplicate issue of the one I linked, I will go ahead and close this.
