### ISSUE TITLE
4K 60fps support?

### ISSUE THREAD

**Issue by phly95** [FreeTubeApp/FreeTube#1039]
**Describe the solution you'd like to see implemented**
I would like support for high-end video formats, like 4k 60fps videos

**Describe alternatives you've considered**
Checking to see if there is a 4k button. There is not

**Screenshots**
![image](https://user-images.githubusercontent.com/3526540/108145418-644ce400-7099-11eb-8ce1-9a8a36cc0701.png)

**Additional context**
Test link https://youtu.be/_fC53l3jGAc

**Comment by orthand** [comment]
I'm not sure why it's inconsistent but I've seen at least two channels that had the option to switch to higher resolution.
Example is [ShortCircuit](https://www.youtube.com/channel/UCdBK94H6oZT2Q7l0-b0xmMg/videos) and LTT has 4K as well that worked for me. Not sure if these only work because of the new API and why they don't have "proper" 1080 but only 960p etc.
Though this also could give higher "Default Quality" options in settings.

**Comment by GilgusMaximus** [comment]
Hi,
we support 4k, but as @orthand noted, it appears only on a few videos. This is due to the used video format. The plugin we use for streaming the videos only supports mp4 and no webm format. Unfortunately most 1080p+ videos only come with webm format. So these videos are capped. The developers of the streaming plugin for VideoJS plan to implement this, however you'd have to take a look over there how far they are / when they plan to do so. Linking #826 #957 .

@orthand please take a look at #604 for the 960p.

I'm gonna go ahead and close this, as it is a duplicate and now answered.

Best Regards,
Gilgus
