### ISSUE TITLE
Bitdefender detect malware/virus + threat defense

### ISSUE THREAD

**Issue by Daisenki** [FreeTubeApp/FreeTube#104]
Heyho,

positive detection on my Bitdefender: FreeTube-0.3.0.Setup.exe + FreeTube-win32-x64-0.3.0

c:\users\niemand\appdata\local\freetube\app-0.3.0\freetube.exe infected with Atc4.Detection 
c:\users\niemand\desktop\freetube.lnk infected with Atc4.Detection 
c:\users\niemand\appdata\local\freetube\freetube.exe infected with Atc4.Detection 

Threat Defense block all 3 malware attacks.

Bitdefender Antivirus Plus 2018 - Build 22.0.21.297 - Last Update 29.05.2018 18:33 o'clock
Virusdatabase 12131857 - 05.06.2018 12:25 o'clock

**Comment by LexHimself** [comment]
Zip:
`https://www.virustotal.com/#/file/10565fdf72529e34ddd54bc33e71b1a557903aaae307b3d8be69285da6a4b453/detection`
Exe: 
`https://www.virustotal.com/#/file/1df63b07fe2a388dbb15b14f22441b04a8eaba43ee5daedf968e09326c76ad7f/detection`

Since the source code is publicly available, and the above detections are false positives, just as yours, i will fill out the forms over at bitdefender. 
https://www.bitdefender.com/support/what-to-do-when-bitdefender-detected-a-clean-file-as-infected-(false-positive)-851.html

**Comment by PrestonN** [comment]
Hey there,

The cause of this is because the packages for FreeTube are not signed. I have the reasoning for this on the FAQ on the Wiki. (I would link it here but I'm on mobile at the moment.)

If you still have concerns of something malicious being in the executable, you are welcome to clone down the repo and build an executable.

Hope this helps.

**Comment by Jon-guy30** [comment]
Old thread I know, still I wanna share my thoughts. I don't think it's because the program isn't signed that it triggers certain antivirus software. I have a few unsigned software on my computer, none of them trigger the antivirus. It might be because the program is fairly new, it's not in AV databases yet, the behavior of this program might also trigger the antivirus, since it does make remote connections to the google server. Avast wanted to scan the files too, I guess it's smarter or less sensitive since it didn't flag it. And I even run it on the highest heuristic sensitivity setting.

**Comment by LexHimself** [comment]
`Dear ****,

Thank you for your patience.

We hope this email finds you well. We wanted to let you know that your request, ticket no: 2018060513560004 is currently being reviewed and you will receive a response as soon as possible.

Have a nice day!

Best Regards,
Bitdefender Customer Care Team `

This was on last friday, no update since, will keep you posted.

**Comment by Daisenki** [comment]
Hey there,

I test it today again with the newer FreeTube-0.3.1.Setup.exe and FreeTube-win32-x64-0.3.1.zip, there was no problem with Bitdefender, no problem with the archive files or the running program, nothing. I guess we can close the ticket as fixed.

Bitdefender Antivirus Plus 2018 - Build 22.0.21.297 - Last Update 02.07.2018 12:13 o'clock
Virusdatabase 12301004 - 21.07.2018 21:23 o'clock

**Comment by PrestonN** [comment]
Awesome.  If anyone ever sees an issue like this in the future, feel free to make a new issue.
