### ISSUE TITLE
Unmet dependency on Debian 11

### ISSUE THREAD

**Issue by calibs** [FreeTubeApp/FreeTube#1050]
Can't install on Debian because of unmet dependency. I install deb package using this command:
`sudo apt install ./freetube_0.11.3_amd64.deb`
And the output said:
`The following packages have unmet dependencies:
 freetube : Depends: libappindicator3-1 but it is not installable
E: Unable to correct problems, you have held broken packages.`

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: 11/Bullseye (currently in testing repo)
 - FreeTube version: 0.11.3
 - Installation Method (If applicable): deb

**Comment by PrestonN** [comment]
Hello! You should be able to install the dependency and then attempt to install FreeTube again in order to get it to work.

In some cases, you may be able to run `sudo apt --fix-broken install` to have your system automatically look for the missing dependency.

Let me know if either solution works for you.
