### ISSUE TITLE
[User Interface] arrow colour clue for history

### ISSUE THREAD

**Issue by alexxroche** [FreeTubeApp/FreeTube#1058]
Navigating away to another page, the "forward" or right-arrow should be pale and not change with mouse pointer hover, to indicate that I am at the head of the history.

This is current standard browser UI.

Change also has to aid those that are colour blind and those with vision impairment.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This should also be accounted for:

- When u first start Freetube u cant go forward or backward because u just started the application.
- Gray out the buttons on start of the application and make them not clickable when grayed out.
- Gray out when u cant go forward/backward anymore and make them not clickable when grayed out.
