### ISSUE TITLE
Input on Search Query Box must be cleared each time users proceed to get results

### ISSUE THREAD

**Issue by Raul184** [FreeTubeApp/FreeTube#1064]
**Behavior of the program**
Input persists on search query box 

**Expected behavior**
Input has to be cleared after user make a search

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to freetube
2. Input any search on search input 
3. Press Enter or Click in arrow to search and get results
3. Scroll down to results
4. See error ( Input persists on search query box after selecting a desired result)

**Screenshots**

![Enhancement](https://user-images.githubusercontent.com/39123379/109307248-9cde8180-7840-11eb-8e08-7a3ca98f43c4.jpg)

**Environment Information (please complete the following information):**
 Any environment , is a frontend bug/enhancement

**Additional context**

**Comment by Murciegalo** [comment]
Can anyone assign this issue to me? thanks

**Comment by GilgusMaximus** [comment]
@Murciegalo Yes, I can assign it to you. Thanks for wanting to contribute ! :)

But please be aware that this will only be merged if it is added as an option in the settings. Otherwise we'll have people reporting that they want this behavior changed within days after the code was merged. Because different people have different preferences, and the clearing of a search box is heavily dependent on which user interfaces a person is used to. 


If @Preston does not have an objections to this, please add the option to the general settings group as a toggle option. As reference you can take a look at the respective code over [here](https://github.com/FreeTubeApp/FreeTube/tree/development/src/renderer/components/general-settings).

Thanks for your contribution,
We appreciate it a lot :)
Best regard,
Gilgus

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just want to note here that this isnt the default behavior of YouTube tho. The way its implemented now **replicates**  the default behavior of YT,

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing because of the reason provided above
