### ISSUE TITLE
Freetube fails to fetch what wasn't yet downloaded of the video after a long pause

### ISSUE THREAD

**Issue by Porkepix** [FreeTubeApp/FreeTube#1067]
**Behavior of the program**
After pausing a video a long time ago and trying to resume it, it only plays what was already downloaded at the time of the pause, but fails then to continue beyond: it's not able to download more.

**Expected behavior**
It should be able to resume download what's come next in the video after what had already been downloaded.

**To Reproduce**
- Start to play video long enough so that it's not downloading the full video directly.
- At some point, pause it when it's not completely downloaded (the bar isn't gray up to the end).
- Come back to it say the day after, maybe 12H I can't give you precise time and resume the play.
- As described above, it'll only play what was already downloaded.cached but will fail to fetch what comes after.

**Environment Information (please complete the following information):**
ArchLinux
Freetube 0.11.3-2 installed from AUR
Local API.

**Comment by GilgusMaximus** [comment]
Hi, 
so I believe that the reason behind this is the way YouTube's content delivery network works. It basically gives a temporary session when loading the video data via the yt-dl-core. And after some time of inactivity the links to the actual video files become invalid, so you need to reload in order to get fresh and valid links.

It would be helpful to see what kind of HTTP error (Code and Info) comes out of this. In case you or someone, who wants to fix this issue, wants to check that, please press Ctrl+Shift+I to open the developer console and check what kind of error is printed once you get to the error of not loading more video content.

For a fix, the app basically has to check whether this error occurs in the video player part and then reinstantiate it from the point in time where the video stopped.

Best regards,
Gilgus

**Comment by Porkepix** [comment]
Well, at time of writing this I still had Freetube is the state described in the first message. Fired `Ctrl + Shift + I` as you adviced, devtools first appearing but only the interface, I just had the time to click Console, and then they became unresponsive. Now the whole devtools frame is white and they are not visible anymore… :(

Actually I could close them and reopen them, it's a whole new instance, but they seems unable to process the amount of errors:

![Screenshot from 2021-02-27 12-22-55](https://user-images.githubusercontent.com/709500/109385782-aaeed980-78f6-11eb-96e8-7982b09405bf.png)
Numbers grow up quickly before freezing the devtools.

I also got a coredump in my system logs: 
[coredump.txt](https://github.com/FreeTubeApp/FreeTube/files/6054274/coredump.txt)

**Comment by GilgusMaximus** [comment]
Thanks for sharing the dump. I'll go through it once I have resumed working on the project in a couple weeks.

But that is an important information. So I'll try to replicate the issue then and check what I get as possible errors.

**Comment by PrestonN** [comment]
This is something we can't fix.

YouTube changes the URL for each video in ~6 hour intervals. Once that interval has passed, your URL is now inactive and won't load. The entire page will have to be reloaded in order to grab new URLs. I doubt the errors we get are unique enough where we could detect that the URL has expired without some dedicated logic to constantly check.

The best solution would be to simply reload the page with `Ctrl + R` or reload the page manually by backing out and coming back in. If someone else wants to add logic to periodically check the URL to make sure it's correct and then refresh when it's not then I'd possible accept a PR, though I don't think it's worth implementing.

**Comment by Porkepix** [comment]
> The best solution would be to simply reload the page with `Ctrl + R` or reload the page manually by backing out and coming back in. If someone else wants to add logic to periodically check the URL to make sure it's correct and then refresh when it's not then I'd possible accept a PR, though I don't think it's worth implementing.

I thought about the control-R, but unfortunately it loses everything and bring you back to either your homepage or some empty search when I tried. Both cases you lose the information about where you was playing at. I thought it was possible to detect nothing loads anymore and query again that video at the same timing? Also, there's the console crashing issue pointed out earlier.
