### ISSUE TITLE
Suggestions from the subscribed channels' archives

### ISSUE THREAD

**Issue by manoelpqueiroz** [FreeTubeApp/FreeTube#1071]
I am very pleased to have FreeTube available, with just a few tweaks you have provided a better experience than YouTube by a long mile. The possibility to customise different profiles and allow you to separate your content is a divine gift, for instance.

In light of features that FreeTube could provide that YouTube will never do, either due to laziness or ulterior motives, I would like to propose a (perhaps) simple request: a way for looking into past content from channels without having to spend time scrolling down their history.

One of the great benefits of platforms like YouTube is that having historical content from since years ago means there is useful content lurking in the past. However, the downside is that, given the way these platforms are built, it is very hard for a user to come upon it, basically because:

1. The platform will always prioritise more recent content;
2. The "optimal" way to find old content is to be subject to the algorithm (which means not finding necessarily useful, but *trending* content instead);
3. Users are forced to find old content by themselves through countless videos that a channel (or also channels in a profile in FreeTube).

Therefore, FreeTube could improve on its separation of channels through profiles and allow for the user themselves direct which content they would wish to see. The way I see, this improvement could come in either one or more of the following:

- A button that generates a random video from the available channels to be watched;
  - This could allow for a parameter where the user specifies `n` videos to be suggested, which further expands their choice;
  - This could also have further improvements later by restricting a timeframe for this random generator;
- A search that could be queried by the user specifying a timeframe for output videos that encompass the active profile on FreeTube;
- A "this month in History" tab, listing uploads done by the channels in the active profile that were done in previous years.

This would perhaps also be a good substitute for the YouTube algorithm: while it does not allow for the discovery of new channels, it allows for the discovery of unseen content from one's favourite channels.

**Comment by PrestonN** [comment]
This is one of those features where it would only be doable if we had full access to the backend data that we were using.

Because of our method of obtaining data, we have to be smart on how often we get data from YouTube. If we get data too often, then we risk getting blocked out by YouTube.

With your suggestion, we'd have to grab potentially thousands of videos from a channel to display the information requested. Multiply that by however many channels you have and you'll be blocked almost instantly.

I appreciate the ambition and it's a neat idea, though it's unrealistic with the platform that we have to interact with. The closest we could get would be grabbing the first ~30 videos that a channel made. This would be more of a suggestion for a platform that also controls the data being used like PeerTube.
