### ISSUE TITLE
Fullscreen Problem

### ISSUE THREAD

**Issue by bozkurtovski** [FreeTubeApp/FreeTube#1072]
hi, i use debian buster xfce, on my asus tp200s laptop. and my app version is 0.11.3 beta. when i wanna watch the video infullscreen, video is freeze but sound continue.. thats problem not in the arch(aur) or fedora (rpm). its only debian's deb package. . i try downgrade release but its not fix my issue.
 ss is here, i love this app, greetings \m/ 

![Ekran görüntüsü_2021-02-28_16-48-08](https://user-images.githubusercontent.com/72918227/109420749-1dd67e00-79e5-11eb-843f-216f7139d81b.png)

**Comment by proedie** [comment]
This affects me too.

**Comment by arrowgent** [comment]
ubuntu:deb
i dont use xfce, using mate, i dont have a fullscreen issue

is this a WM (xfce) issue or a debian issue? seems more like the XFCE isnt handling it correctly.

**Comment by proedie** [comment]
Sorry for not commenting in a more verbose way, I was in a rush and then I forgot about it.

I have the same issue on my Ubuntu notebook (Intel graphics), but not on my Ubuntu desktop (NVIDIA graphics).

Both systems run Ubuntu 20.04 vanilla (ie Gnome) and on both machines I don't have any problems with other full screen applications.

However, I now gave the version from the ZIP file a try and I have the same problem there. So it's not a problem in the DEB package.

It might be interesting to note that I share Freetube's settings between both installations with NextCloud.

**Comment by DanteIgashu** [comment]
Hello!
I have a very similar problem.
I am using EndeavourOS and the Freetube Flatpak version (0.14.0 Beta) (also tried the AUR version 0.14.0-1). When I access the full screen function for any video, the screen goes all black, apparently because the interface crashes, but the audio continues working, and once I go out of the full screen function, the program's interface stays all black and the audio continues playing.
In my case, I don't have any issues of the like with the full screen function on a machine that uses Intel integrated graphics, but I do on a machine with NVIDIA dedicated graphics.
Also tested the same machine that uses NVIDIA on Windows 10 and before updating to version 0.14.0, the full screen function worked just fine, but once I updated to version 0.14.0, the same issue happens, the program does the same thing.

Is there a way I can get you a log file (if you need it) from the flatpak or the AUR versions? I was trying to get something from running the AUR version in konsole, but I don't get any info about the error there, or so it seems.
This is what I get when I run the AUR version in konsole:

[10052:0917/013407.767191:ERROR:vaapi_wrapper.cc(1073)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[10052:0917/013407.767320:ERROR:vaapi_wrapper.cc(1020)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[10052:0917/013407.767361:ERROR:vaapi_wrapper.cc(1073)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[10052:0917/013407.767406:ERROR:vaapi_wrapper.cc(1020)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
(node:9987) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `freetube --trace-warnings ...` to show where the warning was created)
