### ISSUE TITLE
Update checking broken in an earlier version

### ISSUE THREAD

**Issue by MPeti1** [FreeTubeApp/FreeTube#1084]
**Topic**
Please select what topic your discussion is about.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [x] Setup
- [ ] Other. Please specify:

**Discussion**
I'm still on 0.9.3, and I just noticed that there are newer versions of FreeTube. because the built-in update checker didn't notify me, and although I've checked the project page periodically, I failed to check the releases page too.
Just wanted to let you know, so you can send out a notification about this if you think so.

**Comment by PrestonN** [comment]
I was well aware of the problem for a while now. I did in fact [notify](https://blog.freetubeapp.io/release-v0-10-0-is-now-available) everyone when I realized there was a problem. Unfortunately the blog only shows the latest blog so if it was a while since you last opened the app then you might not have seen that notification. There isn't much I can do about it at this point, though I've already fixed the problem that caused it so it shouldn't happen again.
