### ISSUE TITLE
Need options to hide videos from feed

### ISSUE THREAD

**Issue by EvilGremlin** [FreeTubeApp/FreeTube#1105]
Specifically, option to hide video in dropdown menu, or hide video marked as watched immediately

**Comment by GilgusMaximus** [comment]
This is already available in the settings:
![image](https://user-images.githubusercontent.com/34301369/110808097-fbb1eb00-8283-11eb-881b-220445c7ee02.png)

Closing this issue

**Comment by EvilGremlin** [comment]
Yep, but not quite as convinient as default youtube webpage itself... Also, i forgot to mention, but options to "hide all" and "hide all older than / before date" will be most convenient

**Comment by GilgusMaximus** [comment]
I don't understand what the hide all functionality would do. Because what should be displayed then? An empty page only is not very useful to most users.

The hide all older than some date is similar to #1088, but again, this is not required if you subscribe to more channels or subscribed to channels that upload frequently.

**Comment by EvilGremlin** [comment]
New videos only. Now it loads set amount, no mater how old, which serve no purpose at all, only clutter the feed. Hide all is most useful for new installs.
