### ISSUE TITLE
Reload button, livestreams, transcripts, auto resolution, playlists

### ISSUE THREAD

**Issue by Tiltowait2** [FreeTubeApp/FreeTube#1125]
Hi, I have an unreliable internet connection that sometimes experiences severe packet loss.  I'd like a "reload" button to load whatever page I'm on at the moment so as to restart the connection from where it dropped out.

Livestreams that are scheduled in the future don't say anything on the "Subscriptions" page, they look like any other video. I don't know it's not broadcasting until I click on it. :( There should be a "Premieres on: %date%" line with possibly "9 hours from now" or similar on the next line.

There is no way to get transcripts.  CC works onscreen, but no transcripts that can be copied & pasted.  

When I try to change the resolution, it's...wonky.  Doesn't seem to work when I click a resolution.  I keep it on "auto" due to my crappy connection, and sometimes it goes all the way down to 144p.  This is fine for audio podcasts but with video I'd want to manually set it higher.  It will get stuck sometimes and never continue, or continue without raising resolution.  Another job for the reload button. ;)

I'd like the ability to rearrange playlists by drag and drop.  As it is now, I have to unstar it and then go off to another screen to find it again and star it to put it in front.  

Oh, and it throws a lot of errors like "Local API error" of different types when I reload the Subscriptions page.  This doesn't affect functionality that I can tell, just a bit cluttered.  Also it throws up a bunch of errors when Youtube deletes a channel. 

I'd like to say I love the software!  It does an excellent job.  It's a better Youtube than Youtube!  I especially like how I don't have to change every stream to 1.5x speed - set it once and it's done.  These are just some ideas I had while using the software.  Freetube is really well done and it's a joy to use!

**Comment by GilgusMaximus** [comment]
Hi,
great to hear you enjoy the application.
First of all, please create one issue per feature request next time. Otherwise it is hard for us to keep track of possible progress on features and bugs. 

For live streams please refer to #812 

Yes, transcripts are not available at the moment.

For the quality issue please refer to #595 

Proper playlist will be added at a later stage. At the moment we do not want to change stuff in there, as it will be redone anyways.

For the errors please refer to #1101 

I'd suggest that you convert your issue to one single issue for copying transcripts or close it and open a new one for this feature requests. Everything else is already covered by other's so there is no need to keep these things in.

Best Regards,
Gilgus

**Comment by Tiltowait2** [comment]
Well, transcripts can be worked around by just opening the video in Youtube anyway.  It's just an annoying extra step.
