### ISSUE TITLE
Importing subscriptions from newpipe.json hits rate limits on yt or  either invidous.

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#1135]
**Behavior of the program**
Importing subscriptions from newpipe.json hots rate limits on yt or  either invidous.
Clearly visible in dev tools when trying to import 561 subscriptions.

**Expected behavior**
Import should be rate limited. Large lists should be able to be imported.

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
![image](https://user-images.githubusercontent.com/43231640/112169092-2be97a00-8bf2-11eb-92ed-363aa7af393c.png)

**Environment Information (please complete the following information):**
 - OS:macOS
 - OS Version:Big Sour
 - FreeTube version:0.12.0
 
 - Primary API Used: [Local API, Invidious API]
 - Tried both and different invidious instances.

Please add a rate limit between requests otherwise this sucks :-)

**Comment by cocoonkid** [comment]
I was able to import them via a instance that apparently does not rate limit or the timeout is large enough to support it.

Still this issue should be fixed as it plays nicer with everyone involved.

**Comment by GilgusMaximus** [comment]
Hi,
so this is very unfortunate. But you are not getting rate limits here. You are getting Server errors in your screenshot. The rate limit error code is 429. Anything with 5xx is a server problem.

However you are right that rate limiting will occur with that many channels. I did not test this myself, but are the channels added anyways? (Maybe only images missing or something?)

Because then you can use rss once you are not limited anymore.
We can take a look whether it is possible to access the rss feed for channels as well when this many are imported.

> Please add a rate limit between requests otherwise this sucks
For YouTube this does not matter and we are unable to guess the amount of requests. The susbcription fetch is switched to RSS feed once you reach over 100 subscriptions, but that simply is a tested value. We also do not know how quickly you can make more requests without getting limited each day. So there is really not much we can do here besides trying to get a less expensive fetch

**Comment by cocoonkid** [comment]
So far everything is working. I will report back next time I import. With lot more details and over 1k subs.

**Comment by cocoonkid** [comment]
@GilgusMaximus  Thanks again for your explanation. Just wanted to add that 429 or 5xx doesn't really play a role here.

The reason would be the same. So throttling the import automatically to 1 every 2 seconds or so when number of imports >=300 or so would be still helpful. It also keeps  people (me) from crashing invidious instances for others :-) And clearly separate the import from a refresh , since currently both still seem to happen.

THANKS again for this wonderful tool. I'd really enriches my life. You have no idea :-)

**Comment by GilgusMaximus** [comment]
The problem is that the limit counts for usage within an unkown time frame. We cannot know what this timeframe is. 
Only safe option would be to auto split them into profiles and then load them one by one by the user.
