### ISSUE TITLE
Support for WebM in video.js?

### ISSUE THREAD

**Issue by heipra** [FreeTubeApp/FreeTube#1140]
Hi,

Upon diving into a few issues regarding resolutions above 1080p I came across [this issue](https://github.com/FreeTubeApp/FreeTube/issues/1039) . In it, it is mentioned that when videojs implements support for webm then work could start to get it working in freetube. 

Upon visiting the video.js repo I found the following [issue](https://github.com/videojs/video.js/issues/7087)
where a maintainer of video.js mentions that there shouldn't be any issues with webm playback.

Does this mean that webm support could be implemented in freetube?

Best Regards
Heipra

**Comment by GilgusMaximus** [comment]
Hi, so thanks for keeping an eye out.
Unfortunately it is not VideoJS which prevents us from implementing wide spread 4k support, but instead the [vhs plugin,](https://github.com/videojs/http-streaming/tree/v2.6.4) which we need in order to stream the video rather than download it, to support this.
So as it seems, this is not yet implemented. So unfortunately we cannot provide it at the moment
