### ISSUE TITLE
Hello, I come from issue #1137 . There is no way i can figure to get nightly. help appreciated

### ISSUE THREAD

**Issue by doritoshave3sides** [FreeTubeApp/FreeTube#1143]
Topic: Other/setup?

i come from issue #1137 . When I get onto the nightly sections or the 'actions' (https://github.com/FreeTubeApp/FreeTube/actions) I am unaware how does the author explain the process of getting one. 

Help appreciated kindly and also i am still having the issue #1137 (I know i did not do anything since then but please know that I have made a github account just for this and am therefore new)

**Comment by PrestonN** [comment]
I would ask that you please keep the discussion over in #1137 instead of creating a new issue.

On the actions page, click on the first build in the list that has a green check mark. From there, you will be greeted with a list of binaries at the bottom of the page. Pick the one that works on your system. You can install it the same way you initially installed FreeTube.

At the time of writing this, [this](https://github.com/FreeTubeApp/FreeTube/actions/runs/695952760) is the latest nightly.
