### ISSUE TITLE
Using Hooktube for all video

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#116]
Hi there. 

I just noticed the new browser (which I installed for FF). As I would expect it conflicts with the hooktube extension which opens all youtube links in hooktube.  This got me thinking, it would be really cool if all video were passed through hooktube instead of youtube. Have you ever thought about this?  If I understand correctly it would even allow you to bypass the whole google API Key (which means they know who you are anyway, right?). It would be great to see this as an option.

**Comment by PrestonN** [comment]
Sorry about the formatting. I'm typing this on mobile at the moment.

I sort of did something like this when FreeTube started. I was using the HookTube API for grabbing the videos.  Unfortunately the guy that runs HookTube noticed and closed off parts of his API. He also said that he didn't appreciate it as it could potentially eat through his server costs/usage. In an effort to prevent any attempts of "leeching" on his servers, I got rid of all dependencies of it. I think that this has been better in the long term anyways since I didn't have control of the server to begin with. The better plan is to use NewPipe's API so I can run it on my own server. This should give the best all around solution with the keys and with privacy.
