### ISSUE TITLE
Is the Tor proxy option working correctly?

### ISSUE THREAD

**Issue by SimonMGS** [FreeTubeApp/FreeTube#1169]
I use Freetube with a VPN, and occasionally get a rate limiting error, requiring me to switch to a different IP. That's completely understandable.

What I find odd, is that I have the proxy through Tor option enabled. And yet, when I get a rate limiting error, it's only by changing my VPN IP that the problem goes away. I would have thought that if connections are being routed through TOR, the VPN IP should not be significant. Am I missing something?

**Comment by SimonMGS** [comment]
After a bit more experimentation, I think the SOCKS5 Tor proxy is working - it's just that it's only creating a new circuit when the VPN re-connection forced it to.

I wonder if it might be possible to request a new circuit from TOR and retry, when one of the rate limiting errors is returned? Perhaps I should open as a feature request?

**Comment by Svallinn** [comment]
We're not bundling a Tor daemon with the app, it's up to the user to download Tor and run it on their machine themselves if they want to utilize the Tor network, the app just allows you to point at which port the Tor daemon is running on
Therefore, IMO, it makes no sense for the app itself to interact with the Tor daemon directly (although I suppose it would be possible **but only if you have a minimal understanding of the daemon's functionality, namely the control port**, which is why I'm against it)

**Comment by SimonMGS** [comment]
I see. I wasn't thinking of bundling Tor in the app.

I thought it was possible for an application to simply send the control port a "newnym" command, to cause it to create a new circuit. I believe this is what the Tor browser does when a new circuit is requested. I was thinking that it would only be a small addition to Freetube, to issue a newnym command in certain circumstances. So essentially, on a rate limit error, send a newnym command to Tor, and retry. I'd have thought that would improve functionality when rate limiting becomes an issue on a given IP.

**Comment by Svallinn** [comment]
Yes, this can certainly be done.
However, like I've stated before, I'd prefer the user to have full control of sending the signal rather than make the app do it, but I'll leave that decision up to @PrestonN.

Also, I believe Tor doesn't open a control port by default, one needs to modify the configuration file associated with it.

Therefore, the user would have to be aware of that fact for the functionality to even be useful, in addition to not mistakenly think that it's not working, which bears some influence on my preciously stated opinion.

**Comment by SimonMGS** [comment]
I can can understand the reluctance to do too much interfacing with a separate daemon, but I don't think it would be too much more than we have currently - a wiki page on how to set up Tor, and a section in the settings panel for entering the details and testing the connection.

I'd happily update the wiki to explain configuring the control port, and what the benefits are. I do think it's quite a big win to make Freetube more robust against one of the most common problems.

**Comment by PrestonN** [comment]
My stance is the same as @Svallinn where I believe that the user should have full control over the Tor daemon. At this time, we have no times on attempting to bundle the daemon along with the app. We assume that you know what you're doing when you are setting up your proxy settings, we just allow FreeTube to connect to it.
