### ISSUE TITLE
Maybe issue with multiplatform...

### ISSUE THREAD

**Issue by paramounttrivials** [FreeTubeApp/FreeTube#1199]
Hi,

Why the exclusion of android? 

I apologize for the click baitishness of the titled post, but i was not sure where else to ask. I did hit up quora about flatpak support on android though.

-Jeremy

**Comment by PrestonN** [comment]
Because it isn't worth the effort. Android already has NewPipe, which is an excellent equivalent of FreeTube and I'd highly recommend that for Android users. Making an Android version would also require a brand new code base to support it which would mean double the effort for new features. I'd much rather interact with NewPipe in some way than to try to make a new app for the platform.

As a side note, asking on our Matrix channel is a good place for discussion / questions like this.
