### ISSUE TITLE
Feature to search for videos while the current video continues to play, and a feature to queue next videos.

### ISSUE THREAD

**Issue by heretoenhance** [FreeTubeApp/FreeTube#1204]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'm always frustrated when I'm listening to a song and I want to queue another one but can't either search for it, perhaps in "another tab", nor queue it.

**Describe the solution you'd like to see implemented**
I don't know the proper UX for this but it would be really nice to be able to search for something while the video (or audio) still plays in the background and then it would be nice to have an option to queue it.

**Describe alternatives you've considered**
Nothing comes to my mind other than tabs (like browser tabs).

**Screenshots**
Sorry, I do not have them

**Additional context**
I mostly use FreeTube for music but I think that most of the people would enjoy this feature, for example while doing research on a topic, or finding a video that you don't remember well, or other similar stuff.
(I know this is two features but the queue feature without the feature to search for other videos while the current one is playing doesn't make sense)

Thank you for your work guys, you're amazing

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Good issue. Maybe a workaround for searching is that u use the Picture in picture player so u can search without closing the music.

**Comment by GilgusMaximus** [comment]
Closing as this is already covered by #519 #547
The dynamic playlist implies that we need a way to play videos in the background. Otherwise this feature would be useless.

We do not have started discussing this properly though as for this to function we first need a finished local playlist system which has now been pushed to v14.0.0 as v13.0.0 will be more of service and QOL release rather than a major feature release. But with v14.0.0 major new features are in the making :)
