### ISSUE TITLE
Filter - only from subscription channel list

### ISSUE THREAD

**Issue by presianbg** [FreeTubeApp/FreeTube#1206]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I would love to have videos only from my subscriptions when searching - no results outside of my preferred authors list.
Currently we have a search option within the channel:
![image](https://user-images.githubusercontent.com/2163486/115111496-588e7880-9f89-11eb-92c4-74025ff1d4de.png)

**Describe the solution you'd like to see implemented**
Adding an option like - "only from my subscriptions" in the filter menu will be awesome:
![image](https://user-images.githubusercontent.com/2163486/115111712-3fd29280-9f8a-11eb-87da-4ba77b67cef2.png)

**Describe alternatives you've considered**
I don't think so...
https://support.google.com/youtube/thread/29479010?hl=en

**Comment by PrestonN** [comment]
This likely won't be feasible due to how we obtain our information. We'd have to do potentially hundreds of searches depending on your subscription count and then compile that list into what is the most relevant to your search. If YouTube itself allows this then it'd be possible however in it's current state I don't see this happening.
