### ISSUE TITLE
Captions dont work in PIP

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1219]
**Behavior of the program**
When CC is enabled and u go into PIP the captions doesn't show in the PIP.

**Expected behavior**
When CC is enabled CC should work in PIP. 

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to 'https://youtu.be/EhAemz1v7dQ'
2. Enable Captions
3. Enable PIP
4. See that CC is not being shown in the PIP

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Win 10 Home 20H2
 - FreeTube version: v0.12.0-nightly-706 Beta
 - Installation Method (If applicable): Portable
 - Primary API Used: Local

**Comment by Svallinn** [comment]
This is not a bug, it's intended behavior.
The app utilizes Chromium's built in Picture-in-Picture functionality, which does not extend caption data, only video and audio streams.
Screenshot example from Chromium:
![pip_chromium](https://user-images.githubusercontent.com/41585298/115581356-77597b80-a2b7-11eb-8a37-117a171fe66c.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah my bad ty for informing me about that!

**Comment by numeropi** [comment]
Rather than a bug it's a wanted feature... if Chrome's doesn't support it, is there a way so that captions could be extracted via javascript and placed into the PIP frame ?

Firefox seems to support it: https://www.realmicentral.com/2022/03/01/firefoxs-picture-in-picture-mode-finally-supports-youtube-subtitles/

Maybe natively we could push the issue directly to Chromium here: https://bugs.chromium.org/p/chromium/issues/detail?id=942502&q=component%3ABlink%3EMedia%3EPictureInPicture%20captions&can=2

**Comment by absidue** [comment]
@numeropi No the PIP window is managed entirely by native code, you cannot change anything about it with JavaScript.

**Comment by absidue** [comment]
@numeropi No the PIP window is managed entirely by native code, you cannot change anything about it with JavaScript.
