### ISSUE TITLE
Debian package depends on libappindicator3-1 being unavailable on bullseye

### ISSUE THREAD

**Issue by mika** [FreeTubeApp/FreeTube#1229]
**Behavior of the program**

The freetube package works perfectly fine on Debian/buster, but it can *not* be installed on bullseye[1], only when upgrading from buster (and having `libappindicator3-1` still around), or when manually pulling in `libappindicator3-1` from Debian/buster. This is caused by the following dependency:

```
% apt-cache show freetube | grep Depends
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libappindicator3-1, libsecret-1-0
```

But the libappindicator3-1 package didn't make it into bullseye, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818019 + https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=895037.

It looks like it's recommended to switch to Ayatana (App)Indicator(s), and at least the libayatana-appindicator3-dev/libayatana-appindicator3-1 packages are indeed available in Debian/bullseye, as well as in previous/older Debian releases.

Note: this is related to https://github.com/FreeTubeApp/FreeTube/issues/1050

[1] bullseye is the Debian version that's currently known as testing, but supposed to be released as new stable in the next few weeks (May 2021)

**Expected behavior**
Do not depend on package libappindicator3-1, which is not available on Debian/bullseye

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Install Debian/bullseye (amd64)
2. `sudo apt install ./freetube_0.12.0_amd64.deb`

**Environment Information (please complete the following information):**
 - OS: Debian
 - OS Version: Debian 11/bullseye
 - FreeTube version: https://github.com/FreeTubeApp/FreeTube/releases/download/v0.12.0-beta/freetube_0.12.0_amd64.deb
 - Installation Method: .deb

**Additional context**

Thanks for freetube! :)

**Comment by Svallinn** [comment]
This issue is obviously better fixed upstream (which technically is already semi-fixed with https://github.com/develar/app-builder/commit/c79345743b794ccef41493decafb0b5b2eece505), but I'm not gonna wait around for a release since I don't know if it'll be happen before Debian _bullseye_ moves to stable.

We'll remove `libappindicator` for now, I'll keep an eye out for any [electron-builder](https://github.com/electron-userland/electron-builder) / [app-builder-bin](https://www.npmjs.com/package/app-builder-bin) releases and on [this](https://github.com/electron/electron/issues/27527) issue.
Also, I'll keep the discussion at https://github.com/FreeTubeApp/FreeTube/issues/1127 open until this is fully resolved.
