### ISSUE TITLE
Remember last state of theater mode

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1236]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I know there is a setting in settings page to force theater mode to be always enabled, but it would also be nice if i turn on theater mode and go to another video the theater mode stays enabled. This is also the case for when i disable theater mode i want it to stay disabled for the next video.

**Describe the solution you'd like to see implemented**
Remember the state of theater mode when next video is going to be played. This must also be enforced if autoplay is enabled and if this is going to be implemented #1220. 

**Describe alternatives you've considered**
None.

**Screenshots**
None

**Additional context**
None

**Comment by Svallinn** [comment]
As far as I can tell, this is already the case.
I've tested with the current `development` branch and it recalls the theatre mode state from one video to the next.

---

If what you are requesting is something on the lines of:
1. Go into a video and toggle the theatre mode
2. Go back to a previous page (e.g. the subscriptions feed)
3. Go into another video
4. Expect the default theatre mode to be ignored and the previous state of theatre mode to be remembered

***We will not be doing that.***
The reason is simple.
It'll just cause inconsistencies with the default setting and a user's understanding of the feature, which **will** lead to them thinking it's broken. If you want that to happen for a certain amount of time, just toggle the default setting as many times as needed.

---

If, instead, you really can't see the first scenario happening (theatre mode remembered from going from one video to the next directly), then, since you didn't mention what version of the app you have, I'll have to assume you are on an older version.

Try out the latest automated build.
If you don't know how to get one, instructions here: https://github.com/FreeTubeApp/FreeTube/issues/1209#issuecomment-821880185

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@Svallinn im on the latest nightly build. Its too bad tho that it wont be implemented. I really get frustrated about it when it happens.

**Comment by PrestonN** [comment]
There's good reasons on both side for how this should be handled. I do think that @Svallinn is right in that if we change the logic in how it's handled, then users will very likely assume that the feature is broken.

A toggle could definitely be implemented to tell FreeTube to persist theatre mode based on whatever your last toggle was. This is the only realistic way I can see this implemented.

I don't see anyone on the team planning on implementing it any time soon, however it's a valid request and we'd be open to a PR for it. Because of that, I'll re-open the issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
closing in favor of https://github.com/FreeTubeApp/FreeTube/issues/2295
