### ISSUE TITLE
[Enhancement] Ability to filter out specific channels from subscriptions list

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#1239]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Some subscribed channels release far higher quantity of videos than others, which drowns out others.

**Describe the solution you'd like to see implemented**
On the subscriptions page there should be a button next to the title just labelled "Filter Mode". When turned on, left-clicking the channels in the sidebar will instead filter them out from your subscriptions page instead of directing you to that channel. Left-clicking the channel again will filter it back in.

**Describe alternatives you've considered**
I use Profiles already but it doesn't allow dynamically changing which channels to filter out. 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Svallinn** [comment]
I don't understand how this feature would add value to the app.

As you've mentioned, you can easily just organize the channels into different profiles as necessary.
That kind of dynamic would only be necessary if you had channels that release 10 videos on 3 days of the week and the rest of the week they would release 1 video.
I've never seen anyone do that and even if they did, it wouldn't be a big enough number to justify this.

I'll be closing this, since we don't think such a feature has any utility whatsoever.
