### ISSUE TITLE
Limit Feed Per Channel | Lastest 3 Videos Only (re-request)

### ISSUE THREAD

**Issue by mrlen76** [FreeTubeApp/FreeTube#1248]
Re: https://github.com/FreeTubeApp/FreeTube/issues/1245

While that would be considered a "workaround", it's definitely not an actual or even viable solution to the problem. I'd have to unsubscribe from those channels form my main profile and resubscribe to them on several other profiles (very messy). Then I'd have to sit there clicking through the profiles constantly to see if they have any new videos (defeating the purpose of having a subscription page) -- which I am definitely not going to do. If I'm going to do that I may as well just click their actual profiles (again, defeating the purpose of having a subscription page). I am quite disappointed that this was removed from featured requests because the amount of programming to add this functionality would be quite minimal really -- and the problem I have highlighted is a real and significant one. Who do I have to pay to get this added? And how much will it cost?

**Comment by GilgusMaximus** [comment]
As suggested over at #1245, this is really not an issue. If, some YouTuber really uploads a lot and you do not want to be spammed by him, then you'll have to put him/her into their own profile.

The main problem I see with this feature are the following:
1) 3 is very arbitrary. Some channels tend to upload a lot regularly, for example some Let's play channel. Other channels, e.g. Formula 1 upload a lot, but only on the weekend where actual racing occurs. So this kind of filtering is very inconsistent.

2) You might miss that one, awesome video from the YouTuber, because he/she uploaded 4 videos, and the earliest was that amazing video. Now you will not know that this video was uploaded by looking at your subscription page. 

3) This is a very specific, and really a single use case scenario. I believe the solution with profiles is a very good and much more general compromise for this than such a restricting feature. Most people will not benefit from this, and it will just clutter more of the settings with something probably a handful of people will use. 

I hope I could point out why we believe this is not really a good idea for the project. Despite us trying to add as many suggested features as possible, at some point we have to decide that features are not useful enough for the application and userbase to be included. 

But there is always the possibility to create a Fork and only add this feature. Then you can simply keep the repository up to date with rebases / merges and have the exact features you need.

Best Regards,
Gilgus
