### ISSUE TITLE
Crash while playing: JS Uncaught Exception: Object has been destroyed

### ISSUE THREAD

**Issue by kamazeuci** [FreeTubeApp/FreeTube#1250]
**Behavior of the program**
This happens while watching a video, after some 3 min of watching. Also has happened when tried to jump to almost start of a video and also while trying to change playback speed. With different videos.

Screen goes totally blank. When I kill Window with mod+shift+q, I get the following Dialog:

```
Uncaught Exception:
TypeError: Object has been destroyed
at App.<anonymous> (/usr/lib/freetube/app.asar/dist/main.js:1:16074)
at App.emit (events.js:327:22)
```

**Expected behavior**
Program shouldn't crash.

**Screenshots**

![2021-05-03_23-04](https://user-images.githubusercontent.com/26315958/116956721-7c3e0800-ac85-11eb-8791-f7ca140f6468.png)

**Environment Information (please complete the following information):**
 - OS: Linux Endeavour OS (Arch)  with i3wm
 - Kernel 5.10.33-1-lts
 - OS Version: [e.g. Windows 10, Ubuntu 20.04]
 - FreeTube 0.12.0-4 (+19 4.49)
 - Installation Method: yay AUR
 - Primary API Used: not configured any API

**Comment by taivlam** [comment]
I also have this issue.  I just noticed after updating Manjaro today.

It happens every time I close FreeTube.  If I have a video playing when I close FreeTube, then this dialog box will pop up.  Also, the audio of the video will continue to play until the dialog box is closed.

**Environment Information**

* OS: Manjaro Linux with Xfce
* Kernel: 5.12.1
* OS Version: Stable Release (21.0.4 Ornara)
* FreeTube Version: 0.12.0-4
* Installation Method: `paru`
* Primary API: FreeTube, fallback to Invidious (the FreeTube default)

**Comment by mmghu** [comment]
I am having the same issue @taivlam describes when closing the application. It doesn't matter if a video is playing. Anytime I close the application I get a popup saying "Object has been destroyed".

Very similar setup to taivlam. Just installed Manjaro fresh last night and installed Freetube shortly after.

Environment Information

    OS: Manjaro Linux with Xfce
    Kernel: 5.12.1
    OS Version: Minimal Stable Release
    FreeTube Version: v0.12.0 Beta
    Installation Method: pamac
    Primary API: FreeTube, fallback to Invidious (the FreeTube default)

**Comment by taivlam** [comment]
Just wanted to clarify what triggers this issue: it only happens when I use the mouse cursor to click on the "X" button to close FreeTube in Xfce.  This never happens when I use the keyboard shortcut `Ctrl`+`Q` to quit the program (as I can do with nearly all Linux applications with GUIs, except for Ungoogled Chromium and Brave Browser as examples).

Additionally, this issue persists on the "official" FreeTube package from Manjaro - no surprise there.  (FYI, apparently Manjaro recently added `freetube` to its repositories.)

**Environment Information**

* OS: Manjaro Linux with Xfce
* Kernel: 5.12.1-2
* OS Version: Stable Release (21.0.4 Ornara)
* FreeTube Version: 0.12.0-4.2
* Installation Method: `pacman` (from Manjaro)
* Primary API: FreeTube, fallback to Invidious (the FreeTube default)

**Comment by taivlam** [comment]
This issue no longer occurs when I updated to FreeTube 0.13.0 from the AUR - I can't tel if this is because it was addressed by the many FreeTube changes this time around or what.

Also, I am not sure if the version of `npm` matters - I recently had to install (but more like effectively "downgrade" to) `npm6` on my Manjaro machine because I was installing the source `signal-desktop-beta` package from the AUR.

**Environment Information**

* OS: Manjaro Linux with Xfce
* Kernel: 5.12.1-2
* OS Version: Stable Release (21.0.4 Ornara)
* FreeTube Version: 0.13.0-1
* Installation Method: manual AUR installation via `makepkg -si`
* Primary API: FreeTube, fallback to Invidious (the FreeTube default)

**Comment by Svallinn** [comment]
As far as I know, we didn't do anything about it.
Or... I guess you could say we didn't know what to do about it.
It's Electron related, so incredibly cryptic by default. 😐 

If we get some more confirmations about it being fixed or after some time as passed, we can then safely close this.

**Comment by kamazeuci** [comment]
Ok. Problem went away for me too with the latest update. (running 0.13.0 beta)
So I will Close now. thanks to everybody.
