### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by Elijahu** [FreeTubeApp/FreeTube#1264]
It may not be the most important enhancement, but there are quite a lot of keyboard shortcuts in the youtube player missing in FreeTube, while FreeTube is looking very similar to youtube's website, which feels strange and may cause some confusion. 

This list is perhaps far from complete, but these are the shortcuts I'd used a lot:

[K] play/pause 
[M] mute 
[J] jump back 10 seconds 
[L] jump forward 10 seconds 
[Cursor left] jump back 5 seconds 
[Cursor right] jump forward 5 second 
[Cursor up] Increase volume 
[Cursor down] Decrease volume 
[F] Fullscreen 

It would be nice to implement these in a future version of the FreeTube player. (Perhaps in a user-configurable way, even enhancing youtube's experience.)

**Comment by orthand** [comment]
All of these shortcuts are working for me (Windows). I'm only missing one to change the playback speed but that is afaik already in development as well and has been pointed out in other issues.

**Comment by Elijahu** [comment]
That's strange… now they work for me too as expected. I guess I had a focus problem while trying them, but I can't reproduce it now.

**Comment by manuee** [comment]
The focus problem occurs when you use the mouse to click on the full screen icon:
![image](https://user-images.githubusercontent.com/105582/117638423-1c62c800-b183-11eb-80f8-cd0037f5ff3a.png)

Immediately after clicking that the button is still _in focus_ and the player is not, which I guess is what has the keyboard shortcuts bind to, so that's why its not working I believe.
