### ISSUE TITLE
get an error when importing subscriptions .json

### ISSUE THREAD

**Issue by ThatOneDev-Code** [FreeTubeApp/FreeTube#1283]
when i go to import the .json file for my 200 something subscriptions, i get this error "one or more subscriptions were unable to be imported". please help, thanks!

**Comment by jerc33** [comment]
I can confirm this bug. Here's a video of it happening:

https://user-images.githubusercontent.com/12518848/118380451-b12d5180-b5d9-11eb-8bde-27a66997d8ea.mp4


I've just recently started using FreeTube, so I don't know where the logs are. There were no crash reports generated in `~/.config/FreeTube/Crash\ Reports/
`
Any other information you might need, I'm happy to provide.
Cheers.

**Comment by PrestonN** [comment]
@jerc33 Your issue is different and needs it's own ticket. Please create one and we can help you further.

@ThatOneDev-Code please do not delete the issue template. Filling this out helps us out a lot and makes it easier for us to help you with your issue.

Getting the message that a subscription didn't import doesn't necessarily mean that it failed to import. There are a couple of reasons why that message shows up.

- A channel that you are subscribed to has been banned / removed. YouTube still includes them in the export file and obviously FreeTube won't be able to import these channels.
- Your export file contained duplicate channels. This happens more than you'd think. Obviously we don't want to import a channel twice however the app will make a note of it just in case.

At the end of the day, you need to check the file that YouTube gave you and see which channel(s) didn't import. If your file contained a channel that didn't import properly, then please send the file to me either via Matrix or email and let me know which channel didn't import so that I can further investigate the problem.

Thanks.

**Comment by jerc33** [comment]
Ok, will do.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @ThatOneDev-Code did you know what your issue was. Duplicate channels or Deleted/banned channels?
