### ISSUE TITLE
Allow changing volume by scrolling over PIP window

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1284]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
This issue is created as discussed in #1254. At this moment there is no way to change the volume in the PIP window.
 
**Describe the solution you'd like to see implemented**
When u scroll over the PIP window it would allow u to change the volume.

**Describe alternatives you've considered**
None.

**Screenshots**
None.

**Additional context**
None.

**Comment by SebTota** [comment]
I'd love to be proved wrong on this, but I do not think this will be possible to implement because a [PiP window](https://developer.mozilla.org/en-US/docs/Web/API/PictureInPictureWindow#events) does not have the same event listeners as a [regular element](https://developer.mozilla.org/en-US/docs/Web/API/Element#events). 

If we could at least get the x, y coordinate of the PiP window then it might be possible. But even if that was possible (which I couldn't find a way to do), this would only work if the PiP window is sitting on top of the FreeTube application and would not work if the PiP window was overlayed on top of another application window.

**Comment by GilgusMaximus** [comment]
@Svallinn and I also have the opinion that this is a wont implement. If, at some point in the future, someone comes along over at Electron and does this, or someone is really motivated and implements a custom PiP element in a second window or so, then this is possible, but otherwise not.
