### ISSUE TITLE
Error calling the Youtube API

### ISSUE THREAD

**Issue by annadane** [FreeTubeApp/FreeTube#129]
Seems to happen very often.

**Comment by PrestonN** [comment]
Hi there.

I know you already closed this issue (which means that FreeTube is working now) but I want to explain what happened.

FreeTube uses the YouTube API to get a majority of the information needed to be used.  YouTube forces a quota on how many times you can call their API.  This quota is reached about every other day due to the popularity of FreeTube.  We try to bypass this by having multiple API keys but that doesn't stop a few of them from being maxed out.

The plan is to eventually switch over to NewPipe's extractor API so that FreeTube won't need to use the API keys anymore.

For now, FreeTube will randomly pick an API key every time it starts up.  So if you see this error, you can restart the application to try a different key and see if that works.  You can also wait until the end of the day for the API keys to reset.  Alternatively, you can provide your own API key to avoid this issue from happening.
