### ISSUE TITLE
Dont show text on the sidebar in compact mode and increase size of channel names 

### ISSUE THREAD

**Issue by MaxiMii05** [FreeTubeApp/FreeTube#1293]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
1. The sidebar looks horrendous in compact mode. The text that is displayed next to the icons in large mode is just displayed smaller below the icons in compact mode. This reduces space for the icons which in turn leads to small icons with hardly readable text. This is especially bad in some languages like German, where long words get cut off by the scroll bar.
2. In large mode, channel names can be very small if some of the subscribed channels have long names. It makes the names hard to read. The font size is also inconsistent with the text next to the icons on top.

**Describe the solution you'd like to see implemented**
1. I suggest completely hiding text on the sidebar in compact mode as it is unnecessary. This allows the icons to be much larger which in turn improves the user experience.
2. Instead of adjusting all channel names because of one long name, I suggest using the same font size as for everything on top. Long names should be cut off as it is not necessary to read the entire name of a channel. Maybe, the full channel name could be shown as a tooltip. 

**Describe alternatives you've considered**
-

**Screenshots**
Bad 5 minute mock-ups:
1. 
![small](https://user-images.githubusercontent.com/77237423/118669987-c080ea80-b7e5-11eb-8565-adc7e62deef6.jpg)
2. 
![big](https://user-images.githubusercontent.com/77237423/118670015-c676cb80-b7e5-11eb-91d7-367da1a83f2f.jpg)

**Additional context**
I understand that it may be helpful to see the text of the icons. But as there are only 7 buttons with very descriptive icons, the text is not needed all the time.

**Comment by GilgusMaximus** [comment]
I agree that the text does not look very nice. But, I would add this as an option to remove the text in this mode. There might be users on something like a Pinephone, where when they first download now text is displayed. This is then not very user friendly. 

Text sizes are not fully 100%, so changing the CSS there would solve that issue

**Comment by JInfantesC** [comment]
Hi, i would like to collaborate in this issue. 

After fiddling around inside the side-nav i propose something like this:

![FreeTube_#1293_title](https://user-images.githubusercontent.com/7262829/119223448-0a6d1780-bae9-11eb-920c-d8fa0771e5ea.png)
Default font size for channel and on long names, an ellipsis will be visible. The HTML title attribute displays the full name on hover.

![FreeTube_#1293_option_title](https://user-images.githubusercontent.com/7262829/119223447-09d48100-bae9-11eb-9efc-0aa7e4338304.png)
For the Option labels, as @GilgusMaximus said, doesn't feel user friendly to remove the text, so i added the ellipsis and also the full name of the option displays on hover with the default HTML title attribute.

Please let me know and thank you for this "good first issue"!

**Comment by MaxiMii05** [comment]
> Default font size for channel and on long names, an ellipsis will be visible. The HTML title attribute displays the full name on hover.

This is what I had in mind when I filed the issue. Hope this gets implemented.

> For the Option labels, as @GilgusMaximus said, doesn't feel user friendly to remove the text, so i added the ellipsis and also the full name of the option displays on hover with the default HTML title attribute.

I'm not sure about this though. Having a button with text that is not fully visible does not feel very "user friendly" either. 
There are two different states of the sidebar for a reason:
1. the expanded state for showing information (such as channel names and button labels)
2. the collapsed state for consuming less space and making the app neater whithout compromising on usability

> But, I would add this as an option to remove the text in this mode.

This sounds like a good compromise but we must be careful not to clutter the settings menu with minor changes.

I would love to hear more opinions on this.

**Comment by JInfantesC** [comment]
Ok, i've been thinking, what if we remove the text like the initial idea? because we already have a button to display the text by expanding the menu. 

So, two states, expanded, and collapsed, one with text, one without:
![freetube_expanded](https://user-images.githubusercontent.com/7262829/120032165-4f151900-bfe9-11eb-8da8-72c0ba549e0e.png)![freetube_collapsed](https://user-images.githubusercontent.com/7262829/120032163-4e7c8280-bfe9-11eb-98bc-e62fe0e3bfdd.png)

In those images i  have modified a little bit the icons sizes

**Comment by GilgusMaximus** [comment]
So basically if @JInfantesC implemented this in his Fork of FreeTube, a pull request can be opened to give us the chance to check the code, test the feature and then add it to the code base if it is fine.

Or someone else can also change the app to work like @JInfantesC suggested and create a PR as currently there is none available for this issue.

Well the problem at the moment is that we have a lot of issues and lots of pr's thanks to the community. So obviously we cannot work on everything and have to prioritize. v14.0.0 will be a release focused on many new features and less on quality of life improvements for the users as well as refactoring the code base for developers. So that is why there currently are many things on hold and with the current problem of video playback due to an upstream issue, everything has come to a halt.

**Comment by JInfantesC** [comment]
Sorry for the delay. I have started a pull request.

**Comment by peepopoggers** [comment]
+1 this is a good issue
