### ISSUE TITLE
Wayland support in Gnome

### ISSUE THREAD

**Issue by skewty** [FreeTubeApp/FreeTube#1303]
**Behavior of the program**
App launches without window controls (title, min, max, close).

**Expected behavior**
App should launch with window controls.  (This is not an upstream bug; upstream labels CSD as will not fix).

**To Reproduce**
```shell
$ freetube --enable-features=UseOzonePlatform --ozone-platform=wayland
```

**Environment Information (please complete the following information):**
 - OS: Fedora
 - OS Version: 34
 - FreeTube version: 0.13.0
 - Installation Method (If applicable): rpm

**Comment by PrestonN** [comment]
Not sure where you're seeing that it isn't an upstream issue. Or even a `wont-fix` label. As stated [here](https://github.com/electron/electron/issues/27522) it _is_ an upstream issue and is not something that we can fix ourselves.

I can only recommend not forcing the app into Wayland mode until the problem is fixed (Which seems to work fine and shows window controls in a Fedora VM that I tested with). We stay up to date on Electron versions so you'll likely see the fix when it's available.

If you believe that I'm wrong and that it's something fixable on our end, I'd be more than happy to include a fix if there's one available somewhere that we can use.

**Comment by IPlayZed** [comment]
> Not sure where you're seeing that it isn't an upstream issue. Or even a `wont-fix` label. As stated [here](https://github.com/electron/electron/issues/27522) it _is_ an upstream issue and is not something that we can fix ourselves.
> 
> I can only recommend not forcing the app into Wayland mode until the problem is fixed (Which seems to work fine and shows window controls in a Fedora VM that I tested with). We stay up to date on Electron versions so you'll likely see the fix when it's available.
> 
> If you believe that I'm wrong and that it's something fixable on our end, I'd be more than happy to include a fix if there's one available somewhere that we can use.

@PrestonN Hi, it looks like the issue is fixed upstream. Will the app be updated to use a recent Electron version to enable Wayland support?
