### ISSUE TITLE
Let the Filter window push page down instead of being on top of page

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#1337]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
At the moment when u open the filter window it blocks the view of the videos that are being displayed.

**Describe the solution you'd like to see implemented**
Push the page down instead of being on top of the videos. See video.

**Describe alternatives you've considered**
None.

**Video**

https://user-images.githubusercontent.com/73130443/119567073-5f37b900-bd9b-11eb-8c23-20969c4299fc.mp4

**Additional context**
Looks like this atm.
![Screenshot (208)](https://user-images.githubusercontent.com/73130443/119699331-92cd1e80-be41-11eb-8472-191897db079d.png)

**Comment by PikachuEXE** [comment]
I actually like how it's implemented right now
But if there is an option for it I am fine

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> I actually like how it's implemented right now
> But if there is an option for it I am fine

Ah good to know that u like the way its implemented atm.
Then i think a toggle would be better.

**Comment by GilgusMaximus** [comment]
We'll likely settle with one way. Creating every graphical option as setting makes the app and the source code more and more difficult to maintain and debug. 

I'll add the Help Wanted and Discussion tags to get other's involved as well. If we have enough voices about how it should be done, then we can decide.

My opinion is the same as @PikachuEXE's . For a number of reasons:
1) It does not require any changes to the code base (obviously)
2) You can scroll up and down with the filters expanded.
3) It would even be possible to make it a bit, and only a little bit transparent, so one could look behind.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Well im not really hardcore against the way it is implemented now, but it do think it needs some kind of change. I mean im open to any suggestion to make it a bit more user friendly, i think ur suggestion of making it a bit more transparent is nice. Maybe we can do something about the width of the window too because it doesnt need to be that wide. Maybe we can make the filter window the same width as the grid?

**Comment by GilgusMaximus** [comment]
Any opinion welcome. Another option could be to have the filter panel come out on the right side (at least if your window width is enough). But that then could require different UI behavior for different screen sized again, which is also a big hassle

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> 
> 
> Any opinions are welcome. Another option could be to have the filter panel come out on the right side (at least if your window width is enough). But that then could require different UI behavior for different screen sized again, which is also a big hassle

I agree that this would be too big of a hassle. In my opinion its maybe the best to make the filter window a bit transparent in combination with making the width of the window as small as possible.

**Comment by PikachuEXE** [comment]
First try: #1360

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Wow nice, yeah i really think this could be a good implementation.

**Comment by GilgusMaximus** [comment]
Looks good imo, but I am currently going through all the pr's one by one so it might take a bit to get merged.

**Comment by dragosnfy** [comment]
I think it would be more accessible if it either was completely opaque or had some sort of frosted glass blur so that what's behind doesn't blend with it, making it harder to read the options and putting less focus on the thing that you're supposed to focus on when you open the menu. I understand why someone would want to see both the video and the filter, but you're supposed to open it for like 1-5 seconds, not watch a whole video with it shown. But I agree with the things mentioned otherwise and I like it tho.

**Comment by PikachuEXE** [comment]
frosted glass blur preview:

![1px](https://user-images.githubusercontent.com/1018543/123574875-39229000-d803-11eb-8cf2-8689549b23fe.png)
![2px](https://user-images.githubusercontent.com/1018543/123574890-3de74400-d803-11eb-853b-710251c98f35.png)
![3px](https://user-images.githubusercontent.com/1018543/123574893-3f187100-d803-11eb-8182-d99c8b3c59aa.png)
![4px](https://user-images.githubusercontent.com/1018543/123574895-3fb10780-d803-11eb-8946-7ea368afe68f.png)
![5px](https://user-images.githubusercontent.com/1018543/123574896-40499e00-d803-11eb-8cae-a5a616316685.png)

But what value do you want? (1px-5px)

**Comment by dragosnfy** [comment]
I'd go as far as 15px actually. `backdrop-filter: blur(15px);` didn't fork for me for the same element you used... not sure why... cuz I  tried it on 2 freetube versions + using `!important` and nothing. So that's why my screenshot looks a bit weird with the blur being extended more than the filter, cuz I had to do the effect on the parent element haha.

![Screenshot from 2021-06-28 10-44-03](https://user-images.githubusercontent.com/86549690/123599020-c8c54000-d7fd-11eb-8ae2-8f7a67afec7e.png)

I've done that on lots of projects and I've seen it being done with big ones as well like on macos, windows 11, spotify etc

![image](https://user-images.githubusercontent.com/86549690/123599235-0f1a9f00-d7fe-11eb-82c5-306327c67798.png)

![image](https://user-images.githubusercontent.com/86549690/123599548-628ced00-d7fe-11eb-835f-b3440722c9e5.png)

**Comment by PikachuEXE** [comment]
@dragosnfy 
If you look at my screenshot you should be able to see that I apply the `backdrop-filter` on `searchFilterInner`

**Comment by dragosnfy** [comment]
I tried the same thing before commenting, but it weirdly doesn't work haha. Btw when I mean as far as 15px, it can probably work with 10px as well, but I can't really test it since I have this css issue 😂

**Comment by PikachuEXE** [comment]
I think 5px is better otherwise can't really what's behind and the transparency would become pointless

5px
![image](https://user-images.githubusercontent.com/1018543/123574896-40499e00-d803-11eb-8cae-a5a616316685.png)

10px
![image](https://user-images.githubusercontent.com/1018543/123605224-2cfff800-d82e-11eb-9228-6fc169cca142.png)

15px
![image](https://user-images.githubusercontent.com/1018543/123605263-37ba8d00-d82e-11eb-9cb3-2314e8e5803a.png)

**Comment by dragosnfy** [comment]
Thanks for taking time to increase the number! I gave you the windows & mac examples cuz on those you specifically don't see much behind the glass, but that's the point in some designs, to put focus on the thing on top. Even 15 is less than on those pics.

Another thing is that `box-shadow` is half as important as the blur for the effect. Here for example the blur is small, but it still looks like glass a bit because of the highlights and shadows I added.

![Screenshot from 2021-06-28 12-30-00](https://user-images.githubusercontent.com/86549690/123615850-5c9f0800-d80e-11eb-96b8-5f95ae09d2c5.png)

Here's both more blur and box-shadow:

![Screenshot from 2021-06-28 12-29-02](https://user-images.githubusercontent.com/86549690/123616620-20b87280-d80f-11eb-93d1-0fa97627ccc2.png)

And here's the dark mode:

![Screenshot from 2021-06-28 12-36-59](https://user-images.githubusercontent.com/86549690/123616698-375ec980-d80f-11eb-8558-3cdb3ced07c5.png)

The reason why I think that the difference is not as noticeable is because on the current implementation there's `opacity: 0.9`, which means that the whole div is transaprent, including text, which if you make it `opacity: 0.5` you get this:

![Screenshot from 2021-06-28 12-28-48](https://user-images.githubusercontent.com/86549690/123617189-ab996d00-d80f-11eb-8614-8f096c284ebe.png)

Then you can clearly see that the blur is "faked" with the opacity of the whole div, instead of just using the `backdrop-filter: blur(30px)` I used in the screenshots (see? I went even as far as 30px and it still doesn't look flat) and having a background color that's semitransparent, like instead of `#fff` using `#fff9`.

And then another thing, light and dark modes have to have different values for the box-shadow, background-color, because keeping the same value as the light mode for the dark mode would make it look terrible. The current opacity trick only works because there's barely any visible box-shadow and cuz it's 0.9, else it would not work.

Feel free to correct me, I'm writing this in a rush, so I could be wrong about certain things and thanks for taking the time to tweak the values!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Just want to note this:

If u click on the filter icon, the filter window comes down. If the filter window is down and u click on lets say on the settings page, the filter window will still be expanded. In my opinion this behavior is annoying. It would be better to not keep the filter window expanded when u navigate to another page.

**Comment by PikachuEXE** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc 
#1479

**Comment by GilgusMaximus** [comment]
So the blur effect looks really nice and is a great idea to improve readability. But would it be possible to have the text with a higher contrast ? It still looks kinda washed and not super clear when the light theme is used,

**Comment by dragosnfy** [comment]
I think so, I'm not sure what color was used (I can check later) for the text, but black would technically have the highest contrast ratio, or if the font-weight would have a higher value maybe. And in terms of blur, it could also be more tinted towards white let's say so that they're more towards opposites, cuz it's done by both blur and a semi-transparent background color, compared to the other blur method which had a smaller opacity, meaning less contrast. I'll implement it in [my fork](https://github.com/dragosnfy/FreeTube) in the next 3 days, cuz it's faster for you to test it live that way and if you like it we can merge it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Minor difference i want to point out is that u cant see the edges of the filter window when the background is the same.

https://user-images.githubusercontent.com/73130443/125348269-85b1b380-e34b-11eb-9f73-b2e43e396aae.mp4

**Comment by GilgusMaximus** [comment]
We can continue there, but i will keep this open to have this open for any other input

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think its safe to close this.
