### ISSUE TITLE
support for NewPipe subscription groups import/export to/from freetube?

### ISSUE THREAD

**Issue by denemier** [FreeTubeApp/FreeTube#1349]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
in newpipe there is 2 export options json and db, 
So both newpipe and freetube has same feature called subscription groups / fees / profiles

**Describe the solution you'd like to see implemented**
I want to be able to import all subscription groups as profiles in freetube and export

**Comment by PrestonN** [comment]
IIRC NewPipe doesn't provide how your subscriptions are grouped together when you export them, so they'd need to update their export file before we could do anything with it.

**Comment by denemier** [comment]
hey again, looks like the freetube's own export db file is json? right?
i tried to open it with sqlite managers, then i noticed it's compressed json style, would it not better if you rename it as json? so less confusion

**Comment by PrestonN** [comment]
Our DB is read like JSON, however it's managed using [NeDB](https://github.com/louischatriot/nedb) which typically uses a .db extension. I'm sure it might be confusing however there might not be much that we can do to change this.

Also since this seems to be something that we cannot implement, I will go ahead and close this issue. If the NewPipe team changes their exported file to include groups, then we can re-open this.
