### ISSUE TITLE
Removing/Replacing HookTube integration

### ISSUE THREAD

**Issue by 2a747** [FreeTubeApp/FreeTube#136]
From the HookTube changelog: 

> - rest in pieces
> 
> - It was a good run, 1.5 years. Started as a quickly made addition to the norbot project, and within long the server had to be upgraded several times. Of course YouTube Legal was an inevitability at that point.
> 
> - July 16: YouTube api features are back but mp4 <video> is replaced with the standard YT video embed. HookTube is now effectively just a light-weight version of youtube and useless to the 90% of you primarily concerned with denying Google data and seeing videos blocked by your governments.

Since the latest HookTube updates there is really no point in supporting it in your app any longer. There is already a alternative: https://invidio.us/. I am not familiar with invidio but maybe someone else here is. Looks like a good alternative and other than HookTube it's open source: https://github.com/omarroth/invidious . Might be worth looking into. Thanks and keep up the good work.

**Comment by PrestonN** [comment]
I've already had plans on doing this.  I mentioned it in our Matrix server a couple of days ago as everything was happening.  Switching support from HookTube to Invidious will only take a couple of lines to change so it will be no issue doing this for the next release.

**Comment by thisisjustathrowaway** [comment]
So wait, what exactly happened with Hooktube?

**Comment by PrestonN** [comment]
HookTube was given a cease and desist from YouTube for their use of YouTube's API. The site has been forced to use YouTube's official player and is no longer a viable option for those focused on privacy. Because of their changes, there isn't a reason for FreeTube to continue including links to HookTube. Invidious is a new website similar to HookTube that will replace the current HookTube links in the next release.

**Comment by PrestonN** [comment]
I think the main reason has to do with the fact that HookTube became very popular which made YouTube aware of it's existence.  The other reason is that using YouTube's API in conjunction with not providing YouTube income is against their terms of use with their API.

FreeTube also uses YouTube's API, though I believe FreeTube is in a slightly better position.  Before I mention anything this is an obligatory "I am not a laywer, take everything I say with a grain of salt."

Because of HookTube being a website, HookTube provides a "service" to users by helping them bypass YouTube restrictions.  This puts HookTube as the person that is bypassing YouTube's restrictions.  Because FreeTube is a downloadable app, the user takes that responsibility instead of me as the developer.  FreeTube isn't a "service" like HookTube is and would be treated slightly different because of that.  I could be 100% wrong on everything I just said so please don't take anything here as fact.

Because you have FreeTube on your computer, they can't really shut me down since I'm not a website.  The worst that they can do is disable my API keys.  If you switched to a personal API key, you would never have to worry about not being able to use FreeTube.

Having said that, the other difference with FreeTube is that I intend on switching to NewPipe's API in the future, which will completely remove YouTube's API.  This will mean that they can't send a C&D since I'm not using their API at that point.

If anything ever does happen, I will make sure to let everyone know.  For now, and especially in the future, I feel like we are in a comfortable position.

**Comment by PrestonN** [comment]
Invidious has replaced HookTube as of #140 so I will go ahead and close this issue.
