### ISSUE TITLE
2 pretty important questions

### ISSUE THREAD

**Issue by SamIsOnMC** [FreeTubeApp/FreeTube#1436]
**Important note**
Please check other open and closed issues for a similar question before posting a new one. 

**Topic**
Please select what topic you are referring to.
- [ ] Coding
- [ ] Contribution
- [ ] Languages
- [x] Setup
- [*] Other. Please specify: how the app works, and why a vpn is highly recommended

**Question**
Hey, so does FreeTube download videos and play it and, why is an vpn highly recommended?

**Comment by Svallinn** [comment]
> Hey, so does FreeTube download videos and play it

FreeTube doesn't enable you to directly download videos, but we do provide links to the video and/or audio streams, which open in your browser on click and you can download them manually there.
They are provided in a drop-down menu of sorts on the video page (triggered by the button with an arrow pointing down):

![image](https://user-images.githubusercontent.com/41585298/122690813-23b5d080-d21b-11eb-95c5-9c098ab31eb5.png)

> why is an vpn highly recommended?

I mean, the answer to that is technically already given...
> Using a VPN or Tor is highly recommended to hide your IP while using FreeTube.

but, I suppose I can elaborate on this a bit.

The FreeTube team's main goal is to provide YouTube content while retaining the highest possible degree of privacy for its users.

We do this by not running any JavaScript from the actual website (which is basically an automatic perk of simply using the app), not using YouTube's official API to get our data, among other things.

However, making these requests to fetch the actual data still exposes a user's IP address, which is a privacy-related concern since you might not want YouTube to know what topics you like or dislike, since you don't even know what they'll do with that data (the most prominent example of this would be political views, but more casual topics can fit into this notion just as well).

That's why we advise users to use a VPN (or Tor, whatever suits you best) to hide their IP address.
