### ISSUE TITLE
is there a way to sign in?

### ISSUE THREAD

**Issue by alekksander** [FreeTubeApp/FreeTube#144]
i'd like to sign with with google account, or at least be able to view my account subscriptions and their new content. how do i do that?

**Comment by PrestonN** [comment]
Hi there.

One of the main features of FreeTube is the ability to subscribe to channels without an account.  Because of this, I do not want to make users login to something whether it's a Google account or an account specifically for FreeTube.

You can export your subscriptions from YouTube by going to the [subscription manager](https://www.youtube.com/subscription_manager) while signed in and clicking on the "Export" button at the bottom of the page.  You should download a file that you can then import into FreeTube by using the "Import" button in the settings.

Hope this helps.

**Comment by alekksander** [comment]
thanks!

**Comment by tarbear123** [comment]
i can't find the export button, i scolled to the bottom but it isn't there

**Comment by PrestonN** [comment]
The instructions originally mentioned here are outdated due to changes with YouTube. Please see [this](https://docs.freetubeapp.io/usage/importing-subscriptions/) article for how to import your subscriptions.
