### ISSUE TITLE
More visibility to SponsorBlock feature

### ISSUE THREAD

**Issue by 360fun** [FreeTubeApp/FreeTube#1491]
I just found out about this function...on a fork of NewPipe! 😅  Then I was looking for it in FreeTube and I discovered that was already implemented, which is awesome 🥳 , but would be nice if the UI had told me first. 😜

I suggest to add a label and/or button in order to:
- know if a video has a sponsor inside
- discover about SponsorBlock feature and quickly enable it

**SOME MOCKUPS**
(I made them very quick, just to give an idea, but they need further thinking)

Notify if a video contains ADS in video listing:
![image](https://user-images.githubusercontent.com/844090/124271580-eb2cc580-db3d-11eb-9cd7-ef400d392129.png)

Notify if a video contains ADS and give ability to quickly enable SponsorBlock (button appears only if an AD is present):
![image](https://user-images.githubusercontent.com/844090/124273023-cc2f3300-db3f-11eb-9c65-9a94713424b4.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
But what if a video contains ads but sponsorblock doesn't detect them?

**Comment by GilgusMaximus** [comment]
> 
> 
> But what if a video contains ads but sponsorblock doesn't detect them?

Exactly. That is my main concern here. Therefore we are not going to add the label to video elements. It additionally adds confusion, because there are also videos which are sponsored by a company but might not contain one dedicated sponsorblock. So what should be done about this?

And the ads button is basically one suggestion of #1380
