### ISSUE TITLE
FreeTube on the Mac App Store

### ISSUE THREAD

**Issue by simonSlamka** [FreeTubeApp/FreeTube#1520]
### This is just a suggestion.

On macOS, Apple by default blocks installation of third-party software that they haven't personally verified. This causes that even though you can install the app using the `.dmg` archive, you cannot open it. This security policy is enforced on users and can't be disabled on an app-to-app basis (as far as I know). You can only disable it globally, which is obviously a huge security risk.

## Knowing this, I would suggest you try to get FreeTube to the Mac App Store. I think it would help a lot of people.

Thanks

**Comment by PrestonN** [comment]
I do not believe Apple would allow FreeTube on the Mac App Store. I'd need to confirm this, however I believe they specifically do not allow GPL based projects in the app store. This isn't even mentioning that they likely wouldn't host it just to prevent Google from saying anything about it.

The security issue that your mentioning has nothing to do with it being in the app store or not. The problem is that Apple (and Microsoft) expects every application to be "Signed" with a verified certificate that tells the user that the software that you are about to install comes from the verified source that it claims to be. The issue with getting FreeTube signed is that it involves paying Apple a yearly subscription to their developer program (Which is about ~$100 IIRC) just for the privilege of having their software signed (Microsoft charges even more).

I understand that this isn't ideal, but this is something we'll have to deal with for now. We technically make enough through donations to cover these costs however I do not want to set up these certificates at the moment as I'd rather wait for FreeTube to be in a v1.0 stable state before I include them. Personally I believe that these certificates are a waste of funding however I understand the concerns of running unauthorized applications and would still like to set them up eventually. It may be a while however.

**Comment by simonSlamka** [comment]
Yeah, I know that. To clarify, by saying that you should consider putting this to the App Store I meant not just signing the app, but making it easier to get for Mac users. I myself am a member of their development program, so I am aware of both the cost and the hassle of correctly generating the keys, profiles, and certs to submit apps to their ecosystem. My issue is purely of the security kind. Guess I gotta wait then. Thanks for responding though.

**Comment by NX211** [comment]
I'm not sure that this would be helpful but I am an apple developer and I would be happy to publish free tube for the community at no cost.

**Comment by simonSlamka** [comment]
> I'm not sure that this would be helpful but I am an apple developer and I would be happy to publish free tube for the community at no cost. The App Store does definitely have some restrictions but I believe that there are gpl projects that have made it into the store. Part of the App Store agreement does say that it has to be your sole means of distribution. Maybe I can fork the project and "rebrand" it enough to pass. I will have to do some research to see how possible this is but if anyone knows better please let me know.

There are FOSS apps that are on the App Store, but still have a public repo. Signal would be an example of that.

**Comment by NX211** [comment]
Fair point @simonSlamka. Depending on what the project wants I would be happy to help out.
