### ISSUE TITLE
Add default quality setting

### ISSUE THREAD

**Issue by uranuspucksaxophone** [FreeTubeApp/FreeTube#1528]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Please describe clear and concise of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like to see implemented**
Add a list of resolutions to use as default when playing a video, also, add highest quality available like NewPipe.

**Describe alternatives you've considered**
Capability for remembering quality setting.

**Screenshots**
Sometimes people have screenshots from mock-ups or other projects. Add them here.

**Additional context**
Add any other context about the feature request here.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Add a list of resolutions to use as default when playing a video, also, add highest quality available like NewPipe.

U can already do this here:

![Capture](https://user-images.githubusercontent.com/73130443/126072443-bcf73e17-6379-4bcb-a14c-5b2c77ecf5b5.PNG)

4k is not supported in allot of videos due to a limitation see; https://github.com/FreeTubeApp/FreeTube/issues/1376  https://github.com/FreeTubeApp/FreeTube/issues/1039 https://github.com/FreeTubeApp/FreeTube/issues/1140 https://github.com/FreeTubeApp/FreeTube/issues/957

@PrestonN i think u can close this one.

**Comment by uranuspucksaxophone** [comment]
I'm sorry, didn't see the option, closing feature request.
