### ISSUE TITLE
Enhance mouse interaction with the playback-speed button

### ISSUE THREAD

**Issue by Filip62** [FreeTubeApp/FreeTube#1559]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
It's just a minor inconsistency that if I left-click the playback-speed button it speeds up the video one level but the right-click does not slow it down at all.

**Describe the solution you'd like to see implemented**
Right-click on playback-speed button slows it down one step. Middle-click resets it back to 1x.

**Describe alternatives you've considered**
It's a peculiar "issue", there are no alternatives.

**Screenshots**
None needed.

**Additional context**

**Comment by agw76638** [comment]
I would like to try this one.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Sure go for it! If u have questions about this please feel free to reach out! :)

**Comment by Skidout** [comment]
I'd like to work on this one.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Skidout unfortunately this issue should have been closed a while ago because we are close to doing a full migration of our video player. 

The migration of the video player would mean that this issue becomes absolute because this click to increase feature will be removed.

I would like to thank you for your interest in the project and hopefully there is another issue in our repo that you like to work on
