### ISSUE TITLE
Some videos don't play, others do, can't figure out why

### ISSUE THREAD

**Issue by brainscar** [FreeTubeApp/FreeTube#156]
Here's an example of a video that doesn't play in FreeTube:

https://invidio.us/watch?v=9Ww-TQUeA3E

**Comment by AdmiralAsshat** [comment]
Seconding this. I'd say maybe a third of the videos I open from Youtube in FreeTube simply don't play. [Another example](https://www.youtube.com/watch?v=6F6DIXU35Hk).

Is there a debug log or something we can enable to see what's going on?

**Comment by brainscar** [comment]
Thanks @AdmiralAsshat 

I've found out that changing the quality to 480p and then back to 720p makes it play.

Not really a solution, but might help with debugging.

**Comment by PrestonN** [comment]
With the first example given, as you've pointed out, switching to 480p fixes the issue.  The reasoning is because that video does not have a 720p version, yet FreeTube is still trying to play 720p.  I had checks to automatically switch over the quality but it looks like something went wrong with the latest update.  I'll be taking a look at it and hopefully get it fixed.

**Comment by thebrowser** [comment]
I've been having this issue recently with actually quite a few of videos that I know have 720p available. Yet, I have to change it to 480p in order to have them play (since 720p is always the default), is it just me or is this something happening as a bug?

**Comment by PrestonN** [comment]
This should likely be fixed in the next release.  If it still isn't fixed please re-open or create a new issue.
