### ISSUE TITLE
Hide the top bar on fullsceen video

### ISSUE THREAD

**Issue by danfr** [FreeTubeApp/FreeTube#16]
When passing the video on fullscreen mode, the bottom bar disapears in a few seconds but the topbar (with menus) persists.

![screenshot](https://user-images.githubusercontent.com/15647166/36992049-f72c9d8a-20a9-11e8-8b28-f470e9e4bdef.jpg)

Nice job btw ;)

**Comment by PrestonN** [comment]
I am aware of this issue.  I found this very late before I released the app but I wanted to get it out to gather feedback over the weekend.  This issue is specific to Windows and doesn't appear on other systems, which is why I didn't find it at first.  I definitely want to get it fixed though so I'll try to get it fixed in next weeks release.

**Comment by PrestonN** [comment]
This should be fixed in the latest release, so I will close this issue.
