### ISSUE TITLE
local api keeps failing for no reason and comments dont load

### ISSUE THREAD

**Issue by D0nnieD4rk0** [FreeTubeApp/FreeTube#1637]
Error: Status code: 410

title is self explanatory

**Comment by jasonhenriquez** [comment]
Hello, please use the provided template next time. These issues are fixed in 13d73d2 and #1537. [You can use the latest nightly build to use FreeTube with this fix.](https://github.com/FreeTubeApp/FreeTube/actions/workflows/build.yml) Otherwise, our next release is coming out very soon and includes this fix.

**Comment by peepopoggers** [comment]
@D0nnieD4rk0 new release is out, check releases.
