### ISSUE TITLE
Firefox: "Access your data for all websites" Request

### ISSUE THREAD

**Issue by smartspacemonkey** [FreeTubeApp/FreeTube#165]
Hi,

I've just tried to install the firefox extension, but it wants to access the web page data **for all websites** ...
Is it possible for you to change the access for **youtube only** without breaking the features ?

Thanks

**Comment by PrestonN** [comment]
Hey there, I understand the concerns that you probably have.

The extension asks for that permission because it tries to find a YouTube link on any website.  If it finds a match, it sends the request over to FreeTube.  There isn't really a way to limit it to YouTube as the extension wouldn't be very useful as that point.

If you're still concerned, you can always view the [source code](https://github.com/FreeTubeApp/freetube-redirect) for the extension.  The file itself is [very small](https://github.com/FreeTubeApp/freetube-redirect/blob/master/redirect.js) and doesn't track what you do.

Hope that helps.
