### ISSUE TITLE
Order/Filter by "unwatched"

### ISSUE THREAD

**Issue by 360fun** [FreeTubeApp/FreeTube#1760]
**Describe the solution you'd like to see implemented**
I'm subscribed to several channels with a lot of videos already online. When a new video comes in is very easy to find out and watch it. Also the "watched" state helps me a lot to keep track of what I've already seen. The problem starts when I've already watched all the latest videos, this means scrolling and clicking on "Fetch more results" to find where I was. More I watch and more scrolling and clicking needs to be done every day (I watch 3 or 4 videos per day).
All this process would be a lot easier if there would be a way to filter out what I already watched! 😄

An **Order/Filter by unwatched** could be the solution, like this:
![image](https://user-images.githubusercontent.com/844090/135096415-4318031b-f17e-48cd-b8ab-cfc57256fd30.png)

PS
I love FreeTube! ❤️

**Comment by jasonhenriquez** [comment]
There is currently a setting under Subscription Settings called "Hide Videos on Watch". Is this the behavior you're asking for?

**Comment by peepopoggers** [comment]
@jasonhenriquez Even though that may seem a solution, you would probably find yourself going in the settings often to toggle it.

**Comment by jasonhenriquez** [comment]
@peepopoggers Can you clarify what you mean? I do not use this setting, so I'm not familiar with the unfavorable behavior you are describing.

**Comment by peepopoggers** [comment]
I think he is talking about channel video sorting

**Comment by e-tobi** [comment]
Just took a look at this, because I find this annoying too. As the "watched" state is only stored locally, you can't just query all unwatched videos form YT. If there are 100 videos in the channel and you have watched the first 70 videos, in order to get the 30 unwatched videos, all 100 videos need to be queried over the network to be able to filter out the 70 unwatched videos. This is not very efficient. But on the other side - if you manually need to skip all unwatched videos, you would also need to query all 100 videos.

**Comment by PrestonN** [comment]
I'll go ahead and add on to what's been said here.

The options that are given for a channel page are the same ones that is provided in YouTube. It's setup this way because those are the endpoints that YouTube has available. When you use one of those options, we have to query YouTube to get that information. It isn't something that we already have.

So we you say that you want every video from a channel that is "unwatched", this isn't something that YouTube provides. That means that we have to fake it with the options that we _do_ have available. This means that we have to repeatedly query the "Newest" endpoint until we reach a video that you haven't watched yet. This could potentially force the app to load nearly an entire discography of videos from a channel and would take forever to load just to potentially show only a couple of videos. This isn't even considering the fact that repeatedly querying these endpoints in this manner has a very good chance of just blocking your IP for spamming their servers, which is something that has happened _a lot_ in the past. It isn't something I'm keen to implement simply because it'll absolutely lead to people complaining that the app itself is slow or they'll have no idea why they were IP blocked by YouTube.

Because of this, I can't ever imagine this being implemented, and will be closing the issue. I apologize, but something like this isn't practical with the way that we have to do things.

**Comment by Victor239** [comment]
How about just querying the normal amount of videos, it saying "no unwatched videos in first 100 videos, click here to load the next 100"? Or whichever number is suitable. I don't mind it being more manual or being slow, I just don't want the UI to be cluttered with videos I have to scroll past looking for the unwatched one.

**Comment by e-tobi** [comment]
I think it's about 30 videos loaded at once. So if you've already watched 90 videos, you would see 3 times an empty page and need to click "load more" to get to the unseen videos. This would not be much different from just showing the unwatched videos.

Maybe it would be an idea to have a time-line based watching mode where you can watch oldest to newest or vice versa and FreeTube remembers that you've watched all videos up to a certain time and only loads older/newer videos. I think the YT endbpoints have a publishedAfter/publishedBefore parameter that would allow to do such thing.

**Comment by 360fun** [comment]
I suppose you can load videos from the server "by pages", so I believe this feature can be implemented with a smart caching system; this will also reduce drastically the calls to the server and improve the general UX and loading speed:
- when the script loads a page, it saves everything in the cache
- when user watch something, script can easily hide the video and load the next page, storing it in the cache and never call for that page again
- of course it needs to load every time the 1st page, because that's where it discovers if there're new videos (unless there is another way)
- since old videos are not going to change, script can calculate which page doesn't have stored and load it directly if needed

example 1:
- when I watch the first video (30-1=29), script will load automatically the 2nd page and store it
- every time I open it will load 1st page (to check new videos) but show 1st 29 videos + 2nd 1 video
example 2:
- when I watch the 31st video, script will load 3rd page
- every time I open the channel, script will load just the 1st page, hiding all watched, showing basically the 3rd page

notes:
- of course the user can load more pages, script stores them and never ask the server again for them
- if the script detect a deleted video, it removes it from the cache
- with a button should be possible to wipe a single channel cache, this can of course create the problem we try to avoid so...
- ...loading many pages one after the other should always be managed by a time interval to avoid IP ban (first time videos will appear slowly, but after that it will be lighting fast)
- since now the script leaves 2 empty video spaces at the bottom (in fullscreen), it can load immediately the 2nd page and fill them (having already stored 28 more videos) or hide the last 2 (which will appear when something is watched)
