### ISSUE TITLE
Volume control by scolling

### ISSUE THREAD

**Issue by anxiolyt** [FreeTubeApp/FreeTube#1778]
**Volume control by scrolling**

**Is your feature request related to a usage problem (not a bug)? Please describe.**
It is not.

**Describe the solution you'd like to see implemented**
I'd like to request the feature, that you can control the volume of a video by using the mouse scroll wheel up and down.
Ideally it would be in 1% steps per scroll.

**Describe alternatives you've considered**
I've used the arrow keys but it's not as small of a step as I'd like it to be.

**Screenshots**
![volscroll](https://user-images.githubusercontent.com/3084791/135667958-a6c94a40-1f44-424d-bb45-ae5dcf73cec5.jpg)

On the top bar you can see the volume percentage.

**Comment by jasonhenriquez** [comment]
Thank you for your time in making this feature request, but fortunately this feature is already implemented in FreeTube: see "Scroll Volume Over Video Player" under Player Settings.

**Comment by anxiolyt** [comment]
Thank you for your quick response. My mistake, I must have overlooked it.
Makes FreeTube even better for me, I just discovered it today.

Am Fr., 1. Okt. 2021 um 21:06 Uhr schrieb Jason ***@***.***>:

**Comment by seascape** [comment]
New FreeTube user here.

Funny timing, because I actually came to suggest an enhancement to "Scroll Volume Over Video Player": It would be nice if some indication of the current volume level appeared over the video while adjusting via scroll wheel.

Here is a gif showing how the popular YT add-on [Enhancer for YouTube](https://www.mrfdev.com/enhancer-for-youtube) handles it, via a simple number that appears as the user adjusts with the scroll wheel:
![GIF 2021-10-03 14-22-39](https://user-images.githubusercontent.com/1672115/135771970-d6f88494-0f9f-4ca1-903f-7f40b55fc223.gif)

Just a number, from 0-100, works great in my opinion. More sophisticated presentations are possible, of course.
