### ISSUE TITLE
slows and pauses when vpn enabled, work fine when vpn disabled

### ISSUE THREAD

**Issue by pbwn** [FreeTubeApp/FreeTube#1797]
using ubuntu 18.04. Basially can't use freetube when my vpn (open vpn) is enabled, the stream freezes incessantly. If i disable the vpn then the issue disappears. Thanks for the app!

**Comment by DesignatedJM02** [comment]
If you disable the VPN and it works fine, but it doesn't work with the VPN enabled, it's likely the VPN and the speed of the connection via that VPN. I would recommend using UDP instead of TCP, if you are using TCP. I am not sure of the VPN provider you are using, but you could try changing servers to a server that is closer to your actual location or try using a server that isn't under a heavy load, if your VPN provider has that capability.

**Comment by 7echLife** [comment]
I use ProtonVPN (which uses OpenVPN) with UDP and also have constant buffering. It's annoying to the point where I stopped using the client and watch videos on Invidious instances.

**Comment by absidue** [comment]
@p-m-brown @7echLife Have you tried lowering the video quality in FreeTube and seeing if that fixes the issue? If yes, it sounds like a performance issue with your VPN or computer. Could you also check that your computer isn't sitting near 100% cpu or ram usage.

**Comment by absidue** [comment]
When the video pauses is it just the video or the whole app?
Are the symptoms similar to the ones in #1066 ?

**Comment by 7echLife** [comment]
For me it's the videos.

**Comment by Mnky313** [comment]
I have the same issue (Windows 10, 64 Bit) however I can say that it depends on the protocol being used for the VPN. 
If I use Wireguard the video hangs constantly and only plays a second or 2 at a time before having to wait for several seconds.
If I use IKEv2 there are no issues, haven't tested other protocols.

**Comment by Atrate** [comment]
I have a similar issue on Linux (Wireguard). YouTube in the browser works fine

**Comment by g3dil** [comment]
The same here.
