### ISSUE TITLE
Readme dishonesty

### ISSUE THREAD

**Issue by Larivact** [FreeTubeApp/FreeTube#18]
>FreeTube is an Open Source Desktop YouTube player built with privacy in mind.

Bundled with a proprietary, obfuscated JavaScript script by Google. You don't feel like mentioning this?

>[FreeTube] uses the HookTube API to grab the raw video files and play them in a basic HTML5 video player, preventing YouTube from tracking that video.

Directly retrieving a video from Google does not prevent Google from tracking what you watch. It improves you privacy as it gets rid of proprietary JS  but they can still track your IP address and User-Agent.

If you are so serious about privacy you should also mention that if you use FreeTube, HookTube can also track what videos you are watching and that they don't even have a privacy policy.

**Comment by PrestonN** [comment]
Hey there, I want to be as transparent as possible with everything and will answer your questions as honestly as possible.

The JavaScript from Google that you mentioned is required so that FreeTube can access their API, which is required to obtain data from YouTube.  The file that is included with the project is to reduce the amount of calls to Google's server, even if it's only slightly.  There is no way around this currently.

As for the videos, once again, there is no way around grabbing these videos.  Because the video is hosted on YouTube, something has to make a connection to their server and obtain that video.  The person using FreeTube calls the API through their system, which would send over their IP and possibly user-agent.  If you are serious about your privacy then you should have a VPN running to prevent this issue.  With FreeTube being it's own user-agent, your actual browser will probably be different from it anyways and Google shouldn't be able to link the connection back to you.

Having said all of that, the guys over at NewPipe are preparing to release their REST API sometime in the future.  The plan is to switch over to their API when possible and it will remove the need for YouTube's official API.

I hope that helps, feel free to ask anymore questions if you have any.

**Comment by Larivact** [comment]
I appreciate your response but I didn't have any questions. My issue was that your README is misleading. You call your software open source but don't mention that it includes a proprietary script, you say that FreeTube prevents tracking, when it only prevents specific kinds of tracking.
