### ISSUE TITLE
Mark destructive buttons as red

### ISSUE THREAD

**Issue by ChunkyProgrammer** [FreeTubeApp/FreeTube#1815]
**Behavior of the program**
We currently use the user's primary and secondary color preferences to inform how to distinguish destructive versus non-destructive actions. The cost of this design anti-pattern is that that is not a clear visual indicator of destructive actions, which means that it takes longer for users to process and comprehend the implications of these actions.

**Expected behavior**
[Destructive actions should be colored red](https://uxmovement.com/buttons/how-to-design-destructive-actions-that-prevent-data-loss/). If possible, we should attempt to make this red sufficiently distinct from any oher theme color (3:1 color contrast), but it is fine if it comes up a bit short against only the Red theme color. This includes certain buttons in the settings, some buttons in `ft-prompt`s, and probably a couple of other places I'm not thinking of.

**Screenshots**
![image](https://user-images.githubusercontent.com/78101139/137035364-3accd339-b709-4b02-82a3-169d159bd3f2.png)

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - FreeTube version: Nightly build
 - Installation Method (If applicable): .exe
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This inconsistency makes a little more sense with the default colors (red and blue) as I wanted it to be clear that these were different.

The buttons in question are more hard actions where irreversible changes can happen. In the default theme, these buttons are red, which makes sense in that context.

With the customizability of the app, I'm not really sure what other solution we should do at a glance. I don't really believe making all of the buttons the same color is the solution due to the nature of what some of the buttons do, but I also don't want to force the buttons to clash with the theme settings either.

I'm open to suggestions for this. I know it's a little strange.

**Comment by jasonhenriquez** [comment]
Permission to change this issue name to "Mark destructive buttons as red"? @ChunkyProgrammer

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That would mean that all buttons in the settings will basically be based on the Secondary Color Theme and the destructive ones will be red. Which im perfectly fine with just wanted to clarify this for myself

**Comment by ChunkyProgrammer** [comment]
> Permission to change this issue name to "Mark destructive buttons as red"? @ChunkyProgrammer

Feel free to update this issue or close it and make a new one
