### ISSUE TITLE
How to enable hardware decoding in linux?

### ISSUE THREAD

**Issue by xeleven11** [FreeTubeApp/FreeTube#1824]
I am using Ubuntu 20.10 x64 with Nvidia 470.57.02 X.org driver. Freetube does not use hardware acceleration for 4k videos. Software decode is enabled using dav1d and proccessor runs fine.

**Comment by ripper81** [comment]
Like with all other Apps based on Electron and also all browsers available on linux, GPU based videodecoding isn't really a thing.

For decoding AV1 Videos you'll need an Nvidia RTX 3000 series GPU. In addition to that requirement Freetube/Electron must support Nvidia NVDEC which is not the case right now. Actually no linux desktop app that i know is supporting NVDEC at the moment. There is support for VDPAU in some linux Mediaplayer Apps. However VDPAU is tied to X11 which will make it abandonware at some point because of Wayland. Also there is no support for AV1 decoding with VDPAU.

Nvidia GPU'S are better for videoencoding on linux because of NVENC but for videodecoding the situation with Nvidia is even worse compared to AMD.

I have learned that support for hardware videoencoding and -decoding is a "nice to have" feature when it comes to linux. Nothing compensates a powerfull CPU on linux.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi is this issue still valid?

**Comment by pm4rcin** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc could you reopen?  I have tried a few things but still cannot get it to work. I've tried adding those flags:
```bash
./FreeTube-0.18.0-nightly-2844.AppImage --enable-features=VaapiVideoDecoder --ozone
-platform-hint=auto --enable-features=VaapiIgnoreDriverChecks
```

**Comment by xeleven11** [comment]
I am trying to enable hardware acceleration again using chrome flags but it doesnt work on nvidia? #961
