### ISSUE TITLE
Custom proxy support

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#187]
Could you add a support for routing all the traffic through user-specified proxy server?

**Comment by PrestonN** [comment]
This will end up being a lot of effort if I start from scratch.  I currently do not have any server logic for a proper proxy to work.

One thing I've been wanting to do, and should satisfy this feature, is to allow users to specify a server to make Invidious API calls.  @omarrath already has support for a docker container for Invidious where user's could spin up their own Invidious server.  You could then point that server to FreeTube for it's API calls.  I believe the docker containers have support for video proxies which should do what everyone would expect.

When @omarrath is comfortable with his usage for 1080p+ videos, those videos will automatically be proxied through Invidious, so that should be coming soon as well.

**Comment by dimqua** [comment]
Probably much easier to allow to proxify all network requests (not just API calls) using Tor?

**Comment by PrestonN** [comment]
This will be included in the next release.  The new functionality will include the ability to set any proxy, not just Tor.

**Comment by aesthicc** [comment]
The ability to route all traffic through a proxy still seems useful. It's kind of a breaking point for me.

Keep this feature request open?

**Comment by PrestonN** [comment]
@aesthicc The request is closed because it has already been implemented. You can configure your proxy within the settings page.

**Comment by aesthicc** [comment]
Right but not *all* traffic. It still connects to youtube.com when it should only connect to the proxy if it routes all traffic.
