### ISSUE TITLE
Too many subs and sub feed fails to load

### ISSUE THREAD

**Issue by Ausk8815** [FreeTubeApp/FreeTube#193]
Cannot use 0.4.0 due to failure of subscription feed to populate.

After some light experimentation having a few subscriptions allows the feed to populate.
However upon importing my subscription list ( over 70+ ) the feed fails to populate and a loading bar loads for around 45 seconds.
Upon finishing of loading bar nothing happens, clicking subs to attempt re-population again also fails.

**Comment by PrestonN** [comment]
There are a couple of reasons this can happen.  Most likely it is because you have 1 or more subscription where their channel has been deleted or banned for some reason.  Click through each channel from your subscriptions and make sure their channel page loads.  If it does not, remove that channel.  Once you've checked all of your subscriptions, try to load them again and videos should start populating.

If you're still having issues, would you be comfortable with emailing me your subscriptions so that I could take a closer look at it?  I'd like to make this easier to deal with in the future but I do not have anything to test with at the moment.  If you don't want to share your subscriptions then I completely understand.

**Comment by Ausk8815** [comment]
That did it! Excellent.

If i may suggest perhaps adding in an error logging feature.
I'm sure you are very busy so just something to consider, thanks for the help.

**Comment by PrestonN** [comment]
It's something that I'd like to look into in the future.  I'll see what I can do about it.

For now, I'd like to make this issue easier to deal with as a user.  I was given an example file to work with and I will try to make FreeTube silently ignore this if the issue occurs.  Hopefully this should be included in the next update.

Since this has been fixed, I will close this issue.
