### ISSUE TITLE
Remove subscriptions from the "All channels" profile when they're not present in other profiles

### ISSUE THREAD

**Issue by shelmor** [FreeTubeApp/FreeTube#1933]
**Behavior of the program**
When I use a custom profile and unsubscribe from a channel the subscription remains in the "All channels" profile as an unneeded leftover. In my workflow I never use the "All channels" profile, I manually select a profile I want depending on my mood etc. Over time as I unsubscribe from various channels it produces junk in the "All channels" profile that I no longer need.

**Expected behavior**
Removing a subscription from a profile **when it is not present in any other profile** should also remove that subscription from the "All channels" profile. That way the subscription is gone completely and there are no leftovers.

**To Reproduce**
1. Create a profile
2. Select it
3. Subscribe to any channel
4. Unsubscribe from it
5. Select the "All channels" profile
6. You're still subscribed to that channel even though you shouldn't be.

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: 10 19043.844
 - FreeTube version: v0.15.1 Beta
 - Installation Method (If applicable): Portable .exe via scoop
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
I personally don't see this workflow working out as the expectations of what should happen when you delete a channel from a profile is never going to match up between users.

For example, what if I remove a channel from a profile, it removes that channel from "All Channels", but I didn't want that to happen? I just wanted it removed from one profile, but since no other profile also had that channel, now it's deleted from my subscription list and I have to go and search for it again to resubscribe. The situation you're asking for likely won't be ideal for everyone and if that's the case, I can't see us implementing it this way.

My suggestion would be to start using the "All Channels" profile when you're editing your lists. If you delete a channel from that profile, then it will delete it from all of your profiles. That will essentially give you the workflow that you're expecting.

**Comment by shelmor** [comment]
I agree that it's never to going to match between users, therefore this can be implemented as an option (off by default). Switching profiles just to unsubscribe seems tedious to me. I can also help implement it (PR) if it's something you would consider.
