### ISSUE TITLE
Incomplete input from Squeekboard on native Wayland

### ISSUE THREAD

**Issue by cihlarma** [FreeTubeApp/FreeTube#1946]
**Behavior of the program**
When launching FreeTube with the Ozone Wayland backend (this issue doesn't occur on XWayland), Phosh's OSK Squeekboard doesn't input all characters typed. The problem is not consistent between lower and uppercase letters or different keyboard layouts: different letters don't work on different keyboard layouts or when they're uppercase as opposed to lowercase (tested with the "Terminal" and "Czech" layouts). Taking the letters Q and W as an example:

Q
- works lowercase on Terminal layout
- works uppercase on Terminal layout
- **doesn't work** lowercase on Czech layout
- works uppercase on Czech layout

W
- works lowercase on Terminal layout
- **doesn't work** uppercase on Terminal layout
- works lowercase on Czech layout
- works uppercase on Czech layout

 
**Expected behavior**
All characters are input from Squeekboard to FreeTube when running natively on Wayland, just like they do on XWayland.

**To Reproduce**
1. Open FreeTube on Phosh with the `--enable-features=UseOzonePlatform --ozone-platform=wayland` options
2. Click on a text input (e.g. search box)
3. Start typing with Squeekboard

**Environment Information (please complete the following information):**
 - OS: Manjaro ARM
 - OS Version: [Phosh Beta 20](https://github.com/manjaro-pinephone/phosh/releases/tag/beta20)
 - FreeTube version: 0.15.1
 - Installation Method (If applicable):  AUR (`freetube-bin`, uses official .deb build)
 - Primary API Used: Local API

**Comment by PrestonN** [comment]
This issue is very likely an issue with either Electron, Wayland, Squeekboard, or a combination of all three. Electron apps in general from my understanding have some issues under Wayland and the fixes for this likely isn't anything that our team will be able to fix ourselves. We stay up to date on Electron releases though so whenever those fixes come around, we'll be sure to apply them as soon as we can.

I would recommend trying out a couple of other Electron based apps and see if the same issue occurs. If it does, then the issue is unfortunately out of our hands. I do know that the KDE keyboard does not work very well with Electron apps, especially compared to Phosh, so that tells me that the issues are with the keyboard itself and not with FreeTube. If you happen to find anything that suggests otherwise, feel free to let me know and I'll reopen this issue.
