### ISSUE TITLE
PiP | Picture-in-Picture enhancement (phrase change, 5/10-sec skip option)

### ISSUE THREAD

**Issue by bachig26** [FreeTubeApp/FreeTube#1953]
**Is your feature request related to a usage problem (not a bug)? Please describe.**

Phrase change: 
                           The **"Back to video player" needs to be changed to "Back to FreeTube" or just "FreeTube"**.

Skip option: 
               **Adding a 5-second or 10-second skip option within the PiP** to use the player more efficiently without opening the main window to skip.

FreeTube version: 0.15.1 beta

**Screenshots**
![FreeTube_PiP](https://user-images.githubusercontent.com/96393348/146695209-2a5508b2-a7ae-4510-8e3d-09b6ec06e850.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
@SebTota do u know if this is even possible?

**Comment by SebTota** [comment]
I don't think this is possible. There are a lot of restrictions to how PIP works and unfortunately I'm not aware of any way to customize it to add new buttons. I'm not even sure if you can have custom event handlers for the existing buttons to be quite honest since this is the issue we ran into when wanting to differentiate between the two close buttons in the PIP window.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Ah just like i thought, i looked through the documentation but came up empty. Just wanted to double check because u invested allot ur time in researching pip. 

I'll be closing this issue due to lack of support.
