### ISSUE TITLE
instances more than 1 child deep don't work

### ISSUE THREAD

**Issue by bob808** [FreeTubeApp/FreeTube#1957]
There was an issue where you could only watch videos in the main parent window, opening children windows would not load anything.
That has been corrected in a recent update, but still it works with a single level as depth. Opening a new instance/window from that child is still not working.
With earlier versions there wasn't this limitation, and it's really annoying that I can't follow new videos from child instances. For example I'm looking at a how-to video which has interesting videos in the playlist. I can't open a new one while keeping the existing one open as well. I mean I can, but it's not loading anything. I have to abandon the video I was watching and that it's pretty annoying since I can't correlate info between videos this way. Main parent window is usually where I keep my subscription list that I keep refreshing once in a while. That means that I'm stuck with the first child instances and I have to see every video in them. 
A workaround is to open a new child from the parent and navigate in it to the other video I want to have on screen at the same time with the previous child.
Is it that complicated to allow for 2-3 levels deep?

**Comment by absidue** [comment]
Please check in (whatever your OS's version of task manager is, you didn't fill in the template) and see if your computer is hitting 100% CPU, RAM or GPU usage, because I can't replicate the issue on my Windows 10 computer using the local API (I just tested 8 levels deep, I stopped testing after that).
Try lowering the video quality if you are hitting resource or network limits.

If you are using the Invidious API it's likely that you are being rate limited from their side or the random instance being chosen by FreeTube is broken. You can confirm if this is the case by opening the devtools (CTRL+SHIFT+I on Windows), switching to the network tab, then reloading the window (CTRL+R on Windows). If any of the requests in the list are red, you are either being rate limited, the server is erroring or you are being blocked by CloudFlare.

**Comment by bob808** [comment]
I'm using it on Linux. No issues with CPU/GPU usage.
I'll test this on Windows as well. Strange thing that this was an issue with Freetube before, and now it's from the OS? I think it's actually built from source (AUR package)

**Comment by bob808** [comment]
On the new window that doesn't load the video, if I turn on dev tools and look at the console output I get this:
```
renderer.js:2 Uncaught ReferenceError: require is not defined
    at renderer.js:2
    at renderer.js:2
    at renderer.js:2
```

**Comment by bob808** [comment]
Can anyone else confirm this?

**Comment by vr10t** [comment]
I can also confirm this, opening videos with middle click works only from the parent window

**Comment by bob808** [comment]
Seem I can follow other types of links, in new windows, many levels deep. It's just youtube videos that don't load.

**Comment by RippedCornet391** [comment]
I can also confirm that this occurs on Manjaro Linux.
