### ISSUE TITLE
[Feature Request]: Reduce clipboard aggression of search field

### ISSUE THREAD

**Issue by Pistos** [FreeTubeApp/FreeTube#2019]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

## Steps to Reproduce 

1. Use KDE/Plasma (Linux)
2. Use the default Plasma clipboard manager
3. In clipboard manager config, set "Synchronize contents of the clipboard and the selection" to on (checked)
1. Have some text in the search/URL field of Freetube already, e.g. `abc`
2. Go to another application, copy something, like a YouTube URL `https://youtube.com/foo`
3. Return to Freetube
4. Try to paste that URL in the search/URL field of Freetube

## Actual Behaviour

The previous text in the Freetube field is pasted (`abc`)

## Expected Behaviour

The text the user wants to paste is pasted (`https://youtube.com/foo`)

## Details

It seems that Freetube is very aggressive in re-copying the current field contents to the clipboard.  Even using the (X) button to clear the field copies the contents to the clipboard, which is kind of bizarre to me, because I don't know any other app in the history of the world which copies to clipboard when you use a UI element to clear a field.  I guess you guys have coded it to be a "select all" followed by "delete".

Maybe other people like the current behaviour, and that's fine, but please make a config setting so that Freetube isn't so aggressive with the clipboard.

(And making people change their desktop/OS settings is not a solution -- no, I do not want to change the configuration of my clipboard manager just to make it play nice with Freetube, while sacrificing the desired behaviour in every other application I use)

### Proposed Solution

Add a config setting to FreeTube so that clearing the field does not interact with the OS clipboard

### Alternatives Considered

* I could change the way I work with my OS, DE, and clipboard manager, but that is too much of an ask
* Clear the field in FreeTube first, then go copy the other thing

### Issue Labels

ease of use improvement, new optional setting

**Comment by absidue** [comment]
FreeTube doesn't interact with the clipboard when you clear the search field. This not an issue on FreeTube's end but very likely because as you mention you have this setting enabled "Synchronize contents of the clipboard and the selection".

When you click the search box? FreeTube does a select all on the textbox, this means you can copy it, start typing or paste to overwrite it.

So it sounds like what you are actually asking for is a setting to disable the automatic select all behaviour. Although this will not solve your issue because if you want to paste in the link on your clipboard you will have to clear the search box anyway, by clicking the X or selecting everything and deleting it with delete or backspace.

Essentially what i'm saying is this is an issue with your setup and not FreeTube.

**Comment by Pistos** [comment]
I'm okay with having to click the X first to clear the field, though, because that makes sense.  If I click into the field and it selects all, I can accept that that would be "user error" because it might select all text in the field.  I'm used to that already with other apps.  But what I have a hard time accepting is that, without cilcking into the field, or selecting anything, just clicking the X in Freetube (currently) also selects all the text, which doesn't make sense to me.
