### ISSUE TITLE
[Feature Request]: display download link

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [FreeTubeApp/FreeTube#2091]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

It would be nice if it would be possible to obtain download link in order to have a possibility to download video in external tool, for example i  use **Persepolis**.
In previous versions of **FreeTube** it was possible but now not ( or at least i can not fin where exactly) 

### Proposed Solution

Display download link for video.

### Alternatives Considered

Display download link for video.

### Issue Labels

display more information to user

### Additional Information

.

**Comment by truthinhoney** [comment]
Which version of FreeTube are you using? I already see a download button displayed beneath the video. The YouTube URL can easily be copied from with the share button, that can be used with an external tool.

**Comment by DracoDynasty** [comment]
> 

That's just the URL of the youtube page, which anybody can find using another web browser anyway with the title of the video.

In the previous version, there was a dropdown menu with lots of links that directly pointed to the hosted MP4 and audio files.
This was useful to download, for example, videos that are restricted to verified accounts.

As someone who refuses to send my ID and/or bank account to google, this feature was the very reason I even downloaded Freetube: to watch and save those videos.

I can still watch them, but since the application does not display those links anymore it's impossible for me to save them using external tools.
Since the internal download somehow doesn't work for me (shows "there was an issue downloading [video name]"), there's no way for me to get that video anymore.

Video example: https://youtu.be/74fG-8jPsRw

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Fixed in https://github.com/FreeTubeApp/FreeTube/commit/cf1de6302c7e2c689c3a887b3b59b09043efc04d
