### ISSUE TITLE
[Feature Request]: Sponsorblock Submit segments

### ISSUE THREAD

**Issue by Mystqr4** [FreeTubeApp/FreeTube#2170]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

Currently Freetube only allows Sponsorblock to work if the segments have already been created thus forcing me back to a web browser to create and submit segments and then watch it on Freetube which kinda defeats the purpose of going back to Freetube and watching it through that.

### Proposed Solution

Allow the creation of Sponsor segments through full sponsorblock implementation allowing Freetube users to create and submit video segments as you can through a web browser.

### Alternatives Considered

Full implementation of Sponsorblock which includes allowing the creation and submission of sponsor segments in a similar way one can do through a web browser.

### Issue Labels

improvement to existing feature, new keyboard shortcut, new optional setting

**Comment by PrestonN** [comment]
We have zero plans to allow users to submit data to Sponsorblock. The reason is because FreeTube is a privacy first application. We want to generally encourage users to accept in video sponsor segments as it is currently the most viable form of advertisement that is also private by design. If we continue to accept and encourage sponsor segments, then it will hopefully discourage YouTube and other services from implementing more invasive forms of advertisements.

Having said that, we're well aware that Sponsorblock is popular and have made the decision to include a basic implementation of it. Because of our stance to sponsor segments we will not be including a way for users to submit data and contribute to Sponsorblock as a compromise to including the feature in the first place.

You can read our full response [here](https://docs.freetubeapp.io/usage/sponsorblock/#disclaimer). I hope you understand.
