### ISSUE TITLE
[Feature Request]: Add nightly flatpak build

### ISSUE THREAD

**Issue by 0x6e656b6f** [FreeTubeApp/FreeTube#2225]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

There is no nightly flatpak build.

### Proposed Solution

Add a nightly flatpak build using Github Actions.

### Alternatives Considered

The build can be automated on the flatpak repo.

### Issue Labels

ease of use improvement, improvement to existing feature

**Comment by PrestonN** [comment]
I've considered it and I think it would be neat to do. It'll be a little bit of effort though as we'll have to automate a way to upload the artifacts to the website server since Flatpaks need a base app to build from and we can't use Artifacts stored in GitHub Actions. It can be done it just isn't something that we can do very quickly.

**Comment by zestygrass** [comment]
I'm in support of this, nightly builds literally kept the app working while there was no official release in the last while. This would help anyone stuck on the old version of flatpak build with bug fixes/features available in nightly.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Going to close this as there isnt a valid reason for this to implement 

> nightly builds literally kept the app working while there was no official release in the last while. 

We are updating the application very quick when it breaks and we are releasing faster than ever. 

The situation before this is that we maybe had a release 2 times a year.
