### ISSUE TITLE
[Bug]: Visual errors and video flicking since v0.15.0

### ISSUE THREAD

**Issue by ZibiCat** [FreeTubeApp/FreeTube#2235]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Hello, I have used Freetube for a while now and everything was working fine until v0.15.0 released where visual errors started occurring. I downgraded back to v0.14.0 as a "temporary" thing until hopefully the issue would fix itself. v0.14.0 is far less usable now so I would like to upgrade to v0.16.0 but again, I get visual errors. I am using Local API and Legacy format. There is a video attached below to show the errors in action. I can add any more info/details needed upon request.

In Settings:
1. Open Freetube
2. Go to settings
3. Open and close menus, change settings, etc
4. Encounter visual errors

In player:
(DASH formats infintely load so legacy is used)
1. Open video
2. Play video
3. After a while, black flickering occurs

I can't get the video under 10mb for Github's limit: https://we.tl/t-Eh72f3rhhW

### Expected Behavior

Freetube should function without visual errors

### Issue Labels

visual bug

### FreeTube Version

v0.16.0

### Operating System Version

Windows 10

### Installation Method (If applicable)

.exe

### Last Known Working FreeTube Version (If Any)

v0.14.0

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I think u mean since v0.15.0

**Comment by ZibiCat** [comment]
> Dont u mean since v0.15.0?

Yes, fixed.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Link expires in 7days so i took the liberty to download and compress the video so i can upload it here.

https://user-images.githubusercontent.com/73130443/167311328-9c788516-a163-40a9-8c16-6532cf0d41e3.mp4

**Comment by absidue** [comment]
@ZibiCat Those issues look like they could be caused by something outside of FreeTube. I tried both the installer and the portable .exe and can't replicate either of your issues on my computer on FreeTube 0.16.0.

1. When did you last update the drivers for your graphics card? Try updating them if you haven't done so in a while.
2. I see you have a custom animated mouse cursor, could you please try disabling any operating system customisations you might have like wallpaper engine and see if that fixes the issues, specifically anything that might be causing transparency issues.

Please report back if either of those fixed the issue for you.

**Comment by ZibiCat** [comment]
@absidue Thanks for the swift response, I have updated my drivers - my cursor is not part of any wallpaper engine or the like, but I disabled f.lux in case it was doing anything. No luck, still the same flickering and visual artefacts as shown in the video.

**Comment by yontekh** [comment]
I am also experiencing this issue.

https://user-images.githubusercontent.com/77578151/168379159-49e2ad82-15d8-461e-a5f3-14e250ddff0f.mp4


Windows 11, tried disabling ll thirdparty background processes, still happens.
I have a 3080, latest game ready driver.
1920x1080 with no scaling.

The interesting thing i noticed, is that this only happens when the UI is hiding or hidden. when I move the mouse over the video it does not happen (see video attachment)

**Comment by absidue** [comment]
@ZibiCat @yontekh Do either of you use gsync or freesync? If yes do you have gsync enabled to run for only fullscreen apps are also windowed ones?

**Comment by absidue** [comment]
This is the setting I mean. I still can't replicate the issue but other apps like the Windows Terminal (https://github.com/microsoft/terminal/issues/649) have experienced flickering when that setting is set to "Enabled for windowed and full screen mode".

![gsync_settings](https://user-images.githubusercontent.com/48293849/168422829-49bdd3f7-e840-4653-96bb-d68eae767bf3.png)

**Comment by yontekh** [comment]
The issue happens regardless of having G-Sync enabled or disabled. Also tried setting my refreshrate from 120hz to 60hz.
I will likely be reinstalling Windows 11 on my PC soon, will report back then aswell.

**Comment by ZibiCat** [comment]
@absidue I do not have GSYNC enabled, nor the ability to. I noticed that both me and @yontekh both have NVIDIA cards so it could possibly be linked to that?

**Comment by absidue** [comment]
It's possible that it's because of NVIDIA cards, I don't suspect it is though as i'm on Windows 10, with an NVIDIA card and the latest game ready drivers and I don't don't have the issue.

**Comment by yontekh** [comment]
I reinstalled Windows 11, its working now on 0.16.0

**Comment by netruitus** [comment]
I found a solution. At least it works in my case.

1. Go to NVidia Control Panel
2. Manage 3D settings
3. Turn off "Multi-Frame Sampled AA (MFAA)"

I had the same issues on my Windows 11. Freshly installed, NVidia card, latest drivers, without G-Sync.

**Comment by absidue** [comment]
@netruitus Thanks for finding out the root cause of this issue.

**Comment by ZibiCat** [comment]
@netruitus Can confirm this works, thanks for solving this issue! Will close this issue now.
