### ISSUE TITLE
[Bug]: YT Shorts videos are labeled 1:00 long

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#2243]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.

### Describe the bug

Go to the trending page and see that shorts are labeled incorrectly. 
Go to https://youtube.com/channel/UCGpf7WX7R1one-NwOvg_PbQ and see that shorts are labeled incorrectly.
![Screenshot (255)](https://user-images.githubusercontent.com/73130443/168316212-48b229b0-dfb2-4b28-abcc-b5df49b48a58.png)

### Expected Behavior

Shorts should be labeled with the correct timestamp.

### Issue Labels

text/string issue, visual bug

### FreeTube Version

https://github.com/FreeTubeApp/FreeTube/commit/be6aa3ee069191fdabf8319c5fd5578bbcdbbb2d

### Operating System Version

Windows 10 Home 21H1

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
In the other issue you mention that it's wrong on channels too, which you haven't done here. The links in both issues point to a video, I'm assuming that is not intentional? For the channel pages this pull request is probably going to fix it: https://github.com/FreeTubeApp/yt-channel-info/pull/75. To fix it on the trending page [yt-trending-scraper](https://github.com/FreeTubeApp/yt-trending-scraper) will likely need a similar fix.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
you're right i have update the url
