### ISSUE TITLE
When will freetube natively support the use of Tor hidden services as invidious proxies.

### ISSUE THREAD

**Issue by Destroyinator69420** [FreeTubeApp/FreeTube#2270]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.

### Problem Description

I prefer to use a hidden service hosted by incognet, it is available on the clearnet, Tor, I2P and Yggdrasil. I like its simplistic interface and its active maintenance of the invidious source code. I use the onion site daily, but when will I be able to use it with freetube, since I prefer the desktop app over the website in this instance.

### Proposed Solution

This would not need a large overhaul of the source code but instead a minor refactoring to allow the app to parse .onion domains if the tor proxy is on. If it is not, the app should tell you to turn it on.

### Alternatives Considered

I could just use the clearnet version, but I find that onion sites are much faster in practice, even if there are more hops, as there are never enough exit nodes.

### Issue Labels

new optional setting

**Comment by ChunkyProgrammer** [comment]
The issue comes with this comes with determining whether the proxy being used is a TOR proxy or not. I think by "natively support" you mean the autocomplete working for invidious onion domains? If that's not what you mean then I would like to add that you should be able to type onion domains into the invidious instance box even though it won't autocomplete.
