### ISSUE TITLE
PeerTubeify whenever possible

### ISSUE THREAD

**Issue by Shamar** [FreeTubeApp/FreeTube#237]
Looking at @omarroth invidious, I've learnt about both FreeTube and the [PeerTubeify](https://gitlab.com/Ealhad/peertubeify) browser extension.

The issue with PeerTubeify is that you must be on YouTube to find the same video on PeerTube.

It would be nice to have such feature on FreeTube, so that if I get a link to a YouTube video, I don't need to visit it in the browser to see if a PeerTube copy exists.

**Comment by Randshot** [comment]
@Shamar You can paste YouTube/Invidious links into the search field in FreeTube. It will open the corresponding video.

**Comment by Shamar** [comment]
@Randshot maybe I'm missing something but this doesn't address the issue I'm talking about.

The point is using FreeTube to let users consume videos from PeerTube whenever they are available, further reducing the data collection about the user (that might be identified even just though the connection IP).

**Comment by foNYWZc** [comment]
I was thinking of this exact same thing! I just recently got into Peertube and think it's a great platform.
It would be cool if you could set a PeerTube instance(or possibly multiple instances) in the settings (similar to how you can set an invidious instance) and FreeTube would search both Invidious AND the PeerTube instance you set in settings.

This would make FreeTube the perfect One-Stop-Shop destination for both Youtube and Peertube content.

**Comment by bepolymathe** [comment]
Any news about this ?

**Comment by PrestonN** [comment]
I'll ask the same question that I asked when someone asked me about a similar feature, except with LBRY:

If the reason is to avoid the direct connection to YouTube, then what is the benefit of including this over the existing functionality to proxy through Invidious?  Your privacy would be virtually identical in both situations and I'm hesitant to include such a feature when there is a redundant result.  I likely won't look into it if this is the case, however I'll accept a pull request if someone want's to work on it.

I think what's trying to be asked is for full PeerTube support, which is an entirely different conversation (and should be a new issue).  I'm a little more open to having this conversation, however there would need to be some serious discussion before I make such a decision.  I'll save my opinion on it for when that issue is created (If this is what's being requested).

**Comment by bepolymathe** [comment]
I actually think the major interest would be what corresponds to the second part of your answer... making peertube accessible from freetube. 

I think there's an interest in that because it would be particularly convenient to manage all your videos from the same application. But it's a big job (subscriptions, etc)... I'll understand if you say no.

**Comment by jibe-b** [comment]
I think I am suggesting a similar feature #625
