### ISSUE TITLE
[Bug]: too many to list .. everyone happened after updating today to the latest version

### ISSUE THREAD

**Issue by avincent98144** [FreeTubeApp/FreeTube#2442]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

the new errors message scroll SOOOO fast I can't even snap screenshots effectively. I tried and those are attached.

Never had any of these error messages before this latest update! Nothing else changes=d and it's persistent thru reboots.

No icon images in the left pane and no images at all in the main pane. see screenshot.

None of the channels will load the content. I've tried 20+ See screenshots. Just an empty .. placeholder?

The instances are not down and are fine on my iPad with other apps that use the same ones.

### Expected Behavior

to work without any errors like it did before this update. what happened??

### Issue Labels

content not loading, feature stopped working, usability issue, visual bug

### FreeTube Version

0.17.0 (0.17.0)

### Operating System Version

12.5

### Installation Method

.dmg

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

I don't know

### Additional Information

<img width="1196" alt="Screen Shot 2022-08-01 at 4 45 58 PM" src="https://user-images.githubusercontent.com/65172111/182264003-078134bd-f163-460c-b463-e7c75014f671.png">
<img width="1" alt="Screen Shot 2022-08-01 at 4 46 08 PM" src="https://user-images.githubusercontent.com/65172111/182264006-aff520f1-fced-4bed-84a5-00be10315d9d.png">
<img width="1270" alt="Screen Shot 2022-08-01 at 4 46 18 PM" src="https://user-images.githubusercontent.com/65172111/182264008-d717821a-bdf5-4db0-8acc-4ac380f9ebb8.png">
<img width="682" alt="Screen Shot 2022-08-01 at 4 46 23 PM" src="https://user-images.githubusercontent.com/65172111/182264009-b0d54630-be77-43aa-be22-ff59bf04003c.png">
<img width="421" alt="Screen Shot 2022-08-01 at 4 46 38 PM" src="https://user-images.githubusercontent.com/65172111/182264010-f55de1a5-88ee-4b20-bb6b-2bbeb875e05d.png">
<img width="1171" alt="Screen Shot 2022-08-01 at 4 49 51 PM" src="https://user-images.githubusercontent.com/65172111/182264012-721cb0a0-e108-49de-8b69-27868169c444.png">
<img width="1724" alt="Screen Shot 2022-08-01 at 4 50 11 PM" src="https://user-images.githubusercontent.com/65172111/182264015-e8763023-612a-4118-95dd-192b99f8e2ee.png">

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
U need to be connected to a network before starting up the application

**Comment by avincent98144** [comment]
What?

If you mean the internet .. of course I am. All else is working as expected other than this latest build of FreeTube. I searched for the previous build so I can go back to that, but it’s not linked on the site.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Can u provide a screenrecording.

Show that ur connected to the internet -> open application -> (if errors show) CTRL + Shift + I to see the logs and errors in console. Im only interested in seeing the red errors.

**Comment by PrestonN** [comment]
Hey there. Do you happen to have the proxy enabled within the app? I've seen this happen when it's enabled. Disabling it should fix it if that's the case.

**Comment by avincent98144** [comment]
no proxy already confirmed disabled

**Comment by avincent98144** [comment]
Also tried several other instances - same thing.

**Comment by avincent98144** [comment]
vids are over 20mb, taking a while thru email.

**Comment by avincent98144** [comment]
Attachments available until Aug 31, 2022
attached.

How to save the log file?

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FASRSdMcVPOq0HUp3DQDHusFFgqNeAdF8rQI_g09bcBvvzZPTguhwSu4y%2F%24%7Bf%7D%3Fo%3DAsPvPDrdvAW4smhgnguYdDbXGPtRpQnDWU4CFOfegHRE%26v%3D1%26x%3D3%26a%3DCAog4Y1p-7QpPUWVbQTfw6naSgoYEb7aEqopMRKiZDNzDXcSdhCe4J3gpTAYnvCYtK8wIgEAKgkC6AMA_wJ6N1VSBEWCo15aBHBK7jJqJWaYwEvV-ru3DdiXwzSF6FoCAfhW9LqbB18gdwU5tgNc7xbk-l1yJc3EVj8cW-ZbR_JkmRwI8D_A_SKZhO9XyoBiWQcXdiuu9mwh2-c%26e%3D1661993367%26fl%3D%26r%3D8EB012BB-67B1-4626-9AB0-3A96B49C1C65-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D51EC4C23-EE47-43B6-8E5D-09EE9072C26A%26p%3D44%26s%3Du1gwlECiT2dZVohIee_wLUrGfNY&uk=gFPsy9iwlGsy0k2FRq-Few&f=IMG_1574%202.MOV&sz=236775311>IMG_1574 2.MOV
236.8 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAZKCqsYdG6BMTS_F66pKPOrh6IWBAZ7kjhlBZGJ0_XvQQoSCLj6rkFiT%2F%24%7Bf%7D%3Fo%3DAg7P83KjFJsRh_C4lJaQEOATeW9SZkC0XIPEkXrU-WJo%26v%3D1%26x%3D3%26a%3DCAogu2X7y4_K498qXzIaoHxbvf_z73rdPViulffjheKwVGcSdhCP3p3gpTAYj-6YtK8wIgEAKgkC6AMA_yqdPmVSBOHohYFaBKuQWJNqJbTeoCwQSo8JzlC8IjE1CTdYqt94PR7Qg1ARTPhUxAC9JYa6l-NyJeOjq7D8_W3wgj66p1BNXOr5G07-5TylkiU7G5HYniud5xVMt98%26e%3D1661993367%26fl%3D%26r%3D3A2C1BA9-F402-4690-A081-FADC0BE45276-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3D51EC4C23-EE47-43B6-8E5D-09EE9072C26A%26p%3D44%26s%3DUKdjl_XkwwaijrlOOYLXJUZzzi0&uk=OqIBOQluLqqxG6Ya-hQXcg&f=IMG_1575%202.MOV&sz=222736798>IMG_1575 2.MOV
222.7 MB

**Comment by avincent98144** [comment]
Red errors in the log are a dozens and dozens.

How to get log to you? Can not find a way to save it.

**Comment by avincent98144** [comment]
> Hey there. Do you happen to have the proxy enabled within the app? I've seen this happen when it's enabled. Disabling it should fix it if that's the case.

Confirmed no. Never used

**Comment by PrestonN** [comment]
The root issue here is that FreeTube cannot make a connection to it's destination (Which is Invidious in this case). There's a couple of reasons why this might be the case.

1. There's an issue with your internet connection (Which you've already said you do not believe to be the case)
2. The app is attempting to connect through a proxy and cannot create a connection with said proxy (Which you've also said isn't the case)
3. The server that FreeTube is connecting to is having issues (You said you tried different Invidious instances, so this also likely isn't the problem)
4. There is a third party app or service that is preventing FreeTube from connecting to it's destination (One that we haven't tried yet)

Regardless of what the issue is, everything is leading up to the idea that the issue seems to have something to do with your current setup, and not with FreeTube itself. You'll likely need to figure out what it is that is blocking FreeTube and it's not something that we'll know ourselves without having access to your system. It's very likely that running FreeTube on a clean system wouldn't be having these issues.

Here's a couple of things you can try.

1. Double check your internet connection. I know you said that everything seems to be working, but if you're running some sort of VPN or if you're connected through Tor, then double check and make sure that isn't interfering with FreeTube.
2. Double check your Invidious instance. Make sure the Invidious instance you're connected to is working properly. Try connecting to it in your browser and see if it works. Check and make sure that the instance that you've given FreeTube is inputted correctly (It must have the `https://` prefix for example or else it will not work). Try connecting to several different instances if you can. Some instances block API access and could be doing so in this case.
3. Check for third party applications. This could be an app such as little snitch, your VPN app, or possibly even your router that might be blocking connections on your machine.
4. Try FreeTube on another device. This may or may not actually help, but it might help narrow down the issues, especially if your second device is also having issues.

We can only give you suggestions on what to try, but the real issue is going to be something that only you'll know. Something external is blocking FreeTube from doing what it wants to do and it won't be able to function properly until that's figured out. I'm sorry that I don't have a better answer for you, but it seems to me that outside of what I just suggested, you might be on your own in figuring this out.

**Comment by avincent98144** [comment]
There is absolutely nothing blocking my internet, all other apps that need it are working as expected. No VPN enabled. I use it only for special needs. Freetube [FT] app and any connections needed has long since been whitelisted in all relevant services [Adguard, LittleSnitch, Lulu, etc.] and never had this kind of debilitating issue. I have checked now over 35 instances, all connect thru Safaire [STP] as expected. yet not working in FT.  If my browser can connect to those 30 different instance, why not FT? I just Re-confirmed that my router config is not blocking - never did. I have now 100% disabled Adguard, Lulu and LSnitch - rebooted. Same FT issue. What is frustrating is this AM FT was working. I use FT several hours a day. Right up to the update and when I continued FT after the build update - all these issues now endering FT unusable. That was in the space of 30 minutes.

**Comment by avincent98144** [comment]
How to get the log to you?

**Comment by avincent98144** [comment]
Just logged into my Dev Test OS user account [factory OS and no 3rd party apps, nothing else]. Fired up FT .. same issue! I am convinced this has zero to do with my Mac, my internet or anything related and not seeing how you can not agree.

**Comment by avincent98144** [comment]
Also, I'm not seeing on your site where I can get the build right before this latest one. It makes sense here that since it was working as expected, I want that version back. My TimeMachine does not backup the apps folder otherwise .....

**Comment by PrestonN** [comment]
I don't think a log would be beneficial even if there was a way to send it to me. I have all the information I need from the screenshots you sent me.

All of our previous releases are located [here](https://github.com/FreeTubeApp/FreeTube/releases). Go ahead and give that a try and we can go from there.

**Comment by avincent98144** [comment]
v0.16.0 is now installed and I have zero issues. 

Sure hope I was the only one who had this level an issue to render the app useless but either way I still feel it’s worth your time to review logs. 

As a fellow [Apple] dev, that is in the top 5 of troubleshooting and this is not a small issue, whatever it is.

I reviewed the 0.17.0 change log and nothing jumped out, but then again I don’t dev in the electron space.

Cheers
Anthony Vincent

**Comment by sol8712** [comment]
Seems like OSX and Electron have been having some issues lately(as osx has removed python2) the Electron team is fixing things as they come up, Freetubes electron verision might just barley be out of date for breaking mac support.

Freetubes versions of electron was last updated to fix a new electron-osx bug, but that update hasnt worked for everyone, and another electron update maybe needed by FT.

FT should maybe update electron-builder from 23.0.2 to 23.1.0.

**Comment by avincent98144** [comment]
Thx for the update. I had zero issues with v16, so went back to it.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @avincent98144 do you also face these issues on the latest release v0.17.1?

**Comment by avincent98144** [comment]
Yes .. and ONLY 0.17.1.

I went back to the 0.16.x version as I had no issues at all with it and is still working as expected. whatever changed in 0.17.1 rendered the app 100% useless.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Is this still an issue on [the latest nightly build](https://docs.freetubeapp.io/development/nightly-builds)?

**Comment by avincent98144** [comment]
I’ll wait until the next public version

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Next release can take a couple of months. There is a high chance of it already working for u in the latest nightly build. I recommend to give it a try.
