### ISSUE TITLE
video aspect ratio

### ISSUE THREAD

**Issue by kokolo12325** [FreeTubeApp/FreeTube#2538]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

It has no function to change the aspect ratio of the video.

### Proposed Solution

Maybe like in MPV Player (circular aspect ratio).

### Alternatives Considered

TamperMonkey (YouTube aspect ratio switcher)

### Issue Labels

new keyboard shortcut

### Additional Information

![image](https://user-images.githubusercontent.com/61141914/188310279-f20221c3-fc8c-4adb-a07a-c5c2212b405e.png)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
The only use of this would be if the uploader messed up the video when they uploaded it but that is not something that we should be handling.

Courtesy of @absidue

**Comment by seascape** [comment]
I came to see if there was a feature request for this after encountering another video in FreeTube with a distractingly broken aspect ratio.

There is precedent for AR-fixing tools like the YouTube Aspect Ratio Switcher userscript OP linked or [this terrifically helpful bookmarklet](https://gist.github.com/arpruss/74abc1bc95ae08e543b9b74f15a23b07) [by Alexander Pruss](https://alexanderpruss.blogspot.com/2018/08/adjust-aspect-ratio-of-online-videos.html) which I use to fix video ARs in Firefox. Unlike the userscript, Pruss' bookmarklet lets the user type in any AR they need to apply, so it works universally. A very nice tool.

As someone who watches a lot of old TV/movie and retro video game content on YouTube,. badly produced/uploaded AR videos are extremely common. Having a simple facility to fix them in FreeTube would be ideal and save the user from having to fall back to the real YouTube in a web browser in order to fix it. My .02c.
