### ISSUE TITLE
4 simple feature requests 

### ISSUE THREAD

**Issue by lextra2** [FreeTubeApp/FreeTube#262]
1. add an option, under settings, to pick either a) the build in videoplayer or b) youtubes native videoplayer. since livestreams do use the native (embedded) videoplayer just fine I don't see a reason why this couldn't be an option

2. add an option, under settings, to use a default volume that overwrites the volume the last video had set. I usually use around 20-30% volume. but the build in player does not allow for precise steps adjustment in 10% steps via the mousewheel, like youtubes native player. This could be fixed by an option in the settings.

3. add an icon to the url search bar. sometimes, I don't feel like pressing any keys on my keyboard. So instead I'd like to hit the search magnifying glass icon.

4. perhaps even better than the search icon would be to add "copy and go" to the context menu, when rightclicking on the url search bar.

**Comment by PrestonN** [comment]
Hello.  I will go through each of your suggestions.

1.  This has already been done and will be an option in the next release.  Live streams will also work with the built in player.

2.  Volume will already be set based on the volume from the previous video in the current release.  For an option in the settings menu, see #252

3.  I'm not quite sure what's being asked here.  There's already a search icon next to the search bar.

4.  This can be done.  I will look into making this happen.

**Comment by stemy2** [comment]
Hi, i have 2 other feature requests:

5) Auto-update subscriptions.
6) Close to the tray.

**Comment by PrestonN** [comment]
Hello.  For future reference, please make a new issue for each request that you would like to make.

Tray functionality can be tracked at #59

Updating the subscription list takes a lot of time and resources to do, which is why it is done manually (or after 2 hours).  Invidious has recently added support for [push notifications](https://github.com/omarroth/invidious/issues/469) which will allow FreeTube to update more in real time.  I haven't decided just yet where I will put that on the roadmap but it is planned to implement it eventually.

**Comment by PrestonN** [comment]
Closing as there's too many requests in one issue.  If these are still desired please make new issues for each one.  Some of these are already included as well.
