### ISSUE TITLE
Proxy test failed

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#263]
Hello,

I'd like to use the proxy for API calls, but the test fails every time. What have i to do to make it work ?

**Comment by PrestonN** [comment]
Hey there, this has been brought up recently in our Matrix server, but I'll put everything here for anyone who is not in our chat room.

The site that FreeTube uses for testing the proxy (http://ifconfig.co/) seems to have recently added a CloudFlare proxy to the site.  When doing the test, CloudFlare will notice a Tor connection and interfere to ask for additional confirmation before going to the site.  Since there is no way for FreeTube to go through this confirmation, it considers the test as failed.  Right now the best way to test your connection is to enable the proxy setting and attempt to load something on FreeTube.

I will be switching to some alternative source for testing proxies for the next release.  Hopefully it will be just as informative as the current one but it may be limited to only IP addresses.

**Comment by stemy2** [comment]
I activated it and i still can load a video, so i assume it works.

**Comment by stemy2** [comment]
I thought it worked, but i accidentally didn't validated and actually, it doesn't. Now i have the message «There was an error calling the Invidious API».

**Comment by andretiagogr** [comment]
> There was an error calling the Invidious API

Do you have a local tor proxy running on the background?

If you use Linux with systemd, you just have to install the package `tor` and run `sudo systemctl start tor` to start it.

You can also run `sudo systemctl enable tor` if you want it to automatically start on boot.

**Comment by stemy2** [comment]
It works !
