### ISSUE TITLE
NewPipe compatible backups do not import into NewPipe

### ISSUE THREAD

**Issue by grrrrr** [FreeTubeApp/FreeTube#264]
With FreeTube 0.5.3 Beta, there is an option on the settings section to export  subscriptions to NewPipe format.    I am not sure if this ever worked but as of today it is not working at least for me.

Steps to reproduce

1. open FreeTube
2. Navigate to settings
3. Change export format to newpipe
4. click `Export Subscriptions`
5. Move .json export to android phone.
6. open newpipe
7. go to `subscriptions` section
8. select `import/export`
9. select `Previous export`
10. browse to and select the FreeTube generated newpipe json

On screen an error "Could not import subscription" is displayed.

Android 9 with NewPipe 0.16.1
Debian 9 with FreeTube 0.5.3 Beta

**Comment by PrestonN** [comment]
Hmm.  I'm having trouble replicating the issue with some data that I have on my end.  It's likely that there is a certain channel included in the file that isn't formatted the way that NewPipe is expecting it or the channel itself has been deleted.

If you don't mind, could you please send me your NewPipe export so that I could take a look at it?  You may email it to me privately or through the Matrix server if you don't feel comfortable putting it here.

**Comment by grrrrr** [comment]
Where would I find your email address?    From looking into the exported json,  there appear to be a couple of mismatched brackets and braces, maybe an issue?

**Comment by grrrrr** [comment]
mail sent

**Comment by PrestonN** [comment]
I believe that I've identified the issue with the exports and have pushed out a fix.  Expect the fix to be included in the next release.

**Comment by grrrrr** [comment]
Confirmed working in 0.60.  Thank you
