### ISSUE TITLE
Borderless miniplayer

### ISSUE THREAD

**Issue by anonymous133** [FreeTubeApp/FreeTube#269]
Is is possible to have the Miniplayer be borderless?

I do get a gray frame around the window and a scrollbar if the window is to small.

Solution proposal:
1. No Frame around the Miniplayer / Frame size == Video size
2. Make video adjust its size depending on frame size

Thank you for your outstanding work!

![frame](https://user-images.githubusercontent.com/47555412/59018333-2c562c80-8835-11e9-880b-c44268f730c6.png)

**Comment by PrestonN** [comment]
Making the Mini Player frameless is pretty simple actually.  Adding a flag to the config makes that happen.

The issue is that I'd like to include player controls to the mini player as well.  Right now, they are included in the top menu when you hit `Alt` on your keyboard.  This isn't an issue when using the new player I have, but if we fallback to the current player used in the live release, there won't be any controls for it.  Maybe it's just something I need to play around with.  I'd like to see this happen too but it needs to be done right if it gets included.
