### ISSUE TITLE
Title bar isn't themed in W10 Dark mode

### ISSUE THREAD

**Issue by Millichrome** [FreeTubeApp/FreeTube#278]
I am running FT on W10 (dark mode is enabled in W10 settings). The FT dark mode looks good, but unfortunately it doesn't theme the title bar:

https://i.imgur.com/XTGRMrH.jpg

**Comment by Svallinn** [comment]
There's absolutely no way to make that work in Electron
Read this:
https://github.com/electron/electron/issues/27100#issuecomment-749806315
The only workaround to this would be to make a custom title bar for Windows alone and leave out the default title bar for Linux/macOS
IMO if there's enough noise going around for that feature, it would make sense to implement it
Otherwise, it's better to just leave it as is

**Comment by senolfndk** [comment]
So is the top bar always white?
![SharedScreenshot](https://user-images.githubusercontent.com/52818836/112878816-07e5d700-90d1-11eb-8d71-75f69a7cbfb4.jpg)

**Comment by Svallinn** [comment]
For now, in Windows, yes

**Comment by senolfndk** [comment]
ok

Windows 10 için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 29 Mart 2021 Pazartesi 21:10
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [FreeTubeApp/FreeTube] Title bar isn't themed in W10 Dark mode (#278)


For now, in Windows, yes

**Comment by peepopoggers** [comment]
https://www.npmjs.com/package/custom-electron-titlebar
This may be a workaround for this issue.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> https://www.npmjs.com/package/custom-electron-titlebar This may be a workaround for this issue.
@PrestonN do we really want to implement that workaround?

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
if someone want to look into this https://github.com/signalapp/Signal-Desktop has implemented this

**Comment by Svallinn** [comment]
Just to clarify, Signal doesn't implement custom-electron-titlebar, it's another module.
But it's essentially similar: they make the window frameless for Windows alone, add a custom title bar and then use Electron's `nativeTheme` sub-module to figure out whether the user prefers dark colors or not.

Also, if anything, Signal is more of a PoC supporting us not to do this, people are already complaining...
https://community.signalusers.org/t/title-bar-is-gone-in-windows-desktop-client/45240
https://community.signalusers.org/t/windows-new-dark-light-mode-ignores-system-specific-titlebar-colors/45253

There's really no winning this, since it's basically an OS limitation issue

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
fixed in latest nightly build
