### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'contents')

### ISSUE THREAD

**Issue by christian179717** [FreeTubeApp/FreeTube#2784]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

If I am reloading the abonnements page an error appears:
"TypeError: Cannot read properties of undefined (reading 'contents')".
![grafik](https://user-images.githubusercontent.com/89655752/198840415-74ae6ebe-4750-4562-a4a5-6b491620592b.png)
But after that the videos appear normally.

### Expected Behavior

I don't know, if this intended or not. If not is there any problem with this?

### Issue Labels

API issue

### FreeTube Version

v0.17.1 Beta

### Operating System Version

Linux Mint

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by nowakommunikation** [comment]
I second that. 

The error in different macOS (10.11 - 10.14) reads

"TypeError: Cannot read properties of undefined (reading 'contents')"

when I click on my subscriptions. 

This bug seems to have worsened over the past two weeks or so.
By now, no videos from the subscriptions show up at all. 

Oddly enough, "Trending" still works and also if I search for a subscribed channel and then _directly_ click on a video from the search results. (But I think they are not necessarily in the order newest to oldest as in the subscriptions, so that's not a permanent workaround.)
IF I click on the channel logo from that search, the videos are gone again.

More in bug #2796.

I have tried older versions also and both the Local and Invidious API.

**Comment by absidue** [comment]
This should be fixed in 0.18.0 for the local API. There might still be issue with no videos for the Invidious API, as that requires fixes on the Invidious servers that you are using, not on the FreeTube side.

Please let us know if it's fixed for you so we can close this issue.
