### ISSUE TITLE
Freetube Does not run/Freetube crashes

### ISSUE THREAD

**Issue by crazy-taco-mk2** [FreeTubeApp/FreeTube#2824]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for open and closed issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.

### Describe the bug

I open Freetube, and it crashes/fails to run. When run via command line, I get output (see below)
In order to solve the issue, I've installed the latest version. Then I tried to run the portable version. But the issue still persists.

-Thanks

### Expected Behavior

I expected Freetube to open/run.

### Issue Labels

causes crash

### FreeTube Version

v0.18.0

### Operating System Version

Windows 10

### Installation Method

.exe

### Primary API used

Invidious API

### Last Known Working FreeTube Version (If Any)

0.18.0

### Additional Information

C:\Program Files\FreeTube>
(node:16748) UnhandledPromiseRejectionWarning: Error: 16% of the data file is corrupt, more than given corruptAlertThreshold (10%). Cautiously refusing to start NeDB to prevent dataloss.
    at o.<anonymous> (C:\Program Files\FreeTube\resources\app.asar\dist\main.js:2:38210)
    at o.emit (node:events:527:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
(Use `freetube --trace-warnings ...` to show where the warning was created)
(node:16748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Error: 16% of the data file is corrupt, more than given corruptAlertThreshold (10%). Cautiously refusing to start NeDB to prevent dataloss.
    at o.<anonymous> (C:\Program Files\FreeTube\resources\app.asar\dist\main.js:2:38210)
    at o.emit (node:events:527:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  corruptionRate: 0.16666666666666666,
  corruptItems: 1,
  dataLength: 6
}

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Emmanuel-Million** [comment]
Started working for me after deleting Electron and freetube folders in .config and reinstalling

**Comment by mittermichal** [comment]
for me deleting `.config/FreeTube/settings.db` fixed the issue

**Comment by mittermichal** [comment]
this was the the setting file that caused crashed[settings.zip](https://github.com/FreeTubeApp/FreeTube/files/10470551/settings.zip)
there are 0 bytes at the end

**Comment by je-vv** [comment]
Hello !

I'm experiencing this frequently.  Originally I was removing the whole `~/.config/Freetube`, and went to add the subscriptions one by one...  Is there any effort going on trying to identify why the settings corruption?  BTW, I'm not even changing the default settings, and it still gets corrupted at some point...

**Comment by mittermichal** [comment]
> Hello !
> 
> I'm experiencing this frequently. Originally I was removing the whole `~/.config/Freetube`, and went to add the subscriptions one by one... Is there any effort going on trying to identify why the settings corruption? BTW, I'm not even changing the default settings, and it still gets corrupted at some point...

try cleaning up the settings.db file manually in text editor

**Comment by je-vv** [comment]
Yup, now I do that, and before, I was removing the whole `.config/Freetube dir`.   I'm wondering how about the seetings file corruption, since by making any change, it's weird to see it getting corrupt, but nothing else in the system, other than Freetube, suffers something like it.  Not sure if there's any sort of investigation about it.

**Comment by je-vv** [comment]
The work around is there, but it doesn't mean the issue underneath is understood.  I mean, why on earth the settings get corrupted on the first place, if there's no touching of the settings at all?

What I ended up doing is whenever calling freetube, I do it  this way:
```
rm .config/FreeTube/settings.db && freetube [...]
```

This inhibits me to have any custom setting at all BTW, so it's not a great work around

**Comment by je-vv** [comment]
has anyone found the root cause, rather than applying the workaround?

**Comment by Zakanuva** [comment]
I'm also having this issue where Freetube just won't run:

I'm running Manjaro Linux x86_64, and I had just updated to Kernel 6.4.2-3; Freetube was working just fine before the kernel update, but now it won't even run. When trying to run it via the console, I got this error:
**/usr/lib/electron20/electron: error while loading shared libraries: libicui18n.so.72: cannot open shared object file: No such file or directory**

This isn't the only issue I've had since restarting after the kernel update: the GUI package manager keeps saying that there are packages that need to be updated, but when I try to do so, it _says_ **"Transaction successfully finished."** but nothing else has changed and the packages still say they need to be updated; every other program I've tried running seems to work just fine, so I don't know if any of these issues are a problem with the kernel or something else...

Is there a way to fix any of  this?
![Freetube bug report](https://github.com/FreeTubeApp/FreeTube/assets/139180503/89b5c759-d2d7-4baf-92c8-3c092cc7ac24)

**Comment by je-vv** [comment]
@Zakanuva, it seems you need wait for several things to upgrade with the recent, or rebuild some GUI stuff, including electron.  Your issue with icu, most probably is due to an update to icu, which on Arch/Artix it's 7.3.0, which provides sonames version 73 and 73.2, and not 72...  The issue you had with your upgrade, is not related with freetube at all, perhaps commenting about the icu problems on a Manjaro forum might get you in the right direction.  Some times big upgrades are not made available all at once, and it takes a couple of days for everything to get available, but I don't even use Manjaro, so the best it to ask Manjaro guys, and hopefully maintainers about the icu issues.

**Comment by Zakanuva** [comment]
> @Zakanuva, it seems you need wait for several things to upgrade with the recent icu upgrade, or rebuild some GUI stuff, including electron. Your issue with icu, most probably is due to an update to icu, which on Arch/Artix it's 7.3.0, which provides sonames version 73 and 73.2, and not 72... The issue you had with your upgrade, is not related with freetube at all, perhaps commenting about the icu problems on a Manjaro forum might get you in the right direction. Some times big upgrades are not made available all at once, and it takes a couple of days for everything to get available, but I don't even use Manjaro, so the best it to ask Manjaro guys, and hopefully maintainers about the icu issues.

The other problem I was having was fixed by updating via the Terminal: the GUI Package Manager now recognizes everything's updated and is no longer pestering me about it. However, that update didn't affect Freetube, because I'm still getting the same error message...

When I searched the Package Manager for "icu", the version it says is installed is v73.2-1, and it's listed as part of the "Official Repositories (core)"; there _is_ a listing for an "icu72-bin" from the AUR, though. Will installing that fix the issue?
![Current icu version](https://github.com/FreeTubeApp/FreeTube/assets/139180503/4b04e9e6-f435-4576-b870-a26f07c0a19f)
![Possible icu72 build?](https://github.com/FreeTubeApp/FreeTube/assets/139180503/11c1c43c-f2ee-448b-a86c-1caf1382a04b)

**Comment by Zakanuva** [comment]
I've installed "icu72-bin", and Freetube now runs without issue.

**Comment by je-vv** [comment]
I still honestly don't understand why developers hadn't bothered to look into this, :(  The WA disables having persistent settings, :(

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This should be resolved by https://github.com/FreeTubeApp/FreeTube/pull/3845
