### ISSUE TITLE
Video not available in country is getting worse

### ISSUE THREAD

**Issue by annadane** [FreeTubeApp/FreeTube#284]
And sometimes different players take forever to load, if you try out multiple ones. Dash sometimes works... but sometimes not. Same for legacy. And generally, across all 3, videos not available in my country will play on some of them, but not others

**Comment by PrestonN** [comment]
There likely won't be a perfect solution to this.  The logic behind the legacy player is different if "Grab Videos Locally" is enabled and will usually have better luck with geo restriction issues.  I would also rather not enable proxies through Invidious as that will greatly increase the server bandwidth. My stance on this is that if the video plays in either the Dash Player or the Legacy Player, then everything is working as intended.

I HIGHLY recommend you use a VPN.  This is the best way to fix geo restriction problems.

**Comment by stemy2** [comment]
For me, the VPN didn't solved anything. The so-called geo-restriction is still random, for videos that i can play without problem on invidious and YT, and sometimes, disappears on videos that were previously «geo-blocked».

**Comment by MystesofEternity** [comment]
I have been playing around with this problem and I think this "Video not available in country" does not necessarily mean exactly that it's not available in country. To begin with there's alot of videos that I can't play right now due to "Video not available in country" yet I can play in youtube.com just fine.

Last week I was playing some of my favorite music videos through Dash player just fine and now I get this "Video not available in country" prompt whenever I try to play it with the Legacy player(since Dash player is down atm)

One interesting observation on my part is the fact that Freetube gives the exact same error message on cases that invidious itself cannot fetch the video because it is unavailable on the country where invidious' servers are located. And thing is, the video isn't even blocked on my country lol

My speculated possibility:
- The legacy player cannot play certain video/file types but gives the wrong error message of "Video not available in country"

Will need to do more testing for the case of the Dash player when next release comes.

**Comment by 0b10** [comment]
Any particular country/video combinations that don't work? I will check it out.

**Comment by avocadoras** [comment]
have you tried appending `&local=true` to the URL (`https://invidio.us/watch?v=Anb5vat35Rs&local=true`)? That seems to solve the issue at least for me in Invidio. There's also an option in Settings where you need to toggle Proxy videos for this to be default. I'm not sure there's a way to do this in FreeTube.

**Comment by MystesofEternity** [comment]
@avocadoras Whoaa many thanks for that! It actually played!
I think the "Play videos locally" option of Freetube actually does this too but I think it's not yet a stable feature which is pretty normal considering the software isn't even in stable version yet.

**Comment by PrestonN** [comment]
Let's see if the next update fixes this issue for everyone.  The next update will include a "Proxy Videos Through Invidious" option which will add the `?local=true` option to video URLs.  This should fix a majority of user's problems with georestriction issues.

**Comment by MystesofEternity** [comment]
Thank you very much for the hard work! I'll support you once I am financially able
