### ISSUE TITLE
Allow injecting JavaScipt code

### ISSUE THREAD

**Issue by T-vK** [FreeTubeApp/FreeTube#288]
It would be nice to be able to inject custom JavaScript code into application. This way users could modify settings that cannot be changed otherwise. For example I could modify how far the arrow keys would rewind/fast-forward, I could automatically hide all videos that I have watched until the end or I could customize the theme/UI. 

I know that I can open the dev tools to inject my own code, but when I do it this way, it doesn't get saved and thus I constantly have to paste it again.

What do you think? Is this a good idea?

**Comment by PrestonN** [comment]
I believe that it would be better to explicitly request the features that are asked here instead, one of which has been requested recently (hiding watched videos in your subscription feed).

Also, if you have code that you're injecting into the app, you should make a pull request so that it can be added for everyone :)

**Comment by T-vK** [comment]
Yeah, but the features that I want may not be wanted by other people. Making a PR requires way more effort than writing a script that meets `your` need because you are required to meet certain standards. For example if I were to add an auto-download feature, I couldn't just make it download everything into my movies folder, I would have to make it configurable and therefore I have to add a setting to the settings page etc......... and then I'd have to wait a month or however long it takes until the next release before I can update FreeTube on my machines because I don't want to deal with downloading software and especially updates manually.
I would however consider making a PR for the script injection feature, if it is welcome.

**Comment by PrestonN** [comment]
I believe that a lot of the requests you're asking for are reasonable and are things I would like to tackle in a future release.  While they could be useful for a typical user, I don't really see a Code Injection feature as useful for the same people.

I understand not wanting to polish up a feature for a PR, but submitting a PR for the code injection would require a similar effort as the injected code would have to be saved in the same way as any other setting would be saved.  I would rather see the effort go towards the feature itself instead of some work around to do the same thing.

I would recommend making new issues for the features you want and I will make sure that they get added to the roadmap.  Demand for features will typically help determine the priority on what gets done next so as long as the features have good support then I will make sure to work on them sooner.

**Comment by T-vK** [comment]
Hmm, I don't think you understand. Yes, the code injection feature would require a similar amount of work as _one_ of the other features, but the effort required can't be compared to, say, 5 or 10 features.
I also think that the script injection feature would make it really quick and easy to create a proof of concept for other new features because you can save the time that would otherwise go into setting up the development environment and the whole fork-clone-add-commit-push process.
I'd also happily share my injected code, but I really don't have the time to make so many polished PRs. And I also just don't have the patience to wait for so long for a new feature when I know that I could write something that fits my needs within a day. Not to mention that if I requested a feature, there is not even a guarantee that it ever gets implemented.
