### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#290]
The app takes forever to load, and if it does, it doesn't load channels.

**Comment by PrestonN** [comment]
FreeTube is based on the same API that is used in Invidious.  That means that we are scraping the data from YouTube's site to get the information that our applications need.  Obtaining data this way will always be slower compared to using an official API and it is harder to optimize because of it.

Regardless, I am always looking for ways to optimize the speed of things when possible.  One suggestion I've had is to cache the subscription list from a previous session and use that on startup instead of waiting for subscriptions to load.  This may help for some users.

Another thing is that the rest of the app will likely be slow if subscriptions are refreshing, even in the background.  I don't force you to wait for subscriptions to finish loading, but it would be a good idea to do that instead of trying to navigate too much as the API calls from subscriptions will take priority over trying to look at a channel for example.

I will go ahead and close the issue, as it isn't very helpful.  I'm always looking for ways to optimize the app and I will be sure to make it clear if I have obtained any significant improvements.
