### ISSUE TITLE
Video no longer starts (thumbnail and play button load)

### ISSUE THREAD

**Issue by JableWable** [FreeTubeApp/FreeTube#291]
Windows 10
Videos no longer play. Thumbnail appears. Media controls often don't load. If they load, Freetube does not respond to clicks.
Streams still play normally.
Invidio.us still works fine.

**Comment by Brn9hrd7** [comment]
I have the same issue on Linux(Manjaro), but it looks like it only affects the Dash-Player, the Legacy player still works.

**Comment by theoriginaljacob** [comment]
Same issue here on Linux Mint. Legacy player works perfect, it's the dash player that spins and spins.

**Comment by PrestonN** [comment]
I will look into this as soon as I can. I'm a bit busy this weekend and likely won't be able to look at it until Monday. Maybe if @omarroth is available (seriously, don't feel like you need to rush to this if you don't have time) he could look into it sooner than I could as it could possibly be on the Invidious end anyways.

I haven't been able to find time to test this issue, so hopefully it isn't too much of a problem. Since everyone has said that the legacy player still works, then the app is at least usable for the time being.  I apologize for the delay but I at least wanted to give an update.

**Comment by JableWable** [comment]
No sweat. For reference, I've had 0.6.0 installed for weeks without incident, and suddenly today this issue popped up.

**Comment by haydenhughes** [comment]
I'm getting the same issue on Arch Linux. Turning debug mode on gives me `["videoUrl is valid"]` in the console when ever trying to load a video using the dash player.

**Comment by PrestonN** [comment]
Quick update. So it seems that the issue has to do with a recent update to Dash.js.

I'll be working on a patch release to fix this issue along with some other issues that have been mentioned. I should be able to work on it throughout the week so expect to see a patch soon.

**Comment by JableWable** [comment]
Thanks PrestonN, really appreciate the work you put in to making invidio.us accessible.

**Comment by PrestonN** [comment]
The fix for this has been pushed into the development branch.  There are a few other fixes that I'd like to make before I release a new build, but I'm hoping to have a patch release sometime this weekend.

Since users are likely to come here looking for information about this issue.  I will keep this open for now and close it once the patch has been released.

**Comment by MystesofEternity** [comment]
Thank you very much for this lovely piece of software that you are making!
I have encountered this issue too in Linux. I haven't tested if the problem exists in my Windows computer just yet but I'll gladly help provide feedback should the issue still exist after the new release

**Comment by selurvedu** [comment]
> The fix for this has been pushed into the development branch. There are a few other fixes that I'd like to make before I release a new build, but I'm hoping to have a patch release sometime this weekend.
> 
> Since users are likely to come here looking for information about this issue. I will keep this open for now and close it once the patch has been released.

@PrestonN, thanks, that fixed the issue, however, there is a similar problem:

1. Open a video.
2. Switch to "Legacy formats".
3. Switch back to "Dash formats".
4. The play button disappears.

Also, there is another unrelated issue: I can't pause the playback on Legacy player using the space bar. The video stops and immediately continues playing.

**Comment by PrestonN** [comment]
This issue has been should now be fixed with the latest 0.6.1 update.  If the issue continues, please re-open this issue.

The new release should also fix the issues that @selurvedu mentioned.

**Comment by selurvedu** [comment]
@PrestonN indeed, both issues are gone. Thank you!

**Comment by MystesofEternity** [comment]
Thank you very much for the new release! Issues have been solved
