### ISSUE TITLE
Icon Redesign Suggestion

### ISSUE THREAD

**Issue by Wever1985** [FreeTubeApp/FreeTube#302]
I redesigned the logo because I don't quite like the current one. Feel free to use however you like.

![logo_freetube_banner](https://user-images.githubusercontent.com/52816917/61176032-e0c43a80-a5b9-11e9-8c93-2ce6541f03c5.png)
![logo_freetube](https://user-images.githubusercontent.com/52816917/61176033-e0c43a80-a5b9-11e9-8170-47d3207f96e9.png)

**Comment by Manueljlin** [comment]
I also have played around with the logo, I hope they like it.
![logos](https://user-images.githubusercontent.com/11275573/61186929-72d84b80-a66b-11e9-8e7d-756fd1e6fbfd.png)

**Comment by PrestonN** [comment]
I appreciate the both of you on taking the time to look at working on the logo.  At this time, I'm pretty content sticking with the logo that we currently have.  While the designs that you both made are interesting, I do not believe they would fit it with the design that the app or website has.  While not exactly matching the guidelines, FreeTube tends to have a more Google/Material Design look to it, and I'd like any potential logo to have a similar style.  The current logo fits those requirements which is why I prefer it.

We can keep the discussion going if you'd like, however I will go ahead and close this so that I can keep track of what still needs to be addressed.
