### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by anonaddict** [FreeTubeApp/FreeTube#3046]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

go to https://youtube.com/playlist?list=PLcyItF5YjT0dYq2E7Oti1pgBsRNq3A3jW or another big playlist (1k+ videos) 

click a video

the video plays as expected but the playlist section of the page doesn't load (even after 10+ minutes despite loading instantly in newpipe or on the youtube website itself) so you cannot select options like shuffle 

### Expected Behavior

it should load within a couple seconds and you should be able to select various options like turning on shuffle even if the videos haven't loaded yet

### Issue Labels

content not loading, usability issue

### FreeTube Version

v0.18.0-nightly-2525

### Operating System Version

Linux host 5.19.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec 15 09:37:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Installation Method

.deb

### Primary API used

Local API

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by ChunkyProgrammer** [comment]
@absidue is this because all the videos get loaded on the watch page but not on the playlist page (i dont remember the logic off the top of my head)

**Comment by absidue** [comment]
@anonaddict Could you please check if you are seeing any errors (red text) in the devtools (CTRL+SHIFT+I -> console tab), as 10 minutes does seem extreme even for slow internet connections.

The entire playlist loads under 10 seconds on my machine and internet connection. So unless you are using dial-up, I'm guessing some error is happening. If it really is just slow to load on your internet connection and not erroring, then we should probably add a 2 minute timeout and then show the videos that have already been fetched and forget about the remaining videos, that way it can still be used even if it's with a limited number of videos in the playlist.

Please check for errors first though, before we implement a timeout system.

In the nightlies on the playlist page, we switched from loading all continuations in the playlist in one go to loading them paginated, so they only get loaded if you scroll down and click load more.
The playlist view on the watch page fetches all pages in the playlist, so that you can watch the entire playlist instead of only being restricted to the first page.

Loading the entire playlist got slightly faster in the nightlies as we also changed it, so that the playlist page passes all the videos it has already fetched to the watch page. So the more times you press load more on the playlist page, the less work the watch page has to do.

**Comment by anonaddict** [comment]
[-1673351899978.log](https://github.com/FreeTubeApp/FreeTube/files/10382448/-1673351899978.log)
[-1673351888566.log](https://github.com/FreeTubeApp/FreeTube/files/10382449/-1673351888566.log)
[-1673351872194.log](https://github.com/FreeTubeApp/FreeTube/files/10382451/-1673351872194.log)
[-1673351850329.log](https://github.com/FreeTubeApp/FreeTube/files/10382452/-1673351850329.log)
[-1673351656279.log](https://github.com/FreeTubeApp/FreeTube/files/10382453/-1673351656279.log)

I wasn't sure which file to upload since it popped up several and would only save them individually with save as

Additional information, I had been using v0.18.0 Beta for several months and have viewed the playlist before with no problems (other than it taking a while to load) however around 4-5 days ago it suddenly started loading the playlist itself (the list of videos) instantly but wouldn't load the playlist box whenever you were watching a video on the playlist and would eventually fall back to the invidious API which seems to be limited to only the 200 most recently added videos on the playlist which can get repetetive for music playlists playing on shuffle

I tried updating to the nightly build but the same issue remained, though it did stop falling back to the invidious api without me changing any settings

Hope this is useful and please let me know if you need anything else from me

**Comment by anonaddict** [comment]
Just for the heck of it I tried leaving it on overnight and it never loaded. I never have issues watching 1080p60 videos so I'm very certain it's not my internet speed

**Comment by anonaddict** [comment]
I went through clicked load more videos to the entire playlist and everything went fine, it loaded every batch of 100 in seconds until it got to 1800/1872 where it just completely refused to load the remaining 72 videos

**Comment by anonaddict** [comment]
> I'm assuming that you are hitting a ratelimit.

I thought freetube was using RSS to fetch videos to avoid rate limiting?

**Comment by absidue** [comment]
RSS is only for subscriptions (see https://github.com/FreeTubeApp/FreeTube/blob/development/static/locales/en-US.yaml#L801-L803)

This playlist is 18 pages long,it wouldn't surprise me if fetching all pages in rapid succession, makes YouTube tell us to slow down a bit.

**Comment by absidue** [comment]
@anonaddict Could you please try the latest nightly and see if this has been fixed in the mean time.

**Comment by anonaddict** [comment]
> @anonaddict Could you please try the latest nightly and see if this has been fixed in the mean time.

It appears to be working now, even with the older build I was using at the time of opening this issue (2525)

I installed 2579 and it works

**Comment by absidue** [comment]
I'll close this then. If it shows up again we can always reopen it.
