### ISSUE TITLE
virustotal

### ISSUE THREAD

**Issue by KonoromiHimaries** [FreeTubeApp/FreeTube#315]
`https://www.virustotal.com/gui/file/81995a2e1eed42dcea1428407a861fe40258a53022496458b84842a4cba4c36d/detection`

**Comment by gkeegan** [comment]
False positives are extremely common. Half the files you can upload will have at least one random antivirus flag it.

If you still don't trust FreeTube's provided executables, it is possible to build it from source.

**Comment by PrestonN** [comment]
As was mentioned, if you have any doubt with the binaries that I provide, you may create a build from source with no differences.  The builds that I make are built straight from master with no alterations made.

Looking more into the virus claim being made in your link, it looks like it might have to do with the Windows executable not being signed.  I try to explain this whenever I make a release, but currently any Windows application needs to be signed by a verified publisher in order to get a pass from some virus protection software.  The process of obtaining this certificate is rather costly and I haven't obtained one because of it.  I hope to obtain a signed certificate for when FreeTube reaches stable status.

You can also look [here](https://github.com/beakerbrowser/beaker/issues/898) for more discussion as other Electron projects have seen a similar message from VirusTotal.
