### ISSUE TITLE
Question: Allow ads but still maintain privacy?

### ISSUE THREAD

**Issue by kcthrn** [FreeTubeApp/FreeTube#319]
I would like to use FreeTube but I still am empathetic to the YouTubers/content creators being paid through ad revenue for putting out content, so my question is this:

Would it be possible to include as an option, to allow ads for certain subscribers while still avoiding being tracked by those advertisements?

**Comment by PrestonN** [comment]
This is a very tricky situation and unfortunately I don't see it happening.

youtube-dl provides a bit of information which would be enough to display ads, however the tracking of those ads is how a creator would receive compensation if a user clicked on the ad, which would defeat the purpose of using FreeTube.  Viewing an ad through FreeTube without the tracking would simply not provide the creator any compensation.  Because of this, I don't see a reason to attempt to put YouTube ads in FreeTube.  Just to be thorough, if by some chance I did put YouTube ads into FreeTube, they would be disabled by default and would have to be enabled through settings.

I think a better solution to help content creators get their deserved compensation would be to simply donate to them.  The creator would likely receive more from a donation than they would from watching ads which keeps all parties content.

Another solution is that FreeTube provides the official embedded YouTube player as a last resort fallback in case something goes wrong.  You can enable this at any time when watching a video (or even enable it by default in the settings) which will typically display an ad when used and will give the content creator a small kickback.  I would consider this a simpler solution than to try to put ads in the existing player.

A lot of content creators have also been relying on in-video advertisements for a while now.  I would also recommend using any referral code that they provide if they promote a service that seems interesting to you.  This also typically provides more to the creator than watching ads.

Hopefully this is a good enough answer for you.  These other solutions exist because a lot of content creators these days haven't been able to make enough financially through advertisements alone and it isn't significant enough by itself for them to do the work full-time.  We should encourage other methods of helping creators as they help a lot more than watching an advertisement.

If anyone ever has any ideas on implementing this while not tracking the user and providing compensation to the content creator, please let me know.
