### ISSUE TITLE
so awesome love this

### ISSUE THREAD

**Issue by macducknut** [FreeTubeApp/FreeTube#32]
its a great program love it .. one thing that you can try to implement is external players like vlc and mpv also notifications but the app is great great jobb

**Comment by dimqua** [comment]
Notifications would be great to have, however I'm not sure that it's possible to implement them without a need to log in YouTube account.

**Comment by macducknut** [comment]
ahh understand how about playlist?

**Comment by dimqua** [comment]
Do you mean playing someone's YouTube playlist or making your own local playlist of YouTube videos?

**Comment by macducknut** [comment]
playing someones:)

**Comment by PrestonN** [comment]
Hey there.  Others have mentioned opening the videos into other players but it will probably be looked into later down the line.  There's still a lot of core functionality that needs to be included before I'd like to do extra features like this.

Like @dimqua mentioned, notification support will be tricky.  The way that I'd have to do this would most likely eat up my API key usage checking for new videos constantly.  I'd rather suggest that users should use some sort of RSS reader with notification support if they'd like to see that feature.

Playlist support can be tracked at #11.

I will go ahead and close this issue.  Please make separate issues for each feature so that I can track them better.  Also please be more descriptive with your title next time.

Thank you for your support.  It is very appreciated. :)
