### ISSUE TITLE
[Feature Request]: Allow fetching of youtube channels with RSS rather then the built in way.

### ISSUE THREAD

**Issue by Growebis** [FreeTubeApp/FreeTube#3219]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently, Freetube only fetches normal long videos, and while that's great, the problem is the developer still hasn't implemented a way to fetch live streams and shorts.

### Proposed Solution

While the developer is trying to implement a way for fetching live and short videos. Add an option in the subscription setting that would allow the fetching of RSS for YouTube channels so that way we can get both live streams and shorts videos, but include a warning to the user that the video duration wont be visible.

### Alternatives Considered

Update the way Freetube fetches videos to include shorts and live streams.

### Issue Labels

improvement to existing feature, new feature, new optional setting

**Comment by absidue** [comment]
Fetching feeds from RSS is already a feature inside FreeTube. You'll find the switch to turn it on in the subscription settings.

For more information you may also view the docs page about it: https://docs.freetubeapp.io/usage/subscriptions/#methods-of-generating-your-feed

**Comment by Growebis** [comment]
But this is for the feed only, im talking about implementing it for when you are looking at youtube channels where the api cant fetch shorts and live streams

**Comment by absidue** [comment]
The RSS feeds only contain the latest 15 uploads (not exactly sure on the number but it's definitely very low), together with the feeds missing other information, it would provide a significantly worse experience than properly implementing the live and shorts tabs.

There is currently a pull request open that implements the shorts tab on the channel pages. Just because there hasn't been a release in a while, doesn't mean development isn't happening. We've been putting in a lot of work to move away from unmaintained dependencies that we were using for the local API.

**Comment by Growebis** [comment]
Oh ok, thanks for the info provided. I didnt know RSS had a limitation for fetching uploads.
