### ISSUE TITLE
Implement a better menu

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#327]
Currently the hamburger icon shows/hides the whole left panel. Wouldn't be more intuitive for a user to see here some drop down menu? Something similar to what happens when you click the hamburger icon in the Firefox. I'm asking because when I scroll the channel list a bit down and click this hamburger icon, I expect some kind of menu to pop up, but instead the whole panel disappears.

Here's an example from another YT app I was using till the switch to FreeTube: https://i.imgur.com/Z7dE8iG.jpg -- you just click the hamburger icon, and a menu pops up, it's simple. :)

The current solution (menu + channel list) isn't really designed to deal with many channels. I think it would be better to have two separate entities so they wouldn't conflict with each other. When you have 1000 channels, and you want to watch the 666th channel, you have to scroll a lot down. When you enter the channel, you are unable to call the menu -- you have to scroll all the way up, to get the `Settings` button, and then again scroll down to the 666th channel.

**Comment by PrestonN** [comment]
I'll reiterate what was said earlier.  Currently FreeTube mimics the same layout as YouTube, which includes the menu options with a list of channels below them.  While it doesn't have to be the same, I want to keep a similar layout with YouTube so that it feels familiar to users when they switch over to FreeTube.

Having said that, just because YouTube does something a certain way doesn't automatically mean it's a good idea.  We should be open to going a different path if we feel it is necessary.  This could be one of them.  I will need to play around with designs and figure out what would work the best.

A couple of solutions include:

* Ignoring this as a minor issue as local profiles should solve this problem when using the appropriate profile. (Least amount of work)
* Add the ability to view a channel when editing channels through the profile manager. (Small amount of work)
* Rework the list of subscriptions below the navigation bar to be more grid like to make it quicker to scroll to the desired channel (Medium amount of work)
* Add a brand new location for the channel list that would permanently be shown while browsing through the app.  This may include a redesign of the side bar entirely. (Large amount of work)
* Something else

I encourage any and all discussion on the best steps forward for this problem.  If any changes end up made, I'd like for them to be agreed on by multiple people before moving forward.  I don't want to make design changes that could possibly alienate the user experience versus using YouTube.

**Comment by PrestonN** [comment]
I'll go ahead and close this for now since profiles are implemented and solve the main reason for this request.

If we feel like this is still an issue, one thing we could possibly do is to simply force the side bar to scroll to the top whenever navigation is made through it.  I won't do this right away but if we feel like it'd help then I'm open to it.
