### ISSUE TITLE
[Bug]: there are no subtitles on the external player

### ISSUE THREAD

**Issue by candrapersada** [FreeTubeApp/FreeTube#3279]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

how to enable subtitles on an external player like mpv?

### Expected Behavior

no subtitles in mpv

### Issue Labels

usability issue

### FreeTube Version

0.18.0

### Operating System Version

Windows 10

### Installation Method

Scoop

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by doctorcolossus** [comment]
Hello, was this actually resolved, and how if so? Is it now possible to get subtitles with an external player?

I am trying with `mpv`. I have "enable subtitles by default" in my FreeTube settings, but when `mpv` starts playing, there are no subtitles... And when I press `mpv` keyboard shortcut `j` to toggle subtitles, it only says "Subtitles: no".

**Comment by mrbigmouth502** [comment]
I don't know if this is a regression, but over three years after this was marked "completed", I can't get subtitles in any external player I try, whether I try Haruna, MPV, SMPlayer, or Celluloid. 

I also can't get YouTube videos to load regardless in VLC, but I think that's a separate issue.

Haruna and Celluloid are both using MPV as their backend, while with SMPlayer I was able to try both MPV and MPlayer; and neither had subtitles.

I'm using the FreeTube v0.24.1-nightly-7509 Beta pacman package on EndeavourOS.

**Comment by mrbigmouth502** [comment]
I found a method for enabling YouTube subtitles in mpv from this SuperUser post I was linked earlier: https://superuser.com/questions/1405266/how-to-play-youtube-videos-with-mpv-subtitles

Add the following to your `~/.config/mpv/mpv.conf` file:

```
slang=en,eng,enUS,en-US
sub-auto=fuzzy
ytdl-raw-options=ignore-config=,sub-lang="en,eng,enUS,en-US",write-sub=,write-auto-sub=
```

This also works in Celluloid if you set it to use mpv's configuration, though it doesn't work as smoothly for me as just using mpv directly. 

Unfortunately, I haven't figured out how to get it working in SMPlayer, even after setting `--config=yes` and `disable_player_config=false` in the advanced options. 

I don't see how I could enable it in Haruna either, but I've largely given up on using that program due to some annoyances with its UI that can't be disabled.
