### ISSUE TITLE
To many attempts. Please wait before loading subscriptions again

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#345]
When you have multiple subscription profiles, select one and click the refresh icon on the left panel -- the current subscription list will be refreshed. The same situation will happen when you switch to another subscription profile, which is so far good. But when you select another profile (3rd, and the next ones),  the `To many attempts. Please wait before loading subscriptions again` will be displayed and subscriptions won't be refreshed anymore. You have to close the app and after starting it again you'll get another 2 refreshments.

**Comment by PrestonN** [comment]
When you refresh your subscriptions, FreeTube will refresh all subscriptions from all profiles.  FreeTube stores your subscriptions in a list and references that list when you switch profiles so that it knows which subscriptions to show you.  It is done this way because it would be rather slow for some users if the subscription list was refreshed from scratch every time someone switched profiles.

The lock itself has been there for a while and it is to prevent the user from making too many calls to the Invidious server as we don't want to artificially increase the bandwidth on the site.  This lock is removed after roughly 5 minutes.

**Comment by morfikov** [comment]
>When you refresh your subscriptions, FreeTube will refresh all subscriptions from all profiles. 

Looks like something is bugged here. Sometimes when I switch to a subscription profile, it shows me in the subscription tab one or two channels from other profiles, even though the channels aren't shown in the channel list. So that's why I wanted to refresh the current profile subscriptions. So if all the channels are refreshed in one shot, I think this is a different issue.

Also if there's a 5min lock, you could add this info to the message, so users would know how much time to wait.

**Comment by morfikov** [comment]
> Looks like something is bugged here. Sometimes when I switch to a subscription profile, it shows me in the subscription tab one or two channels from other profiles, even though the channels aren't shown in the channel list.

Looks like this was onetime bug, and it haven't occurred again so far. So I think this can be ignored. 

But still the info about 5 min delay between refreshing subscriptions should be included in the message.

**Comment by PrestonN** [comment]
The delay has been removed in the rewrite as YouTube / Invidious has become more aggressive about too many requests.  If this consistently causes problems because of users refreshing too often, then I can add one again.
