### ISSUE TITLE
Scrollbar too narrow

### ISSUE THREAD

**Issue by Tizwoz** [FreeTubeApp/FreeTube#346]
I love this program & have just installed v.7 on Win10 15" laptop (upgrade from 6.1), but the scrollbar is virtually unusable being far too narrow - similar to the other scrollbar issues, but perhaps slightly different?  Anyway, I thought I'd mention it for your review.  Thank you for this software - keep up the excellent work!

**Comment by PrestonN** [comment]
I feel like the scrollbar is fine size wise.  In the rewrite it will highlight when it can be grabbed so that should be easier to tell when it can be used.  If this is still an issue then we can discuss making it slightly bigger.

**Comment by gripfastistech** [comment]
@PrestonN I'd love to see an option to increase the scrollbar per factor (x2, x3) or by percentage (200%, 400%) for touch input devices. ATM, while using _easystroke_, its nearly impossible to use scrolling because the scroll bar on tablet devices, even with hiDPI workarounds is only a few pixels wide. I can't use my finger and must use the high precision stylus (which is cumbersome). I admit my use case is very niche. However, you can see the size of the scroll bar versus the end of my finger in this image below.

![20210412_095111](https://user-images.githubusercontent.com/53624322/114432023-0c9c9780-9b75-11eb-9d8b-87091c72a96a.jpg)
