### ISSUE TITLE
The Debug Mode doesn't work

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#349]
It looks like the Debug Mode doesn't work. When I switch the appropriate option on, save the settings and restart the app from a terminal, no additional messages are printed to the console -- it's the same behavior like in the case the option was turned off.

**Comment by PrestonN** [comment]
It sounds like you're expecting more messages to come from the terminal.  The debug mode option will actually display more information inside of the Chrome Dev Tools console.  This console can be found by going to View->Toggle Developers Tools in the top bar after hitting `Alt` on your keyboard.

Since this seems to be the case, I will close this issue.  If you think this was an incorrect assumption, feel free to re-open.

**Comment by morfikov** [comment]
Oh, this console. Thanks for the clarification.
