### ISSUE TITLE
Use local youtube-dl instance

### ISSUE THREAD

**Issue by Larivact** [FreeTubeApp/FreeTube#35]
Relying on a youtube-dl-api-server is bad for privacy, makes the app depend on an unnecessary server and only lets the user watch videos which are not restricted in the country in which the server is located (issue #34). While using  a local youtube-dl instance would add a dependency, it would solve all of these problems.

```
/*
 * Detect youtube-dl by trying to run it.
 * @param {function} error - Function called on error with message.
 * @param {function} success - Function called on success with youtube-dl version.
 *
 * @return {Void}
 */
function detectYoutubeDl(error, success){
  const { spawn } = require( 'child_process' );
  const cmd = spawn( 'false', [ '--version' ] );
  let output = '';
  let notInPath = false;
  cmd.on('error', err => {
    notInPath = true;
  });
  cmd.stdout.on( 'data', data => {
    output += data.toString();
  });
  cmd.on( 'close', code => {
    if (notInPath){
      error('youtube-dl not in PATH')
    } else if (code != 0){
      error(`youtube-dl exited with non-zero exit code (${code})`)
    } else {
      success(output)
    }
  });
}

detectYoutubeDl(
  message => {
    console.log(`Error: ${message}`)
  },
  version => {
    console.log(`Detected youtube-dl: ${version}`)
  }
);
```

**Comment by PrestonN** [comment]
When I setup that youtube-dl server, I did so in almost a panic because of some outside dependencies being changed which broke the entire application.  I sort of rushed to figure out a solution so that users could continue using the application.

Now that the application is more stable and that there's more breathing room to work on things, I would love to do this.  You're right that having the server is not needed and it would make more sense to run youtube-dl locally.  It looks like you already have a start on the process.  If you would like to take the task you're more than welcome to.  If not, I can get working on this later today.

Thanks for all of your help!

**Comment by PrestonN** [comment]
I've implemented this in my latest commit and it will be included in the next update.
