### ISSUE TITLE
DASH player is broken

### ISSUE THREAD

**Issue by cyberchief1984** [FreeTubeApp/FreeTube#356]
No matter which video I play, it won't play in the DASH player. It always switches to the legacy one.

**Comment by PrestonN** [comment]
The DASH player seems to work on my end, which tells me it's a more unique issue.  What Invidious instance do you use?  Could you try switching to a different instance?

If that doesn't work, could you show me what it says in the Dev console?  You can open this by hitting `Alt` on your keyboard and going to Tools->Toggle Developer Tools

**Comment by Xulinaah** [comment]
Have this issue too. Am I  missing out on anything? I don't mind that it reverts to other format. At least it works. What Invideous instance do I use? No idea. Don't even know what this means. I am still using the previous version of FT btw since I never got latest version to work.

**Comment by pirate486743186** [comment]
i have this problem too. Actually, some videos are broken with the dash player.

for example:
https://youtube.com/watch?v=LWrztDg2BGI

When that happens, the app permanently switches to the legacy player at max resolution.

This wastes too much bandwidth. It first ignores the settings and goes to maximum format. And if you go somewhere else, it keeps downloading the video. I have to close down the app to make it stop. I'm not using the app because of this.

i don't see where's "tools".
