### ISSUE TITLE
Lead developer received big donations and is inactive

### ISSUE THREAD

**Issue by maboroshin** [FreeTubeApp/FreeTube#3589]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

https://github.com/PrestonN : As lead developer, PrestonN is inactive for about 6 months in the first half of 2023. Since he has released the latest version, now the latest version 0.1.8 has a release date of November 2022.

On the other hand, PrestonN is getting excessive donations. Open https://liberapay.com/FreeTube/ for showing donations. A graph of donations is shown at the bottom. Currently, PrestonN gets $45 per week in donations. In 2022, it exceeded $40 per week. This is about 5 times the $8.50 he states as a necessary expense. In other words, he has already received the necessary expenses for 5 years. And, Donations via cryptocurrency are *undisclosed*.
![image](https://github.com/FreeTubeApp/FreeTube/assets/41102508/ae1bf688-7957-48cd-9086-bf91ca3161a6)

> In an effort to be transparent, I want to make it very clear that donations are not necessary in any way with FreeTube. ... have no need to make money off of the project. ... Progress speed will not increase or decrease because of donations. Only donate if you really want to.

PrestonN stated it this way in Liberapay. We need to ask ourselves. Would you need to donate to an inactive developer? Or would you like to make a gratuitous contribution on behalf of a developer who receives donations for inactivity?

### Proposed Solution

* PrestonN needs to release at least the latest version. This would be the minimum activity expected by the donor.
* And, Use excess donations to improve the user experience. For example, you can charge for other paid services.

### Alternatives Considered

* Suspension of donations for 5 years. Due to excessive donations, donations are currently not required.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Allot of devs already responded to your Weblate issues and we still stand by the previously made arguments.

I can understand that its annoying to deal with people that mistranslate in your language but continuously spamming closed issues and now creating one isnt going to help you solve the problem.

This kind of behavior isn't appreciated as responding to this takes allot (dev)time and energy away on our end.

The only thing i can do for you is to discuss this issue once again in our dev team. This isn't a promise that we will get back to you but if we do it will be in one of your previously created issues.

Furthermore, the actions i will take against this behavior is locking your issues because of the reason stated earlier.

If u do continue your behavior, we will ban u from the FT repo and i suggest u find another project to contribute to.
