### ISSUE TITLE
Can't Delete Exta Profiles

### ISSUE THREAD

**Issue by fjrider** [FreeTubeApp/FreeTube#376]
I had a glitch or human error where I ended up with 5 profiles for "News" videos.  When I try to delete the extra profiles it tells me that it is my default profile (which it is not).  I should have mentioned this glitch was in FeeTube 0.7.0 on Linux Mint 19.2

**Comment by dCo3lh0** [comment]
In my case i have 7 profiles because i follow alot of channels, after 7 custom profiles, it cant identify more than that in the list in top right, i bypass using a bug which is going to settings > manage subscriptions > profile that i want > update profile... than it selects my profile and i can watch this profile, another thing that would be good is an update subscriptions by profiles instead of all channels at once each time its updated, and a category of non-assigned channels to profile yet, it confuses me to look into a thousand list subscriptions and know the name of a channel is already assigned to a profile mixed with others and know which category it belongs to...

**Comment by PrestonN** [comment]
@fjrider I'm assuming you have tried this, but have you tried setting your default profile to several other profiles to see if doing so allows you to delete the one you want?  If all else fails, you should be able to manually update the settings file to remove the default profile and then then remove it through the app.  You can look at #151 for the appropriate location for your OS.  You will want to look for the line that shows the default profile value.  You should be okay to delete this line but replacing the value with a different profile would probably be better.  If this doesn't work then we can troubleshoot further.

@dCo3lh0 please make a new issue next time as your problem is unrelated to the issue mentioned by OP.  It is much harder to keep track of problems when comments like this are made.

Regardless, have you tried scrolling down?  The physical size of the profile list drop down allows for only 7 profiles, but you can scroll down to view the rest of the profiles that you have created.

Also refreshing only subscriptions from the selected profile is possible, but a lot trickier.  I'll have to see what I can do about it but it might be a while as right now FreeTube relies on a master list of all subscriptions and filters out those from the selected profile for viewing.  Refreshing would have to be separate from this list in order for it the work in the requested way.

**Comment by fjrider** [comment]
@PrestonN thank you.  I just went to #151 and deleted those files and started over.  Seems to be fine now.  I messed around trying to assign different profiles as default and delete them but I was having trouble.  Great app!
