### ISSUE TITLE
High CPU usage when movie ends

### ISSUE THREAD

**Issue by morfikov** [FreeTubeApp/FreeTube#379]
When I play a movie (usually 480p, Dash Player), freetube consumes around 15% (CPU0) and 25% (CPU1). When I stop the vid, the CPU usage drops <1%. For some reason when the movie goes to the end (around 30s from the end of the vid has to be played), the CPU usage increases to 27% (CPU0) and 35% (CPU1). Sometimes the values are even higher ~50%. I noticed that the player actually does some job -- I see the preloader but nothing happens. And it stays this way forever. The same thing is when I drag the player's scrollbar -- it also hangs in such state and waits for manual pressing of the play button.

The "play next video" option is turned off. When I turn this on, I get some info that in 5s the next vid will be played, and I don't experience the issue described above. But I don't really want this feature to be on.

**Comment by PrestonN** [comment]
When I saw this I figured it would maybe be a DASH player specific issue.  Trying the legacy player (which is simply a generic video player bundled with Chromium) CPU spikes a bit as well.  While it's close it's not as high as the DASH player.  If this is happening with the legacy player, then there likely isn't much that I can do to fix this.

Admittedly this might be simply because FreeTube is based on Electron.  It's likely a native solution wouldn't have as high of CPU usage.  It's something that I'd like to look at doing but a rewrite of that scale is simply too large for now and would be a huge set back on any progress.  I'd like to "finish" the Electron app before considering a native app.

**Comment by morfikov** [comment]
The legacy player works well, but there's only 360/720p. But when I play the vid in 360p, I have ~7-8% of CPU0/CPU1, but when the video ends, there's no preloader, and the CPU drops to almost 0%. Also, there's no preloader when I scroll the vid. The CPU jumps to 12-15% for a second or two, and it back to those 7% like it was before. So maybe something is wrong with the preloader?

**Comment by evpne** [comment]
"FreeTube uses the Invidious API to grab and serve videos." - I think thats the problem because when i watch a video over Invidio.us my CPU usage is getting really high.
![Screenshot from 2019-09-14 15-28-12](https://user-images.githubusercontent.com/51292471/64908839-1e058f80-d705-11e9-9890-7c506215464e.png)

**Comment by PrestonN** [comment]
This is hopefully fixed in the rewrite, if this is still a problem then we can reopen.
