### ISSUE TITLE
Videos in subscriptions list are not sorted correctly

### ISSUE THREAD

**Issue by Asgaros** [FreeTubeApp/FreeTube#380]
In the latest version 0.7.0 the videos inside of the subscriptions list are not sorted correctly by date. In the attached example picture you can see that a video from July, 15th is appearing before a video from August, 3rd.

The sorting in the list seems to get messed up more as more you scroll down. For example a lot of videos from a specific channel appear grouped (as highlighted in blue) in the list. But in reality videos from other channels should appear between those videos. The sorting seems to stop working around the "1 month ago" time-period starts.

![sorting](https://user-images.githubusercontent.com/12525671/64851391-95f58c00-d617-11e9-9c4a-50e389b4f4ff.PNG)

**Comment by PrestonN** [comment]
When grabbing the latest videos from YouTube, YouTube doesn't provide the exact date that the video was released.  We only have the rough estimations (an hour ago, one month ago, etc.) to go by while sorting so you may see some small rearrangements like this.

The only real fix for this would be to go to each individual video page to get the exact release date, which would be very slow and impractical to do.  Because of this the behavior will likely never change from it's current form without any major changes from YouTube that allows this.
