### ISSUE TITLE
Question concerning YouTube player + VPN

### ISSUE THREAD

**Issue by hunguscrungus** [FreeTubeApp/FreeTube#390]
Hello, first ask here. I have a question to ask.

Will using the YouTube player to watch a video mean a downgrade in privacy in contrast to using Dash or Legacy? Would not using a VPN (either with YT player or not) undermine the entire purpose of the application and leak data or is there still some level of protection without a VPN? I do use one, however I'm wondering about the ramifications of not using one while watching. Thanks.

**Comment by PrestonN** [comment]
Using the YouTube player versus DASH / Legacy will definitely be less private.  YouTube can potentially track your watching habits this way if all of your watching is done using their player.  Even though we're not directly on YouTube, their player will typically still show recommendations to you, which can show that some tracking is still possible.

Using DASH / Legacy removes their player, which removes most of their tracking.  You're still making requests to YouTube, so we don't know 100% what they do with that information.  It's always possible that even without their player that some sort of tracking is done, that's why a VPN is recommended.  It removes that last bit of tracking that YouTube might be doing to identify you as an individual.
