### ISSUE TITLE
Trending + "Most Popular" feeds - how generated? 

### ISSUE THREAD

**Issue by aproposnix** [FreeTubeApp/FreeTube#394]
I've noticed lately that the trending and the popular feeds are not the same as when using a browser. This was not the same behaviour that I noticed in the past. 

If I go to youtube (with a clean browser - no cookies, never visited YT) I see that the trending feed on youtube is the "Most Popular" on Feedtube (though slightly different). Popular is also different than what I see on FT. 

I have also noticed that these feeds change based on which invidious server (IS) I select (I figured this out because I started getting French feeds after selecting a french IS).  Based on this, I assume that Google is modifying the results based on the IS. Is this correct? Even if I set **my location in settings to the US** I still see feeds reflecting the region of the IS. 

I'm assuming that the users of the IS are being profiled as one user by Google. Is this correct? For example, I'm seeing very niche videos (such as" hatedone" - a channel I would expect many invidious users to watch) which I would never see with  clean browser. 

Can anyone help me to understand how this works? Is there anyway to get the "generic" feeds that I see in a clean browser? 

Current version used: 0.7.0 Beta

**Comment by PrestonN** [comment]
Your assumptions are correct.  The Trending tab will use YouTube's trending section for the feed.  This feed will be determined by the Invidious servers IP address (https://invidio.us is based in the US, which is why it is the default feed).  Changing the country in the FreeTube settings will have Invidious attempt to use a proxy in that country to return that country's trending feed.  If Invidious doesn't have a proxy available for that country, it will default to the Invidious server's IP.

The Most Popular section of FreeTube heavily depends on which Invidious instance you're using.  Most Popular will mirror the "Popular" section from that instance, which is a feed of the most recent videos from the top subscribed channels in the feed.  If enough users subscribe to a channel with their Invidious account, then that channel will appear in the Popular section.  Your subscribed channels in FreeTube do not contribute to the subscribed channels within Invidious.

To be thorough, Invidious also has a "Top" section.  This section simply shows the most watched videos in that instance, not taking subscriber count into consideration.  Videos watched within FreeTube WILL contribute to this metric.  I never properly asked the community, but I'm open to using either section as the "Most Popular" tab within FreeTube.  I could easily add a new tab including both if that was desirable.  Open to suggestions on this.

Before the switch to the Invidious API, it was actually possible to obtain a generic trending feed through the YouTube API.  We talked about this a bit during the API switch, but it doesn't seem to be possible to generate a similar list without YouTube's API.  I remember making it mimic SkyTube's Most Popular page at the time.  I don't see a similar list being included any time soon.

I believe this answers your question, so I will close this issue.
