### ISSUE TITLE
Support of one of the new amazing super powreful video media players based on mpv GUI 

### ISSUE THREAD

**Issue by trimechee** [FreeTubeApp/FreeTube#3950]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hello, thank you very much for this amazing awesome software ! 🥇 💯 

Please i have request :  add support of one of mpv gui based players because mpv is very powerful and wonderful and media players based on mpv player has awesome geatures and enhancements....thank you so much ! 

https://github.com/mpvnet-player/mpv.net

https://github.com/coslyk/moonplayer

https://github.com/vzhd1701/gridplayer

https://github.com/thisismy-github/pyplayer

https://github.com/zaps166/QMPlay2

https://github.com/422658476/MPV-EASY-Player

https://mpc-qt.github.io/

https://github.com/smplayer-dev/smplayer

https://tsl0922.github.io/ImPlay/
https://github.com/natural-harmonia-gropius/mpv-config
https://github.com/tomasklaen/uosc
https://github.com/christoph-heinrich/mpv-quality-menu

https://github.com/mpvnet-player/mpv.net-experimental

### Proposed Solution

Use one of the new awesome alernative media players base on mpv

### Alternatives Considered

Use one of the new amazing externel super powerful players based on mpv gui

### Issue Labels

support for external software

**Comment by absidue** [comment]
FreeTube already supports opening videos in external players, you can select one from the dropdown in the external player setting section.

**Comment by trimechee** [comment]
Great ! Thank you Mr @absidue :)

I made this request because i read this : "Right now, all external players have to be hard coded into Freetube to be supported. This is fine, but there are users that want to use lesser known players with Freetube that might not be worth the effort of hard coding."


so , media players, to be compatible with our beloved FreeTube, they have to be hard coded into FreeTube ? 

https://github.com/FreeTubeApp/FreeTube/issues/1975

**Comment by absidue** [comment]
Yes, as FreeTube needs to know how to pass information to players (we don't just try to send the video URL but also things like the timestamp you were at in the video, when you clicked the open in external player button).

We would have to provide a pretty advanced set of configuration options, which will require the user to know exactly what features the external player supports and how to pass command line flags to it. For advanced users that might alright, but for most users that is probably too advanced.

For the moment having support for each player added manually means that it can be verified working, instead of having to deal with loads of bug reports from people that can't get the generic option working, because it's too complicated for them.

Also as I am not a man, Ms is more appropriate, that's why I have the "she/her" pronouns on my GitHub profile.

**Comment by trimechee** [comment]
Ohh I'm sorry Ms Absidue ! Now I understand better, thank you very much for these very interesting explanations :) 💯

**Comment by Cyanide-1** [comment]
SMPlayer is already supported. As for the others, support adding extra support for these players if possible, MPV is fine by itself but i feel like the GUI is unintuitive to use, and these other media players tend to do the job better in terms of intuitiveness, so adding support for these would be good to do and shouldnt be too hard to do since it just uses MPV in the backend so i assume you could support these players the same way MPV is supported.

I may recommend adding Haruna and Celluloid to the list though, as these are also very common MPV-based media players.

https://invent.kde.org/multimedia/haruna
https://github.com/celluloid-player/celluloid
