### ISSUE TITLE
[Feature Request]: "Home Page"

### ISSUE THREAD

**Issue by ericc-dream** [FreeTubeApp/FreeTube#4083]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hi 
I'm a long YouTube user. I have all the pop-up blocker, ad-blocker needed in place and working nicely, and I never see an advertising (beside those "embedded" in the video by the youtuber himself) .
However, I'm still concerned by YouTube tracking me and all my viewing habit.
So I tried several application to have a little more privacy, and all have the same problem which make me going back to Youtube . 

I have a rather limited number of subscriptions. I works more by "Subject of interest" or "Categories" 
When I open "YouTube", I arrive in my "Home page", and the videos there are a selection of subject interesting to me, new or old, and very few are coming from my subscription (may be 5% or less). Some are channel that I'm watching since a long time but never feel the need to subscribe.
This allow me to discover some new channels, sometime new topics I'd never have explored on my own.

This is the weak point of FreeTube, NewPipe and other "YouTube client", as they works by "subscription", the user is locked in a kind of bubble ... his bubble, but still locked 

*And don't talk to me about "Trending" nor "Most popular" please !

### Proposed Solution

I think that it's somehow related with the following issue [ Implement YouTube categories #1582 ](https://github.com/FreeTubeApp/FreeTube/issues/1582). Even if not fully the same

I don't want (all) the same categories as in YouTube. But I would like to build **my personalized home page** with videos related to a list of "Subject of Interest" , that I can build myself ... or to choose amongst a predefined list if it's more simple for you. 

### Alternatives Considered

nothing come in mind

### Issue Labels

ease of use improvement, visual improvement

**Comment by absidue** [comment]
The big difference between a privacy friendly app like FreeTube vs YouTube, is that YouTube tracks everything, has access to their full catalogue of content and advanced algorithms to recommend stuff, so they van generate a fully customised home page.

FreeTube on the other hand stores all of your subscriptions on your own device and only has your watch history to go off, if you turn it on.  FreeTube doesn't have access to the entire catalogue that YouTube has and also doesn't have any advanced algorithms, so we can only display what YouTube gives us or what is stored on your device (watch history, subscriptions).

So even if we requested the homepage from YouTube, it would just have generic content on it, because YouTube doesn't have enough information to produce a customised one.

What about creating our own one? Well we could display random videos from your watch history, probably not what you want as you've already seen it. What about displaying old videos from channels you are subscribed to? Well again as we don't have that level of access to YouTube, it would require making thousands of requests to YouTube's APIs (clicking load more on the channel pages), to get all videos on all channels you are subscribed to and then picking out a few random videos, from that gigantic list that we spent 10 minutes downloding.

**Comment by ericc-dream** [comment]
Hi 

Thank you for taking the time to reply

I just made a test:
If I'm going to "Trending", and in the search box, I enter "woodworking" by example, it return a list of video (and 1 channel). 
Not sure if the search result is related to the page where I'm in the application
And I can "Fetch more results" 
So from this we can build something ... allowing to "preset" a list of keyword, (may be limit the number to limit the number of request) and build a home page from the results ! 
And the filters can be useful also (to avoid channel and order the results) 

Is it not visible ?

**Comment by absidue** [comment]
The global search is like the global search on youtube, it's not connected to the page your are looking at.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Duplicate of https://github.com/FreeTubeApp/FreeTube/issues/183

**Comment by ericc-dream** [comment]
it's a little bit going too fast to the conclusion by closing it as duplicate of #183 ! 
I read it, and this is absolutely not the same request 
#183 was a request to being able to choose which page appear first when the App start 
I'm proposing to create a completely **new home page** based on some "search keyword" or "subject of interest" or "categories" (call this as you please)  from the user

**Comment by journeym** [comment]
> only has your watch history to go off, if you turn it on. FreeTube doesn't have access to the entire catalogue that YouTube has and also doesn't have any advanced algorithms, so we can only display what YouTube gives us or what is stored on your device (watch history, subscriptions).

So it's pretty much useless, thanks for clarification
No youtube reccomendations - no youtube
