### ISSUE TITLE
subscription 100 videos

### ISSUE THREAD

**Issue by Joseph65** [FreeTubeApp/FreeTube#410]
why it only loads 100 videos in subscriptions

**Comment by evpne** [comment]
I personally think thats more than enough but it could depend on the amount of subscriber someone have. Since the project is FOSS you can just change it and build for you. [Here are the lines ](https://github.com/FreeTubeApp/FreeTube/blob/development/src/js/subscriptions.js#L219) you should change if you want to build it.

**Comment by ADepic** [comment]
What does freetube achieve by having this limit

**Comment by ThatIsAPseudo** [comment]
This limit could simply be in the settings with a default value of 100, or even within the subscription tab

**Comment by Agych** [comment]
I totally agree, the value should be customizable.

Moreover, it would very cool to have "Load More" button in the bottom, to be able to load more videos manually like on youtube.
