### ISSUE TITLE
Feature: Support for multiple invidius instances.

### ISSUE THREAD

**Issue by hugglesfox** [FreeTubeApp/FreeTube#415]
Due to [rate limiting changes with youtube](https://github.com/omarroth/invidious/issues/811) invidious instances frequently break. It would be nice if freetube could have a list of invidious instances which it will try so that if the video cannot load on one instance, it'll try the next instance in the list and so on before reverting to the legacy player.

**Comment by PrestonN** [comment]
Something like this would definitely be behind a toggle and disabled by default.

Some users likely won't want to connect to other instances for one reason or another or they may not care if FreeTube has to revert to the legacy player.

Besides that it shouldn't be too big of a thing to include.

**Comment by simoniz0r** [comment]
> Some users likely won't want to connect to other instances for one reason or another or they may not care if FreeTube has to revert to the legacy player.

I personally think this needs to be a thing FreeTube does by default. It should have a function that checks the [JSON API that lists Invidious instances](https://instances.invidio.us/instances.json?pretty=1) with a test video ID to find an instance that isn't blocked for use. If the instance that is being used becomes blocked, it should repeat this process and find a new instance.

I think this needs to be a thing that FreeTube does by default because an instance getting blocked/going down can mean that you can't view channels, your subscription feed, search, etc... let alone even watch a video.  Usually when an instance gets blocked, it cannot retrieve any new video data until it gets a new IP, so using a blocked instance makes FreeTube almost useless even if it can get the video data itself through other means.  

I've had to switch instances a half dozen times today alone just to find one that was working which isn't exactly fun times, and not at all obvious to new FreeTube users who aren't familiar with Invidious to begin with.

Also, just an FYI, all of the output formats that Invidious gives through their API are also [available through YouTube without using their API](https://www.youtube.com/get_video_info?video_id=hq6Y-iIrL8g), so I'm not sure why FreeTube defaults to the legacy player when it can't get info from Invidious.

**Comment by PrestonN** [comment]
We can look at this again if we need to, however since the rewrite has a built in API, the reasoning for including this might not be needed any more.  If we want to look at this again, then please reopen.
