### ISSUE TITLE
Button to load all videos in the channel videos / playlist automatically

### ISSUE THREAD

**Issue by Agych** [FreeTubeApp/FreeTube#423]
There is a browser userscript "Youtube - Load more all" that adds a button near "Load More" on youtube, and by pressing on it, all videos are loaded automatically, without having the annoying problem of pressing "Load More"->waiting repetitions.

Would it be possible to add a button with such functionality for channel videos and playlist pages?
For example, it could be done in a way that the button "Fetch more results..." occupies the left half, and the new "load all" button is on the right half.

**Comment by PrestonN** [comment]
This could technically be done, however this could end up using a lot of RAM depending on how big some of the playlists / channels are.

I think a better solution would be to have more results automatically load on scroll, which is planned for a future release.

**Comment by Agych** [comment]
It's the user's choice.
I have a lot of RAM and i would choose to load all with one click of a button, rather than having to wait after every scroll.

**Comment by PrestonN** [comment]
This starts to become a problem when you account for channels that load daily and have thousands of videos.  Doing something like this would be wasteful with the amount of requests a user can make and will greatly increase the amount of rate limiting that would be done.  I'd hate to offer such a feature and everyone that uses it comes back to me because now they can't use the app at all due to rate limiting.

Sorry, I don't think this will be included.
