### ISSUE TITLE
[Feature Request]: Custom Subscription FIlters

### ISSUE THREAD

**Issue by hutonahill** [FreeTubeApp/FreeTube#4306]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I subscribe to several youtube channels that occasionally do podcasts. I listen to their podcasts on my phone with a podcatcher. as such i don't want to see their videos in my feed

### Proposed Solution

let me write custom filters and apply them to the subscription screen. something like:

```python
((channel = "BrandonSanderson" and title.contains("of Intentionally Blank"))==False)
```

You could let the user input a python(or your language of choice) boolean expression somewhere that gets applied to all the videos.

### Alternatives Considered

Don't do anything. This is not a super necessary feature.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
That would either require us to let people run custom JavaScript during filtering or come up with a custom language/syntax like yt-dlp has

Personally we think that kind of use case is out of scope of FreeTube, a better option would be to create a custom build for yourself with your preferences hardcoded in

Much less development and maintenance work for us, as having something like that makes it harder to make changes, because then any code change that touches video lists, could potentially be a breaking change for someone's custom filter

We see it as one of those things that takes a lot of work to implement but with little benefit 

Don't get me wrong it would be a cool feature, but at that point you are better off just writing some code  

Especially as you're asking for python syntax, which means they already have some coding knowledge
