### ISSUE TITLE
0.7.1 requires 4755 on /opt/FreeTube/chrome-sandbox

### ISSUE THREAD

**Issue by windowsrefund** [FreeTubeApp/FreeTube#431]
Am I missing something here? This thing wants to root my box?

Seriously?

**Comment by stemy2** [comment]
Same problem. The exact message is «[25500:1201/225724.053169:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/FreeTube/chrome-sandbox is owned by root and has mode 4755.»
Nothing happens when i launch graphically and this message appears when i launch with the console.

**Comment by d43m0nhLInt3r** [comment]
[Its a known problem](https://github.com/electron/electron/issues/17972) and electron-builder has fixed it in the pre-release version. Since its not stable yet we are forced to wait. So the only workaround is `sudo chmod 4755 /opt/FreeTube/chrome-sandbox`

**Comment by vladimiry** [comment]
> So the only workaround is sudo chmod 4755 /opt/FreeTube/chrome-sandbox

That's not the only workaround, see a few more:
- Run with the program with `--no-sandbox` argument.
- Enable the User Namespace thing `sudo sysctl kernel.unprivileged_userns_clone=1` (system-wide change).

**Comment by PrestonN** [comment]
This should be fixed in the rewrite as we're finally using up to date build tools, which fixes this problem.
