### ISSUE TITLE
[Bug]: DeArrow not replacing unverified titles

### ISSUE THREAD

**Issue by Mr-Bajs** [FreeTubeApp/FreeTube#4320]
It related to this where the issue are discussed but the issue i closed https://github.com/FreeTubeApp/FreeTube/issues/3696#issuecomment-1776247544
I'll create this seperate issue for the particular issue of FreeTube not replaceing youtube original titles with the dearrows user submited titles, for the sake of keeping track of issues.

This comment and screenshots shows how the DeArrow titles doesn't load on FreeTube.
https://github.com/FreeTubeApp/FreeTube/issues/3696#issuecomment-1778512220

### Expected Behavior

Enable DeArrow in Freetube and look for for youtube videos that has user submitted titles and compare it with a browser with dearrow enabled.

### Issue Labels

API issue, feature stopped working

### FreeTube Version

v.0.19.1

### Operating System Version

Linux Mint 21.2

### Installation Method

Flathub

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
As mentioned in the comments below the original one, this is caused by FreeTube only using titles that a second DeArrow submitter upvoted, whereas the DeArrow browser extension shows everything, even if it has no votes.

The solution would be to lower the standards in FreeTube, so that it uses unverified submissions too. I guess the browser extension lowered it's standards since the original FreeTube pull request, because using ones with 1 or more votes was suggested by the DeArrow developer here: https://github.com/FreeTubeApp/FreeTube/pull/3688#discussion_r1235481467

**Comment by ajayyy** [comment]
Sorry the original suggestion was a mistake. Unverified submissions appear as `-1` votes, so still won't be used. I made a PR #4321

**Comment by ajayyy** [comment]
@Mr-Bajs at the moment you are labeled "verified" after receiving at least one vote on any title
