### ISSUE TITLE
[feature request] youtube-dl for fetching subscriptions and search results? (Remove Invidous Dependency Entirely.)

### ISSUE THREAD

**Issue by JustAnotherGithubUser2** [FreeTubeApp/FreeTube#434]
Right now Invidious is having a huge problem where instances are being blocked left and right FreeTube did a huge fix that enabled youtube-dl to be a fallback which works really well and I actually prefer it to using an invidious instance because it's far more reliable.

The big issue though, is if an invidious instance is blocked than you can't get the subscriptions/video searches, even if youtube-dl is working fine. I think this is a big problem, since there have been periods where it felt like every invidious instance was blocked/offline at the same time.

It'd be nice if there would be a way to retrieve the metadata for videos (title, thumbnail, description ect...) using youtube-dl if the invidious instance wasn't properly loading them. This would be very useful since there are plenty of cheap/free ways of changing your system IP if somehow you generate enough traffic to be blocked, but if all invidious instances are blocked/down there's nothing you can do but wait for one to come back up.

**Comment by PhoenixDiscord** [comment]
I agree, Invidious is currently _on fire_ so it's not really a good thing to use unfortunately.

**Comment by PrestonN** [comment]
This is being included in the new rewrite.  There are extra modules that can be used while still not using any official API.  These modules work in a similar way to youtube-dl / Invidious however they are not officially involved in those projects from what I know.  My initial testing shows that they are viable solutions to allowing FreeTube to rely less on an outside server for grabbing information.

Having said that, using Invidious will always be the more seamless way to get the data.  Since it's much easier to update the Invidious server (in the sense that users don't have to do anything to update), it will always be more user friendly to default to using Invidious over a local solution.  If YouTube changes something on their end and breaks the local endpoints, the user will have to download a new version of FreeTube with the updated endpoints in order to use it again.

So far I've found modules for doing the following actions locally:

- Searching (Along with Filters and suggestions)
- Viewing playlists
- Playing videos and getting video info (Which is already implemented in FreeTube)
- Getting latest videos from subscriptions (This one will have to be custom made, however it will grab from the channel's RSS feed)

The following so far will always rely on Invidious as I have not found any suitable replacements (any help would be good)

- Getting Channel information
- Viewing the Trending Page

When everything is finished, the plan is to allow the user to pick which backend they'd prefer along with an option to fallback to the other backend when their preference fails.  I imagine some people don't want a local backend and an easy way to disable it should please the most amount of people.
