### ISSUE TITLE
this video is unavailable 

### ISSUE THREAD

**Issue by BrainlessConsumer** [FreeTubeApp/FreeTube#435]
"this video is unavailable "  - The recent frequency of this error has become irritating.
Is there any way to alleviate this chronic problem and watch a video?

**Comment by hunguscrungus** [comment]
Same here. Happens on every instance, proxy or no proxy. Videos seem to be random, but once is unavailable it stays that way for seemingly forever.

**Comment by hunguscrungus** [comment]
Same here. Happens on every instance, proxy or no proxy. Videos seem to be random, but once is unavailable it stays that way for seemingly forever.

**Comment by torriem** [comment]
I'm getting it for about 25% of the videos in my feed, sometimes more.  If I take the youtube link and use youtube-dl I can download and watch it great, or if I use the Invidio.us link it works in the browser, so it's not a problem with the instance I'm pointing at.  Seems to be worse lately.  Using the latest beta build posted.

**Comment by PrestonN** [comment]
The problem seems to be from a slightly outdated ytdl-core plugin. Looks like they've had a couple of bug fixes since the last release. I'll likely make a new release with the plugin updated which should fix this issue. Like it was mentioned, turning off "Grab videos locally" should fix the problem in the mean time.

**Comment by BrainlessConsumer** [comment]
The new release was much appreciated & resolved the issue; Thanks much.
