### ISSUE TITLE
[Feature Request]: Avoid to buffer segments blocked by sponsorblock

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#4354]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Sponsorblocks are buffered, and it's a problem because when the said segment is being skipped, i have to wait another buffering time because it preffered to buffer a segment that i wouldn't watch anymay.

### Proposed Solution

I'm not a technical person, so i don't know.

### Alternatives Considered

I'm not a technical person, so i don't know.

### Issue Labels

improvement to existing feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Retrieved from IRC

> I don't think any video player gives you that level of control, especially as most sponsor block segments are probably shorter than a segment of video, so it would need to be downloaded anyway if you want the stuff that is before and after the sponsor block segment to play

maybe if we patched shaka itself we could find some way of modifying it's internal segment list, but then we would also need to make sure that it can cope with sections of audio and video allegedly not existing.

Also don't forget that players tend to request multiple segments of audio and video at the same time, if the connection is good enough, so by doing those changes instead of doing one request for segments 1-4, we would have to do one request for segment 1 and a second request for segments 3 and 4, at which point the added overhead probably outweighs any benefit you would get

Based on this i'll go ahead and close this issue.
