### ISSUE TITLE
Always open youtube links in FreeTube

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#44]
Is it possible to open youtube links in FreeTube instead of web browser?

**Comment by PrestonN** [comment]
This is something that I've been wanting to do.  I have a general idea on how to do it but it's going to take a little bit of research on my part to get this working.  The functionality will most likely have to come from a Chrome/Firefox extension to work.

**Comment by dimqua** [comment]
Is it possible to handle them on a system level, at least on Windows or Linux?

**Comment by PrestonN** [comment]
Not that I'm aware of. You can make specific links in a browser accomplish this without a browser extension, but you would still need something to convert YouTube links to these redirect links. I understand that it's not the most ideal, but a browser extension is the most practical solution to this.

**Comment by keijukainen** [comment]
A javascript bookmarklet would accomplish this. However, it would be session based and would require the user to manually activate it. You could publish the bookmarklet as a link on your github readme page. Users could then right click the link and bookmark the code to save it to their toolbar. Anytime they wanted to activate it they could simply click the bookmark on their toolbar. It would be cross-browser compatible so you wouldn't need a separate chrome and firefox extension. Since it's session based the code would automatically stop once they closed the tab or browser or navigated to a different url. You'd have to implement a global variable and set an interval to constantly check for new links since youtube content can change without reloading the page. Firefox users would have to add one new pref to about:config in order to show protocol handler popup.

overview
1. test domain of page loaded in focused tab. if not youtube.com then exit.
2. set global variable to keep track of total video/playlist links
3. create an array of all links on page
4. loop through array and compare each url to a regex pattern to determine which links point to video/playlist.
5. if match is found then prepend href with a new 'freetube:' protocol, stop propagation of click event and update total.
6. set interval of 3 seconds and call the same function at each interval to count total video links. compare current total to global variable total. if number is different then process urls again to add freetube protocol.


Example:
Go to about:config in firefox.
Type network.protocol into filter box.
Right click and create new boolean pref using name below.

network.protocol-handler.expose.freetube

Set pref to false.
Go to a youtube video page (https://www.youtube.com/watch?v=VPI9E-wNK8s)
Paste the code below into your address bar.
You'll have to retype javascript: at the beginning of url. Firefox automatically removes it when you paste a javascript url.
Press enter to apply the url changes.
Click any video url and you should see a protocol handler popup.
Choose location of freetube and check the 'remember my choice' box.
Tested on linux using ff 60.0.2

`
javascript:
var aTags = document.documentElement.getElementsByTagName('a');
for (let i = 0; i < aTags.length; ++i) {
  if (aTags[i].href.search(/\?v=[\w\-]{11}/) > -1 &&
      aTags[i].href.substr(0,9) != 'freetube:') {
    aTags[i].setAttribute('onclick', 'event.stopPropagation();');
    aTags[i].setAttribute('href', 'freetube:' + aTags[i].href);
  }
}
alert(aTags.length + ' links processed');
`

**Comment by PrestonN** [comment]
@keijukainen you might be interested in taking a look at [freetube-redirect](https://github.com/FreeTubeApp/freetube-redirect).  It's not as robust as your solution but it should be a much more user friendly solution.  I would love to have your help towards improving it if you are willing to do so.

Setting up the `freetube:` protocol is actually done automatically if you install the .deb or .exe of FreeTube.  This might work for other installations but I haven't been able to test them out.  This should make it much easier as a user to get this up and running.

Let's continue this conversation over at the [freetube-redirect](https://github.com/FreeTubeApp/freetube-redirect) repository.

**Comment by PrincessMiki** [comment]
> @keijukainen you might be interested in taking a look at [freetube-redirect](https://github.com/FreeTubeApp/freetube-redirect). It's not as robust as your solution but it should be a much more user friendly solution. I would love to have your help towards improving it if you are willing to do so.
> 
> Setting up the `freetube:` protocol is actually done automatically if you install the .deb or .exe of FreeTube. This might work for other installations but I haven't been able to test them out. This should make it much easier as a user to get this up and running.
> 
> Let's continue this conversation over at the [freetube-redirect](https://github.com/FreeTubeApp/freetube-redirect) repository.

I installed freetube from .deb and see no 'freetube protocol' option
