### ISSUE TITLE
AppImage 64 bit upload please 

### ISSUE THREAD

**Issue by Tall-Lobster** [FreeTubeApp/FreeTube#472]
Dear Developer,

It would be really appreciated if you could provide an appimage in 64 bit variant as my linux mint running off a live usb has the x64 bit and cannot run the x86 build you provided

**Comment by PrestonN** [comment]
The AppImage builds are already 64 bit.  Electron doesn't even support 32 bit any more so it would have been impossible to release a 32 bit AppImage in the first place.  Please make a new issue better describing your issue as it likely isn't because of the AppImage being 64 bit.

I would also make sure that the problem persists on a full install and not only in a live mode.

**Comment by Tall-Lobster** [comment]
Dear PrestonN:

here is a screenshot showing how you suggested that AppImage build was 32 bit
![screenshot for github](https://user-images.githubusercontent.com/46766067/80974276-7d2c2780-8dee-11ea-98a2-ad517f7c4b2d.png)

secondly, I installed LMDE (linux mint debain edition) on virutal machine and it will not run and here is the error I got:
![bug when you run freetube appimage](https://user-images.githubusercontent.com/46766067/80974329-9208bb00-8dee-11ea-8c23-e5bd1c4e1cfe.png)

if you still think that is my fault that something is wrong then you go run both a live USB and an virtual install and see that the AppImage is not working.

**Comment by PrestonN** [comment]
I apologize.  I can see where the confusion was made.  Unfortunately the website was labeled incorrectly and I will get that fixed.  My point still stands that all versions of FreeTube are 64bit only because of Electron not supporting 32bit.

As for the error that you're having, you might find #431 helpful in fixing that issue.

**Comment by Tall-Lobster** [comment]
It turns out #431 did solve the problem. Thanks
