### ISSUE TITLE
[Feature Request]: Copy link to the tab you are on on an channel page (Playlists → /playlists)

### ISSUE THREAD

**Issue by aleksejrs** [FreeTubeApp/FreeTube#4721]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

1.    Go to a channel page, like https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg
2.    Click "PLAYLISTS"
3.    Click "Share Channel"
4.    Click YouTube → Copy Link
    result: https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg

If I want to download all the videos that are in a playlist, and I give that URL to yt-dlp, it will download all videos from the channel without playlist data, and it will be difficult to sort them without redownloading.

### Proposed Solution

Copy https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg/playlists

On YouTube, step 2 leads me to https://www.youtube.com/@techlore/playlists, which is a synonym for https://www.youtube.com/channel/UCs6KfncB4OV6Vug4o_bzijg/playlists

### Alternatives Considered

Right-click "PLAYLISTS" to show a menu with "Copy link" and potentially other items.

### Issue Labels

ease of use improvement, improvement to existing feature, support for external software

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this as i have looked around on YT and came to the conclusion that the feature you are proposing is a non standard way of sharing channel urls

**Comment by csswright** [comment]
What is non-standard about this? Go to any channel page, it's the URL:

`https://www.youtube.com/@CHANNEL_NAME`

Click on any of the tabs, it's the URLs:

    https://www.youtube.com/@CHANNEL_NAME/videos
    https://www.youtube.com/@CHANNEL_NAME/shorts
    https://www.youtube.com/@CHANNEL_NAME/streams
    https://www.youtube.com/@CHANNEL_NAME/playlists
    https://www.youtube.com/@CHANNEL_NAME/posts

for the tabs named "Home", "Videos", "Shorts", "Live", "Playlists", "Posts", respectively. Just append `/videos`, `/shorts`, `/streams`, etc. to the URL channel. It doesn't make sense to be able to see a collection of these videos but not be able to copy them for sharing/downloading, especially because other Youtube-related tools like yt-dlp (which mpv integrates seamlessly) support this out of the box, as you would expect. It's strange you can access the corresponding collection of videos in Freetube but only in the FreeTube interface without being able to retrieve the corresponding URLS that tools like mpv and yt-dlp (which mpv integrates seamlessly) to play/download/share the collection of videos. Somehow the UI is more restrictive than the web browser.

It'd make more sense if FreeTube didn't support launching external players or supporting such useful third-party tools, but it does and they all support this feature.
