### ISSUE TITLE
[Feature Request]: Disable the alt key menu

### ISSUE THREAD

**Issue by LeoNoBit** [FreeTubeApp/FreeTube#4730]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Pressing the ALT key brings up a menu that, for my use (and I suspect for almost everyone else), is useless.
It is a commonly used key, and unfortunately it is not uncommon for me to make the mistake of displaying it unintentionally, which is annoying.

### Proposed Solution

Option to disable this menu.

### Alternatives Considered

Option to disable the shortcut or configure it.

### Issue Labels

ease of use improvement, new optional setting

### Additional Information

Thank you and best regards!

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
We wont implement an option to disable this. The menu only appears when you release the `Alt` key, with no other key pressed at the same time.

**Comment by j-ole** [comment]
The menu appears when pressing alt + F8-12 keys

**Comment by markcst** [comment]
> We wont implement an option to disable this. The menu only appears when you release the `Alt` key, with no other key pressed at the same time.

But why, @efb4f5ff-1298-471a-8973-3d47447115dc ?
Have you ever thought that one might be using that key (`alt`) to do other things?
Why not simply giving the option to disable it to the user? It'd be a user choice, you could dig it into the settings, no one would mess with that if not intentionally...

**Comment by absidue** [comment]
> Have you ever thought that one might be using that key (alt) to do other things?

If you are using the alt key to do other things outside of FreeTube at the operating system level, that thing should be swallowing the alt key press before it even reaches FreeTube. If they are handling the keypress but not stopping it from reaching other programs that is a bug on their end.

> It'd be a user choice, you could dig it into the settings, no one would mess with that if not intentionally...

Because every extra setting adds additional maintenance burden on us, it's not about it affecting other users, it's about it affecting us and causing extra unnecessary work for us, we are a tiny team of volunteers. FreeTube already has too many settings as is, at a given moment at least one of FreeTube's settings is broken, so we won't be adding more for niche use cases, that we don't want to support.

FreeTube is open source, so if you desperately want it you can always create a custom build for yourself with that functionality removed.
