### ISSUE TITLE
[Feature Request]: Option for chosing a different profile at start up

### ISSUE THREAD

**Issue by RyanOrigens** [FreeTubeApp/FreeTube#4787]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is currently no way to easily pick a different account at start up, you need to naviagate to settings and change it there.

### Proposed Solution

Netflix like profile picker, of course it could be hidden under settings or activated by default depending on preferences of the user.

![image](https://github.com/FreeTubeApp/FreeTube/assets/103891807/fdee4167-6259-4ede-a6f6-371b289565f2)

### Alternatives Considered

none.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Yes there is :)

https://github.com/FreeTubeApp/FreeTube/assets/73130443/1a3e05d8-bc80-4d26-83b6-aa10c4eb67da

**Comment by RyanOrigens** [comment]
The primary goal is to provide an easy way to select a different profile, rather than relying on a predetermined profile setting.

**Comment by rwperrott** [comment]
This is probably partially what I've been looking for, because having all subscriptions and playlists in one place soon becomes overwhelming/cluttered.
The easy creation of profiles, and allowing multiple profiles to be open at a time, was something Brave got right, even if some of the implementation had issues. It should be easy to copy/move stuff between profiles, and the taskbar should group windows by profile, not by all windows of the app.

**Comment by Oscarvdm** [comment]
Would love the ability to chose which profile should be the default. Currently I have to switch all the time.
