### ISSUE TITLE
[Feature Request]: Move "Display Play Button in Video Player" from Player settings to Distraction free settings

### ISSUE THREAD

**Issue by Caxtonis** [FreeTubeApp/FreeTube#4829]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Hiding the player button is a purely cosmetic change for an annoying logo so people will likely seek to change it in the Distraction free settings only to be confused when its not there
I almost made a feature request for adding the ability to hide the player button when i noticed a closed issue of someone else asking the same question #4483

### Proposed Solution

Move it to a more intuitive place like the Distraction Free settings, probably under the General category

### Alternatives Considered

None

### Issue Labels

ease of use improvement

**Comment by absidue** [comment]
Just to be clear that button is not just visual, for touch screen users it's very much functional, that's how they pause and play the video. Also to me at least it seems logical to check the player settings to change something about the player.

Sounds like what you need is a way to search through the settings (there is already an open feature request for that), instead of moving a player setting away from the player settings, which will make it more difficult to find for everyone else.

**Comment by Caxtonis** [comment]
I wasn't aware that it had a purpose for touchscreen users, thats a bummer.
