### ISSUE TITLE
[Feature Request]:   Quick-Move-To-Other-Playlist option in the video menu

### ISSUE THREAD

**Issue by cocoonkid** [FreeTubeApp/FreeTube#4868]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like to be able to quickly move videos to specifc playlists in the player view and in the playlist view itself.

### Proposed Solution

![image](https://github.com/FreeTubeApp/FreeTube/assets/43231640/81a7294e-99b1-40b7-af3a-a25cfb9b8bc3)

Add a menu  item "move_to"  and upon hovering open a list of playlists. 
Maybe make that list a max of 10 entries (for UI   and perf reasons)  but let us customize which ones appear there. 

### Alternatives Considered

not yet. I am not an UI expert.

### Issue Labels

new feature

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
I understand why you would want that but we really dont want to touch that menu because it is already way to big.

To add vids to a certain playlists you have to do it like this

https://github.com/FreeTubeApp/FreeTube/assets/73130443/12ad3562-66fa-4a8e-bab8-6bec2b9ac8bd

The quick way would be to enable the quick bookmark feature within the playlist so you can just click on the clock icon on the thumbnail to get it added to that playlist you set as the quick bookmark playlist

https://github.com/FreeTubeApp/FreeTube/assets/73130443/9e7b5f90-9c3c-4e2a-b1b8-0f467776cebb

**Comment by cocoonkid** [comment]
Thanks so much! That helps already a lot. I have 20k items. I will have a gpt sort it for me this weekend.

Much love!
