### ISSUE TITLE
Freetube launched in blank white screen

### ISSUE THREAD

**Issue by xeleven11** [FreeTubeApp/FreeTube#488]
I'm using dark mode in Windows 10 and recently whenever I launch the app the screen turn to blank not responding to any clicks. Are there any workarounds? Also there are a lot of errors not able to retrieve video in playing DASH format.

**Comment by xeleven11** [comment]
I've tried contacting the dev many times and eventually I found out what the problem was. It was the history tab causing it and I changed StartScreen to trending in settings from APPDATA. I still get white screen when I click history page. What can I do to fix it?

**Comment by xeleven11** [comment]
Freetube debug mode when opening history page.

![freetubehist](https://user-images.githubusercontent.com/47713837/91513776-19d77f80-e920-11ea-8b15-a3656fa9bfac.png)



`videos.js:137 Uncaught TypeError: Cannot read property 'toString' of undefined
    at videos.js:137
    at newArguments.<computed> (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\executor.js:29)
    at Cursor.execFn (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\datastore.js:518)
    at callback (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\cursor.js:126)
    at C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\cursor.js:193
    at C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\datastore.js:329
    at Object.async.eachSeries (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\async\lib\async.js:130)
    at C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\nedb\lib\datastore.js:323
    at fn (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\async\lib\async.js:582)
    at Immediate.<anonymous> (C:\Users\user\AppData\Local\Programs\FreeTube\resources\app.asar\node_modules\async\lib\async.js:498)`

**Comment by PrestonN** [comment]
I apologize for not responding right away.  The main reason I didn't respond is because I have now plans / interest in making any fixes for the live release.  I am hard at work on a rewrite right now and this is simply a non-existent issue in that version.  I am happy to accept a PR for this fix but the unfortunate truth is that I won't be fixing this myself.  I apologize for this inconvenience but right now getting the rewrite finished is my highest priority.

You are more than welcome to download and use this rewrite over on the [actions](https://github.com/FreeTubeApp/FreeTube-Vue/actions?query=workflow%3ABuild) page and provide feedback.  Keep in mind that it isn't finished and is missing several features, but it's much more stable than the live release.

**Comment by xeleven11** [comment]
Deleting some of the videos list in history database solved the crash. I switched to Vue 8.0 and it's working great with some features like community, playlist/favorites, subscription missing. UI is much more clean, organized and it's able to fetch all the videos in youtube channel using local API unlike invidious. However comments can only be read through invidious API. I've no idea how the local API works though.
