### ISSUE TITLE
[Bug]: video glitch since version 0.20

### ISSUE THREAD

**Issue by Angedestenebres** [FreeTubeApp/FreeTube#4890]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Open Freetube
2. Click on a video
3. The playing starts
4. After few second, there are some glitches.
5. See this video to illustrate the issue: https://video.tedomum.net/w/nf5o9io8pTRB7dbNXvUbMC

### Expected Behavior

Playing video without issue

### Issue Labels

visual bug

### FreeTube Version

0.20

### Operating System Version

Linux Mint 21.3

### Installation Method

Flathub

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

0.19.2

### Additional Information

I have two laptops and both has the same OS (Linux Mint 21.3) and version (flatpak 0.20) but only one laptop has this issue.
Both using X11.

However, the resolution of the laptop with the issue is 1366x768 (max for my screen).
I don't have the issue on the laptop with the resolution 1920x1080.

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Angedestenebres** [comment]
I complete the ticket with the PC configuration where I get the issue:

CPU: Intel© Core™ i5-5300U CPU @ 2.30GHz × 2
GPU: Intel Corporation HD Graphics 5500
RAM: 8Gb
Resolution: 1366x768

I tried to remove the app cache in /.var and also all the config, no effect.
Remove and install again the app didn't resolved the issue.

Also, I have no issue to watch a video directly from Youtube website or from a Peertube instance or a local video. The issue is linked to Freetube only.

**Comment by ssnor** [comment]
I have this exact problem and had to switch to the Flatpak to get around it, with the version 0.20 bump it has once again reared it's ugly head.

The bug is introduced somewhere between "v0.19.1-nightly-3750 Beta" and "v0.19.1-nightly-3828 Beta" (for once, procrastinating cleaning my ~/Downloads came in useful :P).
Since the Flatpak fixed the problem and no one had filed an issue here, I assumed I had a problem with my configuration.

It doesn't show up on screen record.
I see it in pretty much every video, multiple times.
Minimum once every five minutes, but on some videos several times a minute.
I get the impression that more active videos have more of the bug.
On a rewatch of a video, it doesn't occur on the same timestamps.
Fullscreen or not doesn't seem to matter.

It shows up in Freetube v0.19.1-nightly-3828 Beta and the v0.20.0 Beta Flatpak, but not in the v0.19.1-nightly-3750 Beta.

Here's my configuration, it's a Dell Latitude E7450 laptop with three monitors connected trough a dock.

OS: 				openSUSE Tumbleweed x86_64 
Host: 			Latitude E7450 
Kernel: 			6.8.2-1-default 
Resolution: 		1920x1080, 1920x1080, 1920x1080 
DE:				Xfce 4.18 
WM:			Xfwm4 
CPU:			Intel i5-5300U (4) @ 2.900GHz 
GPU:			Intel HD Graphics 5500 
Memory:			4178MiB / 15863MiB 
Display server:	X11

**Comment by Angedestenebres** [comment]
Interesting, we have the same CPU / GPU. Maybe it's related to that.
I think it could be interesting to have more reports and details about configurations.

**Comment by jwadden** [comment]
I've got the same problem when I use FreeTube on my old laptop (a Lenovo G70-80 with an Intel I7-5500U CPU with integrated HD 5500 graphics.) I can watch videos through other applications (browser, Celluloid, etc.) without a problem. When I use FreeTube on my main desktop PC (AMD 5700X CPU, Radeon 7600 graphics) it works fine, so the problem seems to be specific to old Intel CPUs.

**Comment by ssnor** [comment]
I can pretty much confirm that this is an hardware acceleration bug.
The bug disappears when you deny FreeTube GPU acceleration (and CPU levels rise back to what they where before the update).
Can any of you guys try it and see if that solves the issue for you?
[Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) can deny GPU acceleration in the sandbox if you use the Flatpak version of FreeTube.

I always suspected something with the GPU since the visuals of the bug reminded me of what a faulty GPU can look like.
Can we assume this is an Electron bug, or is GPU acceleration handled by something else in FreeTube?

**Comment by absidue** [comment]
FreeTube turns on VA-API video decoding on Linux in Electron but the rendering of the videos is outside of FreeTube's control. As you all seem to be using pretty similar hardware, I suspect that it is more likely to be GPU driver issue. Probably in the Intel driver's VA-API implementation for that hardware.

**Comment by Angedestenebres** [comment]
Hello,

@ssnor: You are right. If I disable the GPU acceleration via Flatseal, it works like a charm.

@absidue: I think there is a link with the GPU but did you change something between old versions and the current one? Because I use Freetube on this computer since 2021 and I never see that until now.

**Comment by ssnor** [comment]
It's probably just a flag set to activate GPU acceleration for our architecture in an Electron bump.
I am curious if it is possible to disable it without using the Flatpak sandbox?

[This is the driver I think,](https://github.com/intel/media-driver/wiki) but I couldn't find an issue filed for this bug.
Btw, this might be woo-woo, but I found the bug reduced in frequency after a BIOS update. Could be placebo though.

**Comment by Revival8697** [comment]
Can you run a Chromium browser (Chromium, Chrome, Brave, ...) with the `--enable-features=VaapiVideoDecodeLinuxGL` flag (enable hardware acceleration), and see if it plays YouTube videos without issues?

CC: @Angedestenebres  @ssnor.

> did you change something between old versions and the current one?

https://github.com/FreeTubeApp/FreeTube/pull/4532 happened.

**Comment by Angedestenebres** [comment]
Hello,

After checking by opening Chromium with this value, I have no issue at all.
However, if I enable again the GPU acceleration via Flatseal, I get again the issue on Freetube.

**Comment by Revival8697** [comment]
> Hello,
> 
> After checking by opening Chromium with this value, I have no issue at all. However, if I enable again the GPU acceleration via Flatseal, I get again the issue on Freetube.

Hmm. If it is working on Chromium, it should work on Freetube.

Can you verify your hardware acceleration is working on Chromium?
Play a video, F12 > Vertical 3 dots > `More tools` > `Media` > `Video decoder`, `Hardware decoder` should be `true`.

**Comment by blhobbs** [comment]
I have the glitching problem too.  I'm running v0.20.0 on an Intel NUC (i3 processor) with XUbuntu 22.04.  Actually I have it running on two identical NUCs with the same OS, and using the built-in video hardware. 
I only see the glitchy video on one of the NUCs.  The only difference that I'm aware of is that the video resolution is set to 1280x720 where I see the glitchy video. The other is set to 1920X1080 and no problems with the video.
The glitchy video shows up when playing the video in full screen OR non-fullscreen.  It occurs every minute or so. 
I glad I found this bug report, since I hadn't thought about the resolution difference in my two setups.
GREAT software otherwise - I'm really enjoying it.
Here's two successive frames showing the problem
![Glitch1](https://github.com/FreeTubeApp/FreeTube/assets/6117049/352baf31-2392-4122-b4d6-59195cdaec6c)
![Glitch2](https://github.com/FreeTubeApp/FreeTube/assets/6117049/6b8f6b7a-f14d-4788-a94e-2488dedc7dfd)

**Comment by msjoberg** [comment]
I have this issue as well. At least some workaround like a setting to disable GPU acceleration would be nice.

```
$ lspci -k | grep -EA3 'VGA'
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 5500 (rev 09)
	DeviceName:  Onboard IGD
	Subsystem: Dell HD Graphics 5500
	Kernel driver in use: i915
```

**Comment by Revival8697** [comment]
> I have this issue as well. At least some workaround like a setting to disable GPU acceleration would be nice.

You can use `--disable-gpu` for now.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Does this issue still persist for you on v0.21.0?

**Comment by Angedestenebres** [comment]
Hey :cat: 

> Does this issue still persist for you on v0.21.0?

For the moment, the flatpak version is still in 0.20. I'll try again when the 0.21 will be available.

**Comment by Angedestenebres** [comment]
After testing with the version 0.21 with my computer (see: https://github.com/FreeTubeApp/FreeTube/issues/4890#issuecomment-2041364824), I still have the issue.

**Comment by CaptainMorgan12** [comment]
Environment: librem 5, postnaketos edge, freetube 0.20, kernel 6.6.32-librem5.2, wayland, phosh 0.39.0r1.

![Freetube](https://github.com/FreeTubeApp/FreeTube/assets/80182265/cf0b211c-eaaf-49f1-9e86-67eaa570b0ba)

For me videos play normally but especially on initial load all the subscription videos show up with dark blue tint, playing the video and going back to subscription list then shows the correct color.

**Comment by Angedestenebres** [comment]
The issue is still there with the latest version (0.21.2).

**Comment by Flashwalker** [comment]
I'm running Wayland on KDE Neon distro on Intel Ultra 7 CPU wuth ARC graphics driver installed.
There is a total player glitch in Freetube

![Снимок экрана_20240811_181843-1](https://github.com/user-attachments/assets/acf59f8a-a7f8-4db3-9fe8-bbd5759615f3)

**Comment by CaptainMorgan12** [comment]
still have the issue with v0.21.3 Beta

**Comment by Angedestenebres** [comment]
Hello

I confirm I still have the issue and since an update of freedesktop on flatpak side, it's even worse because I can't use anymore Freetube without GPU acceleration:

![image](https://github.com/user-attachments/assets/1a62a430-e7e1-414f-a967-136e235cda24)

When I run it via terminal, I got the following error:

```
[2:0911/172014.248428:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 17:20:14.439: Failed to load module "xapp-gtk3-module"
[2:0911/172014.513572:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
[2:0911/172014.513673:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Aucun fichier ou dossier de ce type
MESA: error: Failed to query drm device.
glx: failed to create dri3 screen
failed to load driver: iris
failed to open /dev/dri/card1: Aucun fichier ou dossier de ce type
failed to load driver: iris
```

So currently, Freetube is unusable on my computer but maybe this can help to find the root cause, I'm sure this is 100% on Freetube side.

**Comment by Revival8697** [comment]
@Angedestenebres This may help.

https://wiki.archlinux.org/title/Intel_graphics#Corruption_or_unresponsiveness_in_Chromium_and_Firefox

**Comment by Angedestenebres** [comment]
> @Angedestenebres This may help.
> 
> https://wiki.archlinux.org/title/Intel_graphics#Corruption_or_unresponsiveness_in_Chromium_and_Firefox

Thanks but I don't know how to set that quickly with flatpak & flatseal.

**Comment by Revival8697** [comment]
@Angedestenebres Can you try running FreeTube with `MESA_LOADER_DRIVER_OVERRIDE=i965`?

**Comment by Flashwalker** [comment]
> Can you try running FreeTube with `MESA_LOADER_DRIVER_OVERRIDE=i965`?

it works for me

**Comment by Revival8697** [comment]
Can people with 5th gen Intel test native FreeTube (not Flatpak) on an up-to-date distro (not Debian)?

This is most likely an issue with the `iris` driver in `mesa` at this point.

**Comment by absidue** [comment]
Okay so it sounds like at this point it's basically confirmed to be a problem with the graphics driver which means we can't do anything about it from our side, so I'll label this with https://github.com/FreeTubeApp/FreeTube/labels/third-party .

If the graphics drivers do ever get fixed, feel free to mention it here or close the issue directly.

**Comment by Revival8697** [comment]
> Can those with 5th Gen Intel CPU (Gen 8 GPU) test native FreeTube (not Flatpak) on an up-to-date distro (not Debian)?
> 
> This is most likely an issue with the `iris` driver in `mesa` at this point.

Anyone?

**Comment by Angedestenebres** [comment]
Hello,

The issue seems to be fixed with the version 0.22 on my side.

**Comment by Flashwalker** [comment]
@Revival8697 
> @Angedestenebres Can you try running FreeTube with `MESA_LOADER_DRIVER_OVERRIDE=i965`?

Just updated to 0.22 Beta release and now it doesn't works anymore.
`MESA_LOADER_DRIVER_OVERRIDE=i965` now gives just white screen with sound instead of video.

 intel ARC graphics.

**Comment by ssnor** [comment]
> @Revival8697
> 
> > @Angedestenebres Can you try running FreeTube with `MESA_LOADER_DRIVER_OVERRIDE=i965`?
> 
> Just updated to 0.22 Beta release and now it doesn't works anymore. `MESA_LOADER_DRIVER_OVERRIDE=i965` now gives just a white screen with sound instead of video.
> 
> intel ARC graphics.

Same issue over here, some videos goes all white on fullscreen.
I had to downgrade to have a usable program.

I'm using the flatpak and just updated normally, so the issue shows with no special command line arguments.

**Comment by Flashwalker** [comment]
> Launching with `--enable-features=` (yes, it is empty) will launch FreeTube without any additional flags thanks to #5438

`--enable-features=` helps for 0.22.0 Beta

**Comment by ssnor** [comment]
> @ssnor Launching with `--enable-features=` (yes, it is empty) will launch FreeTube without any additional flags thanks to #5438.

Thank you, Revival!
This solved my problem!

**Comment by maddiew95** [comment]
> I can pretty much confirm that this is an hardware acceleration bug. The bug disappears when you deny FreeTube GPU acceleration (and CPU levels rise back to what they where before the update). Can any of you guys try it and see if that solves the issue for you? [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) can deny GPU acceleration in the sandbox if you use the Flatpak version of FreeTube.
> 
> I always suspected something with the GPU since the visuals of the bug reminded me of what a faulty GPU can look like. Can we assume this is an Electron bug, or is GPU acceleration handled by something else in FreeTube?

this works like a charm!
