### ISSUE TITLE
[Bug]: Segfaults after updating to electron 30

### ISSUE THREAD

**Issue by adolfintel** [FreeTubeApp/FreeTube#4964]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

I've been using the freetube-git package from the AUR for a few months without issues. Today the system updated electron and installed version 30.0.0-1 and FreeTube no longer starts.

When launched, it briefly shows an empty window then segfaults. From the terminal it just says `/usr/bin/freetube: line 3: 31684 Segmentation fault      (core dumped) electron /usr/lib/freetube/app.asar "$@"`

I tried rebuilding the package but it didn't fix it. Downgrading to electron29 works though.

### Expected Behavior

It doesn't segfault

### Issue Labels

causes crash

### FreeTube Version

v0.20.0.beta.r6351.5359d84-1

### Operating System Version

Arch Linux

### Installation Method

AUR (Unofficial)

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

Same one but with electron29

### Nightly Build

- [x] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
You should report this to the maintainer of that package

**Comment by tuxayo** [comment]
Ok, I guess that means it should work to with electron 30

**Comment by tuxayo** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc @absidue wait, electron 30 isn't supported (from package.json and yarn.lock), please reopen this issue, it's about electron 30 support, not a third party package.

**Comment by absidue** [comment]
Electron 30 works completely fine with the official build process (yes I checked it myself) and setup. In the issue description you mentioned nothing about using the official build processes, only AUR and you for some reason also put a checkmark on the nightly builds box, which makes no sense as FreeTube's nightly builds are based on this source code repo, which is still using Electron 29.

Your problem is that you built FreeTube for Electron 29 but are trying to run it on Electron 30 and as we have told both the AUR and nixpackages people before, you should only run FreeTube with the Electron versions that is listed in the package.json file.

So either you build FreeTube properly and run it the official way with the bundled Electron, so no AUR shenanigans or you downgrade Electron on your system.

**Comment by absidue** [comment]
@tuxayo This issue is about the unofficial freetube-git AUR package being incorrectly setup to always use the latest version of Electron, instead of the version of Electron that FreeTube actually supports. It is not our job to work around incorrectly setup unofficial packages.
