### ISSUE TITLE
Infinitely loading after attempting to import xml subscription list

### ISSUE THREAD

**Issue by Wrapscallion** [FreeTubeApp/FreeTube#5]
I'm sure that you didn't intend for people to use the xml subscription lists that you can export from Youtube, but on a lark I decided to manually specify my personal xml file on the import function, got a "Import was successful" message, restarted as requested, and then was stuck on an infinitely loading page.

![freetube_error](https://user-images.githubusercontent.com/12211653/36937998-706c0d74-1ee9-11e8-8acd-6f0d268fa33b.png)

Deleted the app out of the Local and Roaming folders and reinstalled. This is most likely not intended usage by you, but I figured I would bring it up anyway.

**Comment by PrestonN** [comment]
In a very technical stand point, the import was "Successful" because it takes the file and sends it over to your local folder.  As of right now, the app doesn't support subscriptions exported from YouTube and only works with the database files generated by FreeTube itself.  I do have plans to support this in the future though.

If I don't end up supporting it in the next release, I will at least add some better checks to prevent this from soft locking the application.

**Comment by PrestonN** [comment]
Hey there.  This has been added.  Expect this in the next release.
