### ISSUE TITLE
Import subscribes from google account

### ISSUE THREAD

**Issue by sr-tream** [FreeTubeApp/FreeTube#50]
When I tried import subscribes from google account, I see error: "Invalid OPML File. Import is unsuccessful.". I got file "subscription_manager" from subscription manager (https://www.youtube.com/subscription_manager).

P.S. NextCloud News and Akregator imported this OPML file is successful.
P.S.S. I using version 0.1.3 Beta, OS: archlinux amd64

**Comment by PrestonN** [comment]
This may be related to #41.  The feature is working fine for me on Ubuntu so it might be an Arch specific issue.  I'm working on setting up an Arch VM so I can do some testing on various things and I will look at this while I'm at it.

**Comment by dimqua** [comment]
It works on Windows also.

**Comment by sr-tream** [comment]
May be problem in my OPML? But it work with Akregator and NextCloud News


[subscription_manager.zip](https://github.com/FreeTubeApp/FreeTube/files/1818146/subscription_manager.zip)

**Comment by PrestonN** [comment]
Hey thanks for providing that.  I was able to find the problem.

The header of the file was slightly different because of it using Russian instead of English.  I've made a slight change that should fix this in the next update.

In the mean time, here's a file with your subscriptions that should import successfully in the current version.

[subscriptions.zip](https://github.com/FreeTubeApp/FreeTube/files/1820397/subscriptions.zip)

Take care! :)
