### ISSUE TITLE
Show subscription logo in searches

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5021]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When a search query is submitted, if a video is found that belongs to a channel the user has subscribed to, the FreeTube logo should appear beside that channel name, like it does when a subscribed channel posts a comment on another video.

### Proposed Solution

.

### Alternatives Considered

.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
If the user searches for something like `Linus Tech Tips` and is subscribed to that channel now all videos will get this label which is very undesired and not needed. The reason labeling in the comments make sense is because comments from other YT'ers might be lost in all the noise but with the labeling you can quickly identify their comments.
