### ISSUE TITLE
[Feature Request]: More Download preference options 

### ISSUE THREAD

**Issue by BGMSMX** [FreeTubeApp/FreeTube#5030]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

When I want to download a video from your site, and click download, your don't have an option of of downloading the video with both audio and video, instead, I have to download them separately, video only, or audio only, and this is quiet a long winded option. 
Other video downloaders gives you more options, but with FreeTube, the download options and settings are useless.
I just want one option, click and download both video and audio at the same time.

### Proposed Solution

My proposal is when you click the download icon in the FreeTube page, there should also be a download video and audio to click and download, instead of individual downloads.
This should also be included in the settings, as there isn't a suitable option there either.

### Alternatives Considered

If my opinion isn't valid or seen as a fixable, then I will remove FreeTube app, and look for something that is to my liking.

### Issue Labels

ease of use improvement, improvement to existing feature, new optional setting

**Comment by absidue** [comment]
FreeTube shows everything that YouTube offers, unfortunately they only offer 720p and 360p with both audio and video.

What other downloaders do is download an audio stream and a video stream and then call out to ffmpeg to combine them into a single file.

Due to the very complicated nature of trying to support something like that in FreeTube (the only cross platform way of doing it, would be dreadfully slow, it would take longer than the actual downloads), it's out of scope for FreeTube at the moment. If you want advanced downloading functionality like that, I recommend that you use a dedicated downloading tool like [yt-dlp](https://github.com/yt-dlp/yt-dlp).

**Comment by Mafkeddada** [comment]
> ### Guidelines
> * [x]  I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
> * [x]  I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
> * [x]  This issue contains only one feature request.
> 
> ### Problem Description
> When I want to download a video from your site, and click download, your don't have an option of of downloading the video with both audio and video, instead, I have to download them separately, video only, or audio only, and this is quiet a long winded option. Other video downloaders gives you more options, but with FreeTube, the download options and settings are useless. I just want one option, click and download both video and audio at the same time.
> 
> ### Proposed Solution
> My proposal is when you click the download icon in the FreeTube page, there should also be a download video and audio to click and download, instead of individual downloads. This should also be included in the settings, as there isn't a suitable option there either.
> 
> ### Alternatives Considered
> If my opinion isn't valid or seen as a fixable, then I will remove FreeTube app, and look for something that is to my liking.
> 
> ### Issue Labels
> ease of use improvement, improvement to existing feature, new optional setting
> 
> ### Additional Information
> _No response_

Free tube is missing very important tool which is ability to dowload a file with both video and audio in one file. 
I have free tube since few days and I like it very much for privacy reason but I have noticed the problem with download. 
It would be great to have an option for offline watch .
Please think about resolving this problem .

**Comment by bege10** [comment]
A workaround is to open an external player like MPC-HC from FreeTubeApp and use this for downloading with yt-dl.exe. I only need to copy yt-dl.exe and - this is new - deno.exe in the program folder of MPC-HC.
Couldn't the same be accomplished with FreeTube directly?
