### ISSUE TITLE
Everything stopped working

### ISSUE THREAD

**Issue by felixsanz** [FreeTubeApp/FreeTube#509]
Subscriptions page doesn't list any video. Trending and Most Popular pages are empty too. If i click on a channel i get "Unable to load channel XXX" (XXX = channel name)

**Comment by deejf** [comment]
I installed FreeTube (off of FlatHub, running Fedora Linux) three days ago. 

First day, worked great.

Second day, worked, but sloooooooowly.

Today, I've got this. Nada.

Which is weird, because checking Yewtube, that works, so it doesn't appear to be an Invidious thing.

**Comment by deejf** [comment]
I installed FreeTube (off of FlatHub, running Fedora Linux) three days ago. 

First day, worked great.

Second day, worked, but sloooooooowly.

Today, I've got this. Nada.

Which is weird, because checking Yewtube, that works, so it doesn't appear to be an Invidious thing.

**Comment by deejf** [comment]
I installed FreeTube (off of FlatHub, running Fedora Linux) three days ago. 

First day, worked great.

Second day, worked, but sloooooooowly.

Today, I've got this. Nada.

Which is weird, because checking Yewtube, that works, so it doesn't appear to be an Invidious thing.

**Comment by PrestonN** [comment]
The https://yewtu.be instance appears to return a lot of 429 and 503 errors, which means that the server is actively blocking large amounts of traffic at once.  Checking the API manually still works however any attempt to access the API through FreeTube is blocked.  You'll want to get in touch with the maintainer if you want to use FreeTube with that specific instance.

The main instance also seems to be a bit slow recently, however I unfortunately do not know the reasoning.  I can only suggest that you wait for the main instance to have their issues resolved or to try another instance.  There isn't anything I can do to fix this.

If you are still having issues, you are more than welcome to try out some test builds of the rewrite where there is a local API available.  Subscriptions are not available yet but it's very usable in every day video watching.  You can download the latest test build over on the [Actions Tab](https://github.com/FreeTubeApp/FreeTube-Vue/actions) in the repo.

I'm going to go ahead and close this since this is technically not an issue with the FreeTube side, however you're welcome to continue the discussion here if you want.
