### ISSUE TITLE
Remove npm install lines in shell config file

### ISSUE THREAD

**Issue by forkbomb9** [FreeTubeApp/FreeTube#51]
I'm building FreeTube from source code, and I founded that `npm install` installs a few lines on (either `~/.bashrc` with bash, `~/.zshrc` with zsh or `~/.config/fish/config.fish` with fish shell):

> #tabtab source for electron-forge package
> #uninstall by removing these lines or running `tabtab uninstall electron-forge`
> [ -f /home/namkhai/.apps/FreeTube/node_modules/tabtab/.completions/electron-forge.fish ]; and . > /home/namkhai/.apps/FreeTube/node_modules/tabtab/.completions/electron-forge.fish

I'm trying to write a PKGBUILD to build a package for Arch Linux, and I don't know how to run `tabtab uninstall electron-forge`
Can anyone help me please? If there's need of more info, tell me

**Comment by PrestonN** [comment]
This might be similar to #37 and #41.  I'm working on getting an Arch VM setup to that I can look more into this.  Thanks.

**Comment by keijukainen** [comment]
You can find my pkgbuild at the link below. It required patching the package.json file and I added a .desktop shortcut and resized the icon.

https://github.com/KaOS-Community-Packages/freetube

**Comment by PrestonN** [comment]
Hey @keijukainen, I don't mind you putting FreeTube there, but could you please add a link to this repo in the README so users know where to go for issues?  It would be very appreciated and thanks in advance. :)

**Comment by keijukainen** [comment]
I can add a link in the readme but the pkgbuild already contains one. The KaOS distro uses the pacman package manager and the octopi front end. The vast majority of users don't even realize that for every package displayed in octopi there's a pkgbuild repo on github. Most users install software through octopi rather than downloading the pkgbuild and building it manually. The screenshot below is what they will see if searching for freetube.

![octopi_freetube](https://user-images.githubusercontent.com/25158983/37655352-00f6a2b0-2c13-11e8-939d-41a047d65017.jpg)

**Comment by LexHimself** [comment]
No need to call tabtab, just execute the following from the pkgbuild: 
`sed -i '/tabtab source for electron-forge package/d' ~/.bashrc`
`sed -i '/electron-forge.bash/d'  ~/.bashrc`
`sed -i 's/# uninstall by removing these lines or running/d' ~/.bashrc`

**Comment by PrestonN** [comment]
This might not be needed any more with the rewrite coming up.  If this is still a problem then please re-open.
