### ISSUE TITLE
Integrate repository w/ online localization tool like Weblate

### ISSUE THREAD

**Issue by sanecito** [FreeTubeApp/FreeTube#512]
It looks like this project could use a decent amount of localization love. Would suggest using Weblate to lower the bar to contribute as it's FOSS and you can self host an instance or the Weblate team will host for you for free if you're a FOSS. With a tool like Weblate, people don't need to be computer science types to know forking and PR'ing, etc. They just go to the project subpage where they are presented with a string, they put in the equivalent in a field and hit a suggest/save button. (See https://hosted.weblate.org/ for how it's used)

It also helps provide a quick view of what languages exist for an app and what percentage of each language is done on top of features like subscribing to get notifications when strings are updated/added.

**Comment by PrestonN** [comment]
So here's where I'm at with translations.

I've actually already had access to Weblate for a while now.  I've never announced it because right now none of the translations (Even the English ones) were usable because the English translation is missing way too many strings that are included in the app.  I simply haven't had the time to flesh out that file so that I could properly use and take advantage of translations.

Having said that, there's been a huge focus towards [the rewrite](https://github.com/FreeTubeApp/FreeTube-Vue) and a few members of the community have stepped up to help compile this file for use with the app.  At this point nearly all of the app has been hooked up and can be ready for translations.  There's still a little bit left to go and more strings that will be added as more functionality is added.

Since we're doing a majority of the work in a different repo for now, this leaves us in an awkward situation.  Weblate is hooked up for this repo yet our work is being done in the other one.  We'll have to accept translation PRs over here and then manually transfer them over to the other repo.  At the same time, we'll have to close any translation PR in the other repo to avoid any conflicts.

There's a merge conflict I need to resolve before I can officially accept translations through Weblate.  Once that's done, I can make the announcement.

**Comment by sanecito** [comment]
Thanks for the quick and detailed response! Looking forward to the announcement so I can contribute a language!

**Comment by PrestonN** [comment]
Hey there!  Weblate is now available to be used with the project.  You can find more information at the announcement blog [here](https://write.as/freetube/freetube-is-now-accepting-translations-via-weblate).

If you'd like to go directly to Weblate, you can follow [this link](https://hosted.weblate.org/engage/free-tube/).

Will go ahead and close this since it's now available.

**Comment by sanecito** [comment]
Excellent, thanks for the followup; I'll make sure Japanese is ~100% by the end of the week!
