### ISSUE TITLE
[Feature Request]: Hide loading circle

### ISSUE THREAD

**Issue by eshsdhsd** [FreeTubeApp/FreeTube#5129]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There is a loading circle on the video

![image](https://github.com/FreeTubeApp/FreeTube/assets/79751239/41c5a45f-61b8-48d2-938f-b5cc81ead819)

### Proposed Solution

Want an option to hide it

### Alternatives Considered

None I can thi

### Issue Labels

ease of use improvement, new optional setting, visual improvement

**Comment by jasonhenriquez** [comment]
Hi @eshsdhsd, we will not implement this feature, as we''re trying to minimize our optional features. Before creating future issues, please note that a high percentage of your previous issues are showing as duplicates or Do not Implements, and FreeTube has a stringent bar for which features it chooses to implement.

**Comment by eshsdhsd** [comment]
> Hi @eshsdhsd, we will not implement this feature, as we''re trying to minimize our optional features. Before creating future issues, please note that a high percentage of your previous issues are showing as duplicates or Do not Implements, and FreeTube has a stringent bar for which features it chooses to implement.

Seriously? Minimizing features Is not a very good Idea. second can I at least mod the app and remove it myself. 

I hate it when people think having as many option is too much

**Comment by jasonhenriquez** [comment]
> can I at least mod the app and remove it myself.

Yes, please check [the AGPLv3 license](https://github.com/FreeTubeApp/FreeTube?tab=AGPL-3.0-1-ov-file#readme) for more information.

> I hate it when people think having as many option is too much

I hope you can understand that we want to maximize customizability while also not overwhelming the user with information. Expanding our optional feature set without bound also increases the testing burden for our developers, leading to a higher chance of such features breaking in the future. This means that we sometimes have to make tradeoffs on what features we will or will not accept. Hiding the loading circle altogether is a rare enough and idiosyncratic preference that an individual mod would be the preferable solution rather than an app-wide optional feature.

**Comment by eshsdhsd** [comment]
Alright I understand.
