### ISSUE TITLE
[Feature Request]: Is it possible to use plasma color scheme?

### ISSUE THREAD

**Issue by QuakeString** [FreeTubeApp/FreeTube#5131]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

FreeTube does not use plasam color scheme

### Proposed Solution

can't find any solution.

### Alternatives Considered

na

### Issue Labels

visual improvement

### Additional Information

Here is my screenshot. With dark color scheme it does not look very nice.
![Screenshot_20240519_222222](https://github.com/FreeTubeApp/FreeTube/assets/5375918/45a5c360-6514-487f-857b-b31021cfaa2a)
![Screenshot_20240519_222211](https://github.com/FreeTubeApp/FreeTube/assets/5375918/c8e26c96-0610-47af-808b-806b9dc690a8)

**Comment by absidue** [comment]
That's not possible no, FreeTube uses Electron (so that we can support Windows, macOS and Linux), so just like websites in your web browser FreeTube can't adapt to it (it may be possible to get some of the information like colors on Windows and macOS and for FreeTube to partially recreate the theme, but definitely not on Linux, with it's millions of different setups).

You can however choose between the various themes, primary and secondary colors inside FreeTube's theme settings.
