### ISSUE TITLE
[Bug]: 500 Error when clicking on a artist - topic channel

### ISSUE THREAD

**Issue by jschuhmann47** [FreeTubeApp/FreeTube#5201]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Search for an artist - topic, channel. For example: Evan call topic
2. Click on its channel
3. Error appears: `Error: Could not extract JSON. Youtube API returned error 500 with message:<br>"Internal error encountered."`
![image](https://github.com/FreeTubeApp/FreeTube/assets/76596375/95524f22-1878-4ddd-b2a1-bcb54d9477c5)

### Expected Behavior

When clicking an artist channel, it should show their playlists

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.20.0 beta

### Operating System Version

Linux Mint 21.3

### Installation Method

Flathub

### Primary API used

Invidious API

### Additional Information

It happens with all Artist - Topic channels. If Local API is selected, same result but without showing the error popup

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
The playlists not showing up with the local API is expected, FreeTube doesn't extract those (it used to but then YouTube changed how artist channels work and we haven't adapted to those changes, this is the first time in 6 months since YouTube changed it that anyone has even mentioned it, so it's been understandably pretty low priority) as for the 500 error, that's coming from Invidious which we can do nothing about other than falling back to the local API, which is what FreeTube did according to your screenshot.

I'll be closing this issue as the bug with the error is on the Invidious side not the FreeTube side, so we can't do anything about that. Feel free to open a new issue with feature request about showing the albums on artist topic channels with the local API though if you want it to work on the local API, that won't help with Invidious though.
