### ISSUE TITLE
[Bug]: Floating elements

### ISSUE THREAD

**Issue by albertovillari** [FreeTubeApp/FreeTube#5230]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. open freetube
2. left click on video/title/channel image
3. move mouse while holding left click
4. element will float (see the video)

### Expected Behavior

I think it is not suppose to float

### Issue Labels

visual bug

### FreeTube Version

v0.20.0

### Operating System Version

Ubuntu 22.04

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

https://github.com/FreeTubeApp/FreeTube/assets/121868369/1bc84538-e49b-46a6-abfd-e25fe42057cd

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by jasonhenriquez** [comment]
This isn't really a bug so much as [the default property of text and images being draggable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable). It's pretty benign and common. For example, just about everything on a GitHub page or on YouTube is draggable as well. It doesn't really matter and is often useful (e.g., you can drag text from a comment into the search bar. Closing this as an issue because there doesn't seem to be any problem that needs fixing here.
