### ISSUE TITLE
Import to FreeTube via NewPipe Export File Not Working.

### ISSUE THREAD

**Issue by acjonesy96** [FreeTubeApp/FreeTube#534]
I tried to import into FreeTube the file NewPipe created when I exported the database. First I tried to import "NewPipeData-xxxx_xxxx.zip". FreeTube informed me this was not a supported file format. When that failed I then extracted the file and tried to import newpipe.db. FreeTube didn't inform me if this was successful or unsuccessful. however when i checked my subscriptions tab nothing was present.

Build: Release 0.7.3 Beta

OS: Fedora32_x64

**Comment by PrestonN** [comment]
The problem is you're importing the incorrect file. You want the .json export that NewPipe provides.

On the subscriptions page, there's a drop down that has a "Export to File" option. That file is the one you want to import into FreeTube.

If you're using exports from their settings page, then it's the incorrect file.

Hope this helps.

**Comment by kubo6472** [comment]
I ran into the exact same problem, five minutes of search, and I found your [wiki page](https://github.com/FreeTubeApp/FreeTube/wiki/Importing-Your-YouTube-Subscriptions#from-newpipe).
