### ISSUE TITLE
UI scaling

### ISSUE THREAD

**Issue by linuxgirl22** [FreeTubeApp/FreeTube#544]
Hi :-)
Thanks for saying UI scaling can be looked into. I'm on Linux (EndeavourOS/Mate) and can't find any way to affect Freetube's UI (I'm running the awesome Vue) ... the text on the side bar, under subscriptions-view videos (channel name), and for comments, I find too small. I think the fonts for side bar and channel name are size 8, and comments 7? I'm needing to squint to see the side bar and channel names, and can't try to read the comments. Not super shortsighted, although I do wear glasses, but it would be so cool to be able to scale the UI, and could help people with the same or worse sight than myself too. I don't know what amount of work would be involved, but if it's at all possible to have e.g. a slider for scaling that would be awesome.

**Comment by GilgusMaximus** [comment]
Hey thanks for the feedback. First I'd like to say that I would appreciate it a lot if the issue templates are used in the future. Makes everything tidier. 

Regarding the size of the UI. That is definitely a valid point. Something like that shouldn't be too difficult to implement. This could probably be fixed in combination with the display problem in different languages.

I hope it is still viable to watch videos this way at the moment.

Best regards,
Gilgus

**Comment by linuxgirl22** [comment]
Thank you for your reply :-) and it's great to know that the UI scaling isn't too difficult to include.  

The largest text is the video title, and the videos play really well, but, because of the very small text elsewhere in Freetube, at the moment I use Liferea (can zoom/set the UI) to see titles, and then download videos. The Ctrl+Shift + that Preston advised does make a good difference, leaving only comments a little too small, but it needs doing each time Freetube is opened; it would be awesome to have a fixed zoom for the UI, if at all possible.

Thanks again for your response. 
Best regards, linuxgirl22

**Comment by GilgusMaximus** [comment]
Ah good to hear that it works for the moment with the default Electron zoom.
But adding a slider like that is definitely recorded as a higher than normal issue.

**Comment by linuxgirl22** [comment]
Thank you for your response. It's great that it zooms up, yes, but am relieved to hear the UI scaling is a higher than normal issue for sure; thank you very much for that. :-)

**Comment by PrestonN** [comment]
I just added this to the latest dev builds. Let me know if this works out for you.

**Comment by linuxgirl22** [comment]
Thanks so much Preston! and sorry for delay in responding.

**Comment by PrestonN** [comment]
All good!  I actually started adding Arch based binaries to the automated builds recently.  If you go to [this](https://github.com/FreeTubeApp/FreeTube/actions?query=workflow%3ABuild) location and click the first build with a check mark, you'll see the latest builds straight from development.  The `pacman` binary should be compatible with Arch based systems.  You can install that and give that a try or wait a couple of days for a full release.

I'll go ahead and close this as well, as I believe this should be implemented the way you're expecting.

**Comment by linuxgirl22** [comment]
Thanks for the link; I found an appimage ... and the UI scaling settings is AMAZING!!! Thanks so much! :-)

**Comment by PrestonN** [comment]
Thank you very much.  That's greatly appreciated that you'd like to do that.

The easiest method is probably through [Liberapay](https://liberapay.com/FreeTube).  It should be easy enough to make a donation and not renew it so that it counts as a one-off donation.  Only donate if you really want to though as I have no real need for it.

**Comment by linuxgirl22** [comment]
That's great; I'll look into that now, and thank you for understanding also ... and, again, for the amazing UI! :-)
