### ISSUE TITLE
[Feature Request]: Video Length in 

### ISSUE THREAD

**Issue by SkyeMors** [FreeTubeApp/FreeTube#5440]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I would like for videos (universally) to show the video length. Currently from what I've seen, it only shows video length in the corner of video previews in Playlists and in the Subscription page (and likely other places) if you've already "watched it" (loaded it locally, where it's presumably pulled from once the video loads).

### Proposed Solution

Have the video length timestamp in the bottom-right of thumbnails of all videos globally by default.

### Alternatives Considered

Have a "--:--" fake timestamp in the bottom-right of the thumbnail that stays blank until you hovor on it for long enough for it to grab the video length, then populate it.
Alternatively, grab and place the video length when it's added to a playlist on the user's end.

### Issue Labels

display more information to user

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
FreeTube automatically forces RSS when the currently selected profile has 125 or more subscriptions to avoid getting ratelimited. Unfortunately YouTube's RSS feeds don't include the video duration or live status. If FreeTube didn't force RSS, only about 130-160 channels would get fetched before you would hit YouTube's ratelimit and you would just get errors for the remaining channels.

Because of RSS you dont see the video duration

If you don't want to use RSS, split your subscriptions up into different smaller profiles or drastically reduce you subscriptions.

**Comment by SkyeMors** [comment]
Yes, I understand this, which is why I proposed the other optional solutions that have the user perform an action that manually, individually requests video length after a delay.
