### ISSUE TITLE
Whenever clicking a video or booting the app I get this

### ISSUE THREAD

**Issue by protodrew** [FreeTubeApp/FreeTube#553]
**Behavior of the program**
There doesn't seem to be any error but when the program it booted or I boot into a video it flashes several API errors

**Expected behavior**
The program runs without popups

**To Reproduce**
Import a list of subscriptions and boot up the app

**Screenshots**
https://0x0.st/i0Xi.png

**Desktop (please complete the following information):**
 - Pop!_OS
 - 20.04 LTS
 - FreeTube version: 0.8

**Additional context**
Error: Status code: 429

**Comment by GilgusMaximus** [comment]
Yes. That error means you are getting rate limited by YouTube. This happens when you use the program extensively and make a lot of requests.

I added this issue to the [FAQ](https://github.com/FreeTubeApp/FreeTube/wiki/F.A.Q.) page as well, so people can take a look over there. 

**Possible instant solutions are:**
- Use a VPN
- Change the network, so a new Ip address is used 
- Solve the captcha that is displayed when going to YouTube's webpage

Switching to RSS feeds in the setting will help preventing this issue a bit longer. Although you are loosing a bit of information on your subscription page. Especially with many subscriptions, this will improve the experience a lot. And at some unknown threshold of subscriptions you instantly get rate limited by YouTube if you use normal subscription refreshing.
