### ISSUE TITLE
Channel subscriber count is 0 in the search results

### ISSUE THREAD

**Issue by MPeti1** [FreeTubeApp/FreeTube#554]
**Behavior of the program**
The channel subscriber count is 0 in the search results.

**Expected behavior**
The channel subscriber count in the search results should be the same as on the channel main page, below the channel name

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to the main menu
2. Type a channel's name in the search bar at the top
3. Click the arrow button to submit
4. See the channels with 0 subscribers

**Screenshots**
If applicable, please add screenshots to help explain your problem. Especially console logs from the development tools are very helpful.
Search results with the bug:
![image](https://user-images.githubusercontent.com/9215491/94974685-948f4e00-050f-11eb-943f-0c82066a137f.png)

Freetube can actually get the number of subscribers correctly:
![image](https://user-images.githubusercontent.com/9215491/94974728-ba1c5780-050f-11eb-84ef-b1916bc0c81c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1909
 - FreeTube version: 0.8.0

**Additional context**
Been trying out Freetube for a few minutes, and wow.. I like how much the UI is like the YT UI, that there's the thing when you hover the mouse over the video timeline, and that it's loading the small thumbnail VERY quickly even when just holding the mouse button down there and seeking and.. there's a lot of details, and it's fast, and it's actually hard to believe that it's been put together only in a year. I think I won't need to open YT in the browser anymore
Keep up the good work!

**Comment by MPeti1** [comment]
It seems to be similar for viewer counts of live streams. It's probably only a problem with the search results menu
![image](https://user-images.githubusercontent.com/9215491/94975384-ca353680-0511-11eb-985f-c540f458b6ae.png)

**Comment by syncng** [comment]
These two issues are related to the ytsr (Youtube Search) module dependency of the project.

The bad news is that the channel subscription count is unfortunately not possible to fix, since ytsr uses an endpoint that gives out information about the number of videos a channel has, but gives out no valid information on the subscriber count (even though there is a "followers" property obtained, it always returns 0).
However, it's completely possible to simply remove the subscribers indicator for channels from the app itself though, and maybe there's some other module out there that could be used in the future to replace this one that **does** contain that information, who knows, someone would have to do some digging on that.

The good news is that the live views count is actually provided, it's just a bug with the module itself and I've already opened a PR with a possible solution for this problem.

**Comment by GilgusMaximus** [comment]
syncg is right here.
I already implemented a node module which fetches the subscriber count from the channel page.
However after performance testing, multiple users noted that the search takes 5 seconds or longer than without the module when **searching for channels only**.

Therefore this module did not make it into the build.

Additionally, making one request per channel displayed will get you rate limited by YouTube very quickly if you do a channel search. You can see this already without the module in #553
