### ISSUE TITLE
Implementing multiple backends

### ISSUE THREAD

**Issue by okias** [FreeTubeApp/FreeTube#570]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
First, thank you for a great app.

Would be nice in future, if application would be able to search multiple "providers" of content and allow better independency (while one proprietary service could block access at the time, posibility to search for videos on another service would be useful etc.) At least one already used implementation which could be used as some reference is [NewPipe](https://newpipe.schabi.org/)

**Describe the solution you'd like to see implemented**
I don't have clear preference how it could be implemented, best option would be likely to have filters on search, by default allowing searching all sites available, thus extending user ability to find more information.

**Describe alternatives you've considered**
Of course, another solution is to have multiple apps per site, but on other hand when Youtube implement algorithms or different kind of protection against using it other way than in the (their) browser, this application would lose it's importance, which would be shame.

**Screenshots**
Not available

**Additional context**

**Comment by PrestonN** [comment]
This won't be happening any time soon.  We won't have the resources to properly support more services and each one is structured differently which makes it difficult to support everything properly.

NewPipe is able to handle this because their front-end is designed around working with their custom built extractor, where every API is structured the exact same regardless of which service you're using.  We don't have that same luxury and maintenance will become a problem very quickly if we introduce more services.

We'll be sticking to YouTube for now.
