### ISSUE TITLE
[Bug]: Nightly 4776 Looping playlist only loops to end of every video.

### ISSUE THREAD

**Issue by DoYouKnowMyNamePlz** [FreeTubeApp/FreeTube#5718]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

1. Go to a playlist
2. Turn on loop playlist
3. let the playlist play all the way through
4. you will notice it only plays the end of the videos after 1st time watching it

### Expected Behavior

play through the playlist, then loop but have videos start from the beginning.

### Issue Labels

usability issue

### FreeTube Version

Nightly 4776

### Operating System Version

WIndows 11 23H2 build 22631.4169

### Installation Method

.exe

### Primary API used

Local API

### Additional Information

None that I am aware of, I can provide more upon request.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by KandiPanda** [comment]
It does this when you open *any* video that you've previously watched to the end (try opening a finished video from History, one not part of a playlist even). 

Has been doing it since [v0.21.3-nightly-4699](https://github.com/FreeTubeApp/FreeTube/actions/runs/10672303427) (when they switched from video.js to shaka-player). 

(I would've filed a more detailed bug report way earlier with steps to reproduce in several ways, but I'm using a very unsupported configuration (the `resources` folder from `freetube-#.#.#-nightly-####-win-x64-portable.zip` copied into Supermium-Electron in place of its placeholder `resources` folder, on Windows 7), and couldn't find anyone on a newer, officially-supported OS interested in testing it for me, and I didn't want to file a bug report on something that might just be a "me" issue (wrong OS, Electron version mismatch, etc.) without any idea if it also happens on a _supported_ configuration.)
