### ISSUE TITLE
Quality selector menu for audio formats shows numbers instead of human-friendly names

### ISSUE THREAD

**Issue by oczkoisse** [FreeTubeApp/FreeTube#574]
**Behavior of the program**
On switching to 'Use Audio Formats' for any playing video, the quality selector menu (gear icon) shows various numbers whose origin is unclear.

**Expected behavior**
Instead of numbers, the program should show human-friendly audio quality descriptions. Not sure what these would be, but something like "codec - bitrate" should be a good start.

**To Reproduce**
1. Play a video
2. Select 'Use Audio Formats'
3. Open quality selector menu (the gear icon)
4. Numbers instead of human friendly quality descriptions are shown (see screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/10922171/95007429-2315d500-05cd-11eb-8dbe-095a46986243.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10.0.19041 Build 19041
 - FreeTube version: 0.8.0 Beta

**Additional context**
Numbers shown are not consistent across different videos. Smaller numbers are at the top. It is not clear if higher numbers correspond to higher quality. I suspect those are stream ids of some kind.

**Comment by GilgusMaximus** [comment]
Hi. So the reason behind this is the DashManifest file. It provides us with the data so FreeTube can stream the videos from YouTube in all kinds of qualities.
For videos, the player takes the height as quality indicator. Because this indicator is obviously missing for audio formats, it takes the bandwidth.

At the moment we have the following labels that we could display instead:
![image](https://user-images.githubusercontent.com/34301369/95012247-62790b80-0637-11eb-83c3-f045c74da890.png)


Neither of them is really that perfect to display. So for the moment the higher the number, the higher the bandwidth, the better the quality. And the difference in numbers is simply due to the date YouTube provides. There is nothing we can do about that.

But we are open to suggestions on how to change the display to make it more human-readable.

**Comment by oczkoisse** [comment]
Hi @GilgusMaximus. Thanks for the clarification about the numbers. I have the following suggestions:
- The numbers could be listed in descending order to be consistent with video quality selector menu where highest quality is at the top.
- I'm not sure if there are always 4 audio streams, so I think one could label each stream just based on the total number of audio streams available as follows:
    - 2 streams: Low, High
    - 3 streams: Low, Medium, High
    - 4 streams: Low, Medium, High, Highest
    - 5 streams: Low, Medium, High, Higher, Highest
    - 6 streams: Lowest, Low, Medium, High, Higher, Highest
    - 7 streams: Lowest, Lower, Low, Medium, High, Higher, Highest

The second point is really just an idea. I'll be interested to know what you think. And thanks for an amazing software!

**Comment by PrestonN** [comment]
Changing the order to have highest quality at the top is not an issue at all.  I'll get that sorted out here in a little bit.

With some small testing with a few videos, it seems like they're all consistent with having 4 options available, so it'd be easy to re-label them as "Low, Medium, High, etc.".  Only if the amount of streams varied would it become a problem, so I see no problem with this being changed.

**Comment by PrestonN** [comment]
This has been done.  You can download an automated build to use it or wait until the next release.

**Comment by oczkoisse** [comment]
Sounds good! I'll try the automated build when I get some time. Thanks for the quick response.
