### ISSUE TITLE
[Feature Request]: Show subscription cache even if the RSS subscription video list failed to fetch/load

### ISSUE THREAD

**Issue by ArthurKun21** [FreeTubeApp/FreeTube#5754]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Few days ago when Google performed IP Block for users who uses RSS for loading videos, it also removed the subscription video list cache in Freetube

### Proposed Solution

Make it similar to the error when loading a YouTube channel(s) but could not load any videos on it.

It shows the YouTube Channel(s) on top with the text: `could not load from the following channel(s)` but instead `could not fetch/load subscription videos due to RSS failed to load`

### Alternatives Considered

None

### Issue Labels

ease of use improvement, improvement to existing feature

### Additional Information

This feature request is in tandem with #5749 

At the moment I have already reset my router and have gotten new IP, so I won't be able to check the fix(when it is available) and check if the issue still persist with the RSS not loading and still retaining the subscription cache

**Comment by absidue** [comment]
@ArthurKun21 Could you please open a bug report for this instead?

As FreeTube has no handling for that error from YouTube it treats it the same as the channel having no videos (and tbf to the code the response contained no videos) and overwrites the existing list of videos in the cache with an empty list. So it's a lot more than just not showing something, because with the way the code currently works there is nothing to show because it got rid of the cached data, which is why I would consider it a bug.
