### ISSUE TITLE
Audio sync

### ISSUE THREAD

**Issue by postacik** [FreeTubeApp/FreeTube#576]
Hi,
I'm using Galaxy Buds+ earbuds on Windows and it has about 150 ms audio lag like all other true wireless (TWS) bluetooth earbuds while watching videos on Windows. The audio lag is compensated by the applications on my Samsung phone so the problem is only on Windows.

I'm currently using the following Chrome plugin to overcome this issue:

https://chrome.google.com/webstore/detail/youtube-audiovideo-sync/mknmhikmjljhpccebpnplhicmcfjkgbk

Can it be possible to integrate this functionality into FreeTube?

**Comment by PrestonN** [comment]
This is a pretty small edge case and the possible solutions don't seem to be very clean.

The extension you shared is open source, so it's possible to learn a little bit more about what they're doing.  It looks like they're loading a separate audio source and playing that instead of the audio within the video.

It's technically possible for us to do this as well, though the process of making this happen could become very messy code wise.  We'd have to account for many different things such as the buffering of 2 separate stream, playback speeds along with keeping them properly in sync.  It's doable but it would be a ton of effort to get right and even then there might be some issues with it.

Just out of curiosity, if you attempted to watch a YouTube video within VLC, would that solve your issue?  We're planning to eventually allow you to watch videos in an external player and if that works then I'd feel much more comfortable with moving forward with that solution than to try and add a delay ourselves.

**Comment by postacik** [comment]
VLC has built in audio sync but this solution would not be practical since you have to press the +/- audio sync shortcut keys each time you open a video with VLC.

And it would ruin the comfort of using FreeTube.
