### ISSUE TITLE
[Feature Request]: Playback at 432 Hz Frequency (0.981818x speed)

### ISSUE THREAD

**Issue by CubedApple** [FreeTubeApp/FreeTube#5761]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I am trying to move away from the industry standard 440 Hz Frequency audio/music :)

### Proposed Solution

Hi,

I am a regular user of Freetube on Linux (and Windows).

Can you please add an option for a default playback speed of 0.981818x ?

(I believe this is the correct maths according to this VLC adjustment: https://roelsworld.eu/432-tuning/real-time-auto-pitching-video-player/)

This way, I can hear my audio at 432 Hz instead of the standard 440 Hz. I would love to listen to music and hear audio in the 432 Hz frequency.

Regards,
T.

### Alternatives Considered

- Playback speed option for 0.981818x speed on the main video window
- Playback speed option by 0.981818x speed default in the settings

### Issue Labels

improvement to existing feature, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is too niche of an usecase to add to FT. People generally dont interact in the way you are proposing. Closing as i dont see this happening.

**Comment by jspast** [comment]
This can be covered by a more general approach for pitch manipulation (#1850). Anyway, you can use an external player for that, like the VLC you mentioned.

**Comment by CubedApple** [comment]
Thank you both for your feedback. As I understand, it would be as simple as adding a playback speed option of 0.981818x Speed. I would very much appreciate if this could still be implemented, even if hidden in the back settings.

**Comment by jspast** [comment]
Actually, it's not so simple. FreeTube's (and basically every video player's) playback speed selector is not technically just a playback rate setting. It also corrects the pitch so that the perceived frequency doesn't change (e.g. a music recording tuned A4 440Hz will still sound A4 440Hz if you select 2x, even though you could think it should sound A4 880Hz). That is the expected behavior in most cases, as you wouldn't want to change someone's voice when speeding up a podcast, for example. 

So an acceptable solution for this type of use case would be to add a way to change the pitch (separated from the speed) AND a way to use a custom value (extremely precise!) for both speed and pitch. It would be great if it could also expose the possibility of not correcting the pitch when changing the speed, by linking both settings, just like NewPipe's implementation.

As you can see, it's not simple. But I'm also interested in those features, so maybe I can take a look in the future to see how much of an effort it would be.

**Comment by CubedApple** [comment]
Thank you for the clarification and forgive my ignorance in the matter. That makes perfect sense, given the pitch is corrected too. Hmmm in that case, it would have to be a separate feature as you mentioned. 

Anyway, thanks for taking the time. Will keep an eye out on this :)

**Comment by CubedApple** [comment]
In addition, the way I have it on VLC, is the "Enable time-stretching audio" in the settings is disabled, while I changed the default playback speed is 0.981818x. This slows the playback speed without correcting the pitch, hence 432Hz pitch is attained. I was just following the link I mentioned in my Original Post, so maybe that would help too.
