### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [FreeTubeApp/FreeTube#578]

**Comment by Hiers** [comment]
No one here can decide whether a package will go to Arch's official repositories, that decision is made by Arch's maintainers and TUs alone. We can only have the AUR packages for ease of use. You could always comment on the AUR package about your problems and a fix. I don't have anything to say in that regard, as the AUR package builds and installs without errors. If you haven't, you could install it manually through makepkg to make sure it isn't a problem with the AUR helper you are using.

**Comment by BL4CKH47H4CK3R** [comment]
I didn't told to package and request arch maintainers to officially add freetube arch builds. Who needs to wait for authorization? As like the freetube deb build is not authorized by the debian but can be installed locally the same will be applicable for Arch builds.

Now coming to AUR, I know what I have said. Check yourself first that which build you are using I am telling about 0.8.0 builds not about 0.7.3. And you have installed 0.7.3 which is called `freetube-bin` and which has the needed permission as it should.

Note : I am one of the ArcoLinux developers & I know very well how to handle errors and build packages.

I am taking about new releases 0.8.0 not about 0.7.3 (Hope you understand)

Thanks for understating !

**Comment by Hiers** [comment]
I'm sorry, I misunderstood. An Arch package for each build of Freetube seemed unnecessary because a git AUR package already exists, but if it's not working or you don't want to have to compile it from scratch, it would be a good addition.

Back again to the AUR, I _was_ talking about the `freetube` package, which is for the 0.8.0 version. The permissions for chrome-sandbox are the same regardless of installation method, and the PKGBUILD does not have anything in it that changes its permissions. If 755 isn't working, I can ask for the permissions to be changed to 4755
