### ISSUE TITLE
Youtube Chapters support

### ISSUE THREAD

**Issue by paulpopus** [FreeTubeApp/FreeTube#579]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Some videos, especially podcasts and documentaries will have chapters set up in the video that act like timestamps for the content. [Google's explanation](https://support.google.com/youtube/answer/9884579?hl=en-GB)

I'm not sure if this is technically possible but it would be nice to see as it's a great UX improvement.

**Describe the solution you'd like to see implemented**
Support for chapters.

**Describe alternatives you've considered**
n/a

**Screenshots**
[Video showing how it works](https://www.youtube.com/watch?v=b1Fo_M_tj6w&feature=emb_title), if you hover over the progress bar you can see the different chapters setup.

**Additional context**
n/a

**Comment by GilgusMaximus** [comment]
Hi. So this feature is definitely a good idea, however the practical implementation could become tricky. It is a bit related to #143 as there aren't big projects getting this data from YouTube without the API, as far as I know. 

So some initial research work has to be done in order to figure it out.

**Comment by mbirth** [comment]
YouTube chapters come purely from the video description which FreeTube is already gathering. Just parse them for timestamps at the beginning of a line and take the following text as the name of the chapter. Maybe strip non-letters from the beginning, as some people use "01:23 - Chapter" (and variations) while others use "01:23 Chapter".

![Screenshot 2020-11-01 at 21 13 33](https://user-images.githubusercontent.com/130302/97813284-64120f80-1c87-11eb-859e-109f4b434cdb.png)

**Comment by GilgusMaximus** [comment]
Ah okay, that makes it a much easier task. 
We are open for PR's, however it still requires some more specific work than simply parsing out the time stamps.

Because we are displaying the preview thumbnails via [this ](https://github.com/GilgusMaximus/videojs-vtt-thumbnails-freetube) plugin for VideoJS, so on the one hand you'd have to add the chapter title to the plugin. On the other hand, it would probably help a lot to change the timeline in a similar way YouTube is doing it. So leaving a small space between chapters and making the line of the currently selected chapter larger (however the larger is debatable).  

Because this is quite a lot to do, and we are currently in a major feature development break, this won't come soon. Just as an idea, but this could be built as a community based PR. So one person starts adding the parsing of the description, another person, who might be experienced with VideoJS plugins adds the captions and the timeline changes.

**Comment by paulpopus** [comment]
Thanks for the comments, I'm really keen to learn Electron.js so I am counting on being able to put some time on this project soon

**Comment by GilgusMaximus** [comment]
Great to hear. If you want to get assigned to this task when you are ready, just leave a comment stating that :)

However this is mostly not Electron.js but NodeJs and plain Javascript. But these things are still relevant for Electron.js in the long run

**Comment by offset-torque** [comment]
I think I should add my comment to this one year old issue instead of opening a new one.

**Context:** Chapter support is important for Freetube because chapter usage is becoming even more widespread, especially in tutorials and music compilation videos.

@GilgusMaximus wrote this as the main obstacle for implementation:
> Because we are displaying the preview thumbnails via this plugin for VideoJS, so on the one hand you'd have to add the chapter title to the plugin. On the other hand, it would probably help a lot to change the timeline in a similar way YouTube is doing it.

**MY STATEMENT:**
We don't need thumbnail/timeline changes to implement basic chapter functionality
Parsing chapter timestamps and jumping between them with a keyboard shortcut is enough

### **Example:**
Assume I am watching a song compilation video. I want to skip to next song.

**In my current browser (Firefox+Enhancer for Youtube addon):**
I hit `Ctrl+Right Arrow` and jump to next song.

**In Freetube:**
- I have to move mouse over video to see current time in video - 19:42 for example
- I have to scroll down to description
- Check the timestamps to calculate which chapter currently I am in (because timestamps show the beginning of the chapter - like 18:26)
- Click on the next chapter's timestamp
- Repeat this procedure if I want to skip other songs

**All this effort can be replaced with a simple keyboard shortcut.**

**Offered solution:**
Freetube parses timestamps from the description
If user hits the relevant shortcut, Freetube jumps to previous/next timestamp depending on user's current position
