### ISSUE TITLE
[Feature Request]: Delete watch history from unsubscribed channels

### ISSUE THREAD

**Issue by Cyber-Syntax** [FreeTubeApp/FreeTube#5844]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

I just want to delete unsubscribed channels (e.g., movie trailers, trends) watch history but keep subscribed channels(e.g CS50 ). 

### Proposed Solution

It would be great if you could create a button to "Remove Unsubscribed Channels Watch History" next to "Remove Watch History". 

### Alternatives Considered

It would be great to automate this, but isn't necessary to be a priority for now. Maybe, if it's going to be possible, it will work with #2889.

### Issue Labels

ease of use improvement, new feature, new optional setting

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This is a niche usecase. The whole point of a watch history was to keep track of what you had watched. 

This kind of history customisation seems like something that would be better handled by some external tool that compares the two databases and removes the records that you don't want anymore.

Therefore i will be closing this issue.

**Comment by Nobylo** [comment]
@Cyber-Syntax If you're still looking to do this, you can use the `mark` feature in notepad++ to highlight all videos from specific channels inside exported history.db files. Make sure `bookmark line` is checked
![image](https://github.com/user-attachments/assets/b6d8759e-f5aa-400a-9f27-76b2e054a599)
You can then go to the `search > bookmarks` dropdown and do several operations to all the marked video entries (remove bookmarked for your usecase.)
![image](https://github.com/user-attachments/assets/0622e834-06b4-4ab0-98cd-2e9ccea605eb)
The edited file should import without issue. I think(?) Freetube stacks new imports on top of the current file so you'll need to clear your history then re-import it. Make sure to keep backups!

-------------
> ...seems like something that would be better handled by some external tool...

@efb4f5ff-1298-471a-8973-3d47447115dc since you brought this up, what is this "some external tool"? Does it even exist? I am currently using regex for the complicated stuff and would prefer anything else.
