### ISSUE TITLE
[Feature Request]: Limit search to channels in active profile

### ISSUE THREAD

**Issue by m3thm4th** [FreeTubeApp/FreeTube#5850]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Global search can be dispersive

### Proposed Solution

Allow option to only show search results from channels in the active profile, by sending the search query only to those channels

### Alternatives Considered

.

### Issue Labels

new feature

**Comment by absidue** [comment]
As YouTube doesn't have this feature, something like that would have to be built on top of the existing YouTube search and would come with major limitations.

Here are the two potential ways of implementing it:
1. Use the normal global search and before showing the results to the user filter out anything that is not from one of the channels in the currently active profile. **Downsides**: Unless the channels you are subscribed to have very unique video titles, you will probably be shown empty search results and have to click load more lots of times before you get anything.
2. Use the in-channel search (the search box that you see when you visit a specific channel) and send a request to YouTube for each channel. **Downsides**: YouTube's in-channel search doesn't support search filters and because we would have to send a request for each channel it would have to be limited to profiles with only a small number of subscriptions so that you don't get ratelimited by YouTube.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing this one as i think there are too many downsides.

**Comment by bakaufmann** [comment]
I understand that this feature request has already been closed and hope it is ok that I'm commenting here nonetheless. I just wanted to remark, that I too would find this feature extremely useful and agree with @m3thm4th that @absidue|s second proposal seems to me like a good way to approach this.
