### ISSUE TITLE
[Bug] Default quality setting does not work

### ISSUE THREAD

**Issue by ThatIsAPseudo** [FreeTubeApp/FreeTube#595]
**Behavior of the program**
My default quality setting is set to 240p with Dash player, but videos keep loading in 720/1080p.

**Expected behavior**
The videos play in 240p

**To Reproduce**
1. Go to 'Settings'
2. Select '240p' in the 'Default Quality' dropdown list
3. Play any video
4. Notice that quality is 1080p

**Desktop :**
 - OS: macOS 
 - OS Version: Big Sur Beta 9 (20A5384c)
 - FreeTube version: 0.8.0

**Comment by arrowgent** [comment]
v 0.8.0

linux x64

720p selected as default
same issue, video will select 1080p automatically

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
It still persists in the current version of FreeTube.
Win 10
1909

**Comment by esotericDisciple** [comment]
It's the opposite for me...it feels like the player is locked on 'auto' mode

**Comment by sysdbugfactory** [comment]
Same issue here, default is ignored and freetube plays video in the highest possible setting making the computer hot, slow and the video stuttering.

Using v0.11.2 Beta under manjaro linux

**Comment by ThatIsAPseudo** [comment]
Note : With Legacy player, video plays by default at 360p, not the highest value that is 720p

**Comment by LosEagle** [comment]
> It's the opposite for me...it feels like the player is locked on 'auto' mode

Same here. I'd prefer some buffering over player randomly switching to 240p all the time to present me with unwatchable blurry video no matter how many times I click HD resolutions.

**Comment by tugcanolgun** [comment]
> It's the opposite for me...it feels like the player is locked on 'auto' mode

This is a problem for me too. Sometimes the video switches to 240p no matter what I do. It makes some videos unwatchable.

**Comment by spectrumgamer75** [comment]
Same issue here too, it goes way up to 1080p even though have set 360p in settings. Any fix?

**Comment by EvilGremlin** [comment]
Same, it's doing auto stuff despite set 1080, nor setting quality in player really works. I expect immediate change of format when i say so.

**Comment by nils-van-zuijlen** [comment]
Same, videos playing as in auto (144p for me) in Dash formats, seems to work in Legacy formats (I get higher resolutions, and buffering)

Linux, AUR package
FreeTube 0.12

**Comment by PrestonN** [comment]
Hey all. I know that this has been problematic for a while. I'd like to try to explain a little bit about what's going on.

Legacy formats handle streams much differently than DASH. By this, I mean that legacy formats have physically different URLs for each quality and it's very easy to set a quality level and have it stay there. There isn't any logic for "auto" quality either so that doesn't cause a problem.

DASH formats handle everything with a single URL stream, so the logic of changing quality is vastly different. Up to this point, we've been using an officially recommended module from video.js to handle this quality change. As a lot of you have noticed, this hasn't been working very well. The module also hasn't been updated in several years so that means it's unlikely to get any fixes done to it.

I've just pushed a custom solution to the nightly builds that uses my own logic for handling the quality changes for everything. Please give this a download and let me know how well this works versus the live release.

Some things I've noticed with this change. Video.js doesn't like it when the quality gets changed back and forth very fast, so it'll delay your quality change if you do this. Changing your quality may take a second or two to change, but this seems to have fixed the auto changing problem from my initial testing. Looking forward to hear everyone's thoughts on this change.

**Comment by fabianski7** [comment]
it's working fine for me. 
the only problem so far is this

![ksnip_tmp_rRNZor](https://user-images.githubusercontent.com/47755037/111005383-9bee3980-8382-11eb-82ed-0930f4083dc0.png)

**Comment by fabianski7** [comment]
Also: I don't remember how it was before, but I can't change the quality of the lives

**Comment by EvilGremlin** [comment]
@PrestonN ImprovedTube manage to do resolution right, maybe peek at their sources?

**Comment by EvilGremlin** [comment]
@PrestonN Your fix seems to be working, but whenb switching back and forth it plays a lot more of cached low-quality than it should. Like delay is based on bytes, not time.

**Comment by Fricsion** [comment]
It doesn't work on my macOS Big Sur either. I set 240p as the default quality to save data -> videos play in 1080p regardless.

**Comment by fabianski7** [comment]
with version 0.13.0,this bug is definitely back

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
doesn't occur on v0.13.0-nightly-845 Beta

**Comment by fabianski7** [comment]
ok, to be more specific: it is not working if invidious proxy is enabled. 
[The quality selector is not even displayed](https://user-images.githubusercontent.com/47755037/119262928-7e342080-bbcc-11eb-8378-4af91bb3ff17.png) (and I am not using legacy format).

**Comment by jcartner-young** [comment]
I have also had the problem with doubled-up resolutions in the quality list.

I also have an issue with the 'Default Quality' not being logically honoured - I have 1080p selected as default quality, but videos are playing at 360p.

Could this be caused by the stream not having a 1080p source and the software failing to set the resolution?

I think it should default to the highest available which is closest to the selected default - ie, If I have 1080p selected as default, it should select 720p if 1080p is not available, 480p if 720p is also unavailable, 360p if 480p is also unavailable, and so on.
I have Legacy Formats enabled to improve decoding speed on my non-cutting-edge hardware - Not 100% sure how this would affect this bug, though.

**Comment by hollunder** [comment]
> Same result, but I'm not using DASH formats.
> 
> I have an issue with the 'Default Quality' not being logically honoured - I have 1080p selected as default quality, but videos are playing at 360p.
> 
> Could this be caused by the stream not having a 1080p source and the software failing to set the resolution?

Yes, this seems to be the problem.
I have the default set to 1080p and that works fine, unless there is no 1080p available.
If, as is often the case for me, the video has 720p and 360p available, then the video is played back in 360p.
I would expect it to be played in 720p, as this is the next lower resolution.

**Comment by toby63** [comment]
In recent versions (I use a relatively new commit (1 or 2 weeks old)), some things seem to be working better:
1. Dash as default setting: Default setting is respected and highest available quality option (<=chosen maximum) is used.
2. Legacy as default setting: Default setting is respected and highest available quality option (<=chosen maximum)  is used.

But when I use Dash as default and a video only provides lets say 360p and I want something higher, then I would expect FreeTube to automatically fall back to legacy format and choose e.g. 720p, if available.
Even when I manually switch to legacy format, I would expect the highest option (<=chosen maximum) to be used, but instead it always uses 360p and I have to manually click on 720p.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Reopening because https://github.com/FreeTubeApp/FreeTube/pull/3278 did only partially address this issue

**Comment by nils-van-zuijlen** [comment]
Not stale, still happened to me yesterday by just refreshing the interface (Ctrl+R).

**Comment by nils-van-zuijlen** [comment]
PS: https://fvsch.com/stale-bots

**Comment by nils-van-zuijlen** [comment]
Now at 23 comments and 16 stale comments/reactions. Please consider deactivating that constant periodic spam.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> Reopening because #3278 did only partially address this issue

My bad, this is fixed.



> In recent versions (I use a relatively new commit (1 or 2 weeks old)), some things seem to be working better:
> 
>     1. Dash as default setting: Default setting is respected and highest available quality option (<=chosen maximum) is used.
> 
>     2. Legacy as default setting: Default setting is respected and highest available quality option (<=chosen maximum)  is used.
> 
> 
> But when I use Dash as default and a video only provides lets say 360p and I want something higher, then I would expect FreeTube to automatically fall back to legacy format and choose e.g. 720p, if available. Even when I manually switch to legacy format, I would expect the highest option (<=chosen maximum) to be used, but instead it always uses 360p and I have to manually click on 720p.

@toby63 could u open a feature request for this
