### ISSUE TITLE
[Feature Request]: Move the progress bar to the bottom of the video player

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#5955]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

With Freetube's new video player the progress bar and video settings are now slightly above the bottom, making them more likely to obstruct parts of videos and also just not looking as nice.

![freetubescreenshot](https://github.com/user-attachments/assets/d8cf74d5-d5e3-45d1-9085-57f3a15e7438)

### Proposed Solution

Move the progress bar and video settings all the way to the bottom, where they were with the old video player.

### Alternatives Considered

n/a

### Issue Labels

visual improvement

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
This was the same with the old player and will not be changed in the new player

**Comment by chrrybmb64** [comment]
> This was the same with the old player

No, it's not the same as the old player. Maybe I should have phrased it better, I'm not just talking about the progress bar, I'm taking about the whole player menu. Here's a comparison.

![freetube2](https://github.com/user-attachments/assets/f1d67a0a-acc5-4bda-aeaf-e77368dc8de8)

In the new player, the menu should be where the white box is, as it was in 0.21.3.

**Comment by absidue** [comment]
As @efb4f5ff-1298-471a-8973-3d47447115dc said, it's a new player so it looks slightly different and we won't be changing back to the old player.

**Comment by chrrybmb64** [comment]
I'm not asking you to go back to the old player, I'm asking you to modify the new one. Is that not possible?

**Comment by absidue** [comment]
Theoretically it would be possible, but would likely break other parts of the UI (e.g. subtitles), make the player worse on touchscreens and mobile devices in the same way that the old one was. It would also be a major deviation from upstream, so resulting in more work on our side to update the modifications any time things change upstream, just a reminder that FreeTube had customized the previous player so much that it made it impossible to update to any newer version of video.js. So we definitely want to avoid doing unnecessary modifications, just because users refuse to get used to the new UI.

**Comment by chrrybmb64** [comment]
Fair enough

**Comment by jspast** [comment]
This is a duplicate of #5647 and unfortunately the main issue with the new player's UI. Was also [pointed out in the Release Candidate discussion](https://github.com/FreeTubeApp/FreeTube/discussions/5881#discussioncomment-10991235).

Maybe we should report upstream.

**Comment by absidue** [comment]
It is not an issue and please don't waste the shaka-player developers time with this, as they definitely don't want to redesign their entire UI just because a few FreeTube users refuse to accept that things change over time.

**Comment by kommunarr** [comment]
For discussion on how Shaka handles it, spacing appears to be ~25px taller than YT's on desktop view, which is not much in the span of things. You could argue that it should be a fixed height like YT instead of a dynamic `padding-bottom: 2.5%` to better accommodate above-average viewport sizes, and maybe change that base desktop number in doing so, but I don't think it is that big of a deal. It might be being remarked on a bit because Shaka does not have the icons fill the height of the allocated container space (which I would consider to be a minor visual area for improvement), and it makes it stand out more visually compared to the previous video player.

**Comment by suy** [comment]
Let me please start my comment clarifying that it's totally understandable if Freetube can't implement this on its own due to library limitations. I'm more an app developer than a library developer, and my understanding is that the project is a lot of unpaid work as a volunteer, so I'm well aware of time/interest limitations (and I appreciate the whole project existing).

> It is not an issue and please don't waste the shaka-player developers time with this, as they definitely don't want to redesign their entire UI just because a few FreeTube users refuse to accept that things change over time.

This, however, and with all due respect, I'm pretty confident that is a wrong point of view. I'm not used to the old UI because I never used it. I've always used Freetube the current way, and the controls obscuring the playback has been problematic a few times to me, without knowing how it was in the past.

Today I've searched the issues because of #5951 (the big play button) was just too obtrusive for me. I've also found this issue because someone has found the controls obtrusive in some way, and I think it's not a matter of taste: they are objectively blocking more video area than before.

I've filled #6050 to ask for the possibility of the controls be less in the way in the cases where it might matter, but if that's not possible to do, I don't see why it would not be possible to politely ask for a feature request on the player library if that can reduce the surface area that gets blocked meanwhile. Perhaps it doesn't happen at all (again, volunteer work, lack of resources, etc.), but I don't see the reasoning for discouraging users to try to solve an objective issue by reporting this on the right place.

Thank you.

**Comment by absidue** [comment]
The only people in the world that think the shaka-player UI is bad are FreeTube users, so please don't flood shaka-players issue tracker with requests like this.

**Comment by jspast** [comment]
> For discussion on how Shaka handles it, spacing appears to be ~25px taller than YT's on desktop view, which is not much in the span of things. You could argue that it should be a fixed height like YT instead of a dynamic `padding-bottom: 2.5%` to better accommodate above-average viewport sizes, and maybe change that base desktop number in doing so, but I don't think it is that big of a deal. It might be being remarked on a bit because Shaka does not have the icons fill the height of the allocated container space (which I would consider to be a minor visual area for improvement), and it makes it stand out more visually compared to the previous video player.

Thanks so much for your input here. Following your findings, I was able to experiment with the CSS on DevTools and find exactly what we could change to make the bar fit better. This is what shaka-player does by default:

![image](https://github.com/user-attachments/assets/a22fa728-7589-4a40-87bf-9d3b2e65f19f)

Modifying it to 'padding: 0 0 10px', where 10 is just an arbitrary number to test, makes the player behaves as we normally expect it should, given it is what YouTube and basically every video focused platform does. With the little testing I did, nothing seems to break, but the position of the settings menus do change relative to the bar position.

Next, I would like to research what was shaka-player reasoning behind this choice to better understand what could be done.

**Comment by absidue** [comment]
> Next, I would like to research what was shaka-player reasoning behind this choice to better understand what could be done.

As shaka-player is made by Google they based it on the default Chromium player UI and designed it to work on desktop, mobile devices and TVs.

**Comment by jspast** [comment]
> > Next, I would like to research what was shaka-player reasoning behind this choice to better understand what could be done.
> 
> As shaka-player is made by Google they based it on the default Chromium player UI and designed it to work on desktop, mobile devices and TVs.

So I did some research and [you are correct](https://github.com/shaka-project/shaka-player/commit/e9994730c07a9eae2635ed2c0e26c1844e8b1330). The thing is: I couldn't reproduce the same behavior on the current version Chromium player UI, so maybe shaka-player default UI is actually outdated and all of this could be "fixed" upstream.

However, I also went through their official documentation where they mention [some UI themes](https://github.com/lucksy/shaka-player-themes) and a YouTube theme caught my attention. Look what it does:

![image](https://github.com/user-attachments/assets/1f34f24f-c938-486d-b403-8363b7d45f3e)
_Moving bottom control to bottom_

Finally, I was able to implement this on FreeTube with just 2 lines (also changed the width to match). It's important to say that the buttons clickable area do not change, so it should not affect accessibility other than the fact that the buttons are overall a bit closer to the screen border on full-screen.

Before
![image](https://github.com/user-attachments/assets/f33148ba-d998-47a6-a449-5622213cabfe)
After
![image](https://github.com/user-attachments/assets/f0655320-1eda-4efa-915f-4fb8f7a73d52)

I could open a PR if this sounds good.

The only remaining question is what to do with the settings menus. By default, they are 30px from the bottom, so their position is not even consistent with the bar's default 2.5% padding. There is already an issue somewhat related to that: #6035.

Sorry such a long comment.
