### ISSUE TITLE
60FPS and 1080p unavailable for some videos

### ISSUE THREAD

**Issue by DanielJenkyn** [FreeTubeApp/FreeTube#60]
First of all great job so far, been looking for a program like this for a while 👏 

**Issue:**

Videos that are 60fps and/or 1080p on youtube.com do not have the same quality options on freetube.

**Example**

<img width="640" alt="screen shot 2018-03-18 at 10 53 18" src="https://user-images.githubusercontent.com/11617329/37565156-c36c2280-2a9b-11e8-81e0-3ef00a3eb07e.png">

![screen shot 2018-03-18 at 10 53 57](https://user-images.githubusercontent.com/11617329/37565157-c38e3406-2a9b-11e8-8510-ef2813dab774.png)

I actually know little about javascript, or even web development but fixing the 1080p issue maybe has something to do with the `function changeQuality(videoHtml, qualityType, isEmbed = false)`or  in `player.js`
or just add the option in `player.html` there doesn't seem to be any documentation on why 1080p is unavailable.

**Comment by dimqua** [comment]
I think 1080p videos are not supported at all.

**Comment by PrestonN** [comment]
This is obviously something that I've wanted to do and I won't ever consider FreeTube stable until this is fixed.  The reason why 1080p isn't supported yet is because of how YouTube organizes their videos.

Any quality type 1080p and up separates the video and audio into 2 different files.  This means that the video player has to sync up the 2 files in order for the user to view them properly.  The 720p videos and below do not do this.

It is very possible to combine them, but the issue has been being able to do it automatically.  Normally these types of videos provide some sort of manifest file that directs the player how to combine them, but youtube-dl does not provide this file and I have yet to find a good solution to create this manifest file.

I've been looking at different options and I'm trying to find to find the solution that works the best.  I could probably hack together a video and audio tag and force them to sync together but I don't think I'd be too proud of that.  Plus at that point I'd have to rework all of the controls to make sure that it effects both streams whenever the user does something.  It would be very messy at the end of the day.

The lack of documentation has been my fault.  I shouldn't have assumed this but I figured that people were aware of HookTube having the exact same issue and were alright with it.  Yeah it'll be nice if I can get it working but I think maxing out at 720p is good enough until I can find a proper solution.

I'll keep you updated on this though.  I'm probably going to focus more on the client itself than trying to get this working.  I understand that it's very important to a lot of people though and will continue making efforts to getting this working.

**Comment by DanielJenkyn** [comment]
Right I see, I wasn't aware this was the case. Well thanks for the additional info and at least this ticket can serve as some form of documentation that people can refer to.

**Comment by PrestonN** [comment]
Hey there.  I just wanted to give an update on this, because I know that this feature is very important to users as well as potential users.

I plan on making a serious attempt at this when I get the next release published.  I haven't had much luck in finding anything that solves a similar issue so I'll have to get a little creative with it.  I mentioned it being messy, but my current plan is to make a custom player with custom controls that sync the video and audio together.  I've put some thought into it and I believe that I can get it into a manageable state.  FreeTube will still use the default HTML5 player, the only difference that you will see is that the interface will be different.

Doing this actually opens up a few things.  To start, FreeTube will have a unique interface for it's video player.  I'll be able to add things directly to the player's interface that I couldn't do before (such as playback speed and video quality).  The last question is then how do we want the video interface to look like?  I guess the current plan is to make something similar to how YouTube's player looks, but if anyone has any ideas for themes then feel free to let me know.  Maybe the theme could be interchangeable in the future?

Hopefully this gets people excited.  I'm interested in how the end result will be when I'm finished.  I figured a few people would like to know that it should be coming soon. :)

**Comment by oleteacher** [comment]
Not sure if this will help, but been using Plyr for some time now with great results. Maybe it will be of use to you:

https://github.com/sampotts/plyr

**Comment by PrestonN** [comment]
Thanks for the suggestion @oleteacher, I'll see if that will work with what I'm wanting to do.

While the player shows that it supports YouTube videos, this typically means that the player embeds the YouTube player into their own, which would defeat one of the main goals of FreeTube.  I've seen several players do it this way when I've searched for solutions and this is not the correct way for this type of application to do this.  Any sort of YouTube analytics would come along with it which would ruin any sort of privacy aspect that FreeTube has.

A proper solution will need the player to (as an example) accept a DASH video URL as well as a DASH audio URL at the same time and sync these 2 together without a manifest file.  I've searched quite a bit and I have yet to find a solution that does this.  Realistically this seems like the best way to support higher qualities while still keeping the user as private as possible.  I would not want to implement anything that doesn't do something similar to this.  My best solution seems to be to make a custom player that does this.

I only glanced at Plyr for a little bit, so if I'm wrong and they do support this then please let me know.

**Comment by oleteacher** [comment]
> I only glanced at Plyr for a little bit, so if I'm wrong and they do support this then please let me know.

I mainly brought it up in case there were some inter workings that FreeTube may benefit from:)

**Comment by PrestonN** [comment]
Good new on this, a developer on [Reddit](https://www.reddit.com/r/privacy/comments/903pxf/hooktube_is_no_more_so_i_made_a_similar_site/) has started work on his own YouTube app which included some custom work on 1080p+ video synchronizing.  He has sent me his code along with some notes and I should be able to port this over to FreeTube very soon.  It may even be possible to have this ready before the next release.  If you every get the chance, head over to his [GitHub](https://github.com/cloudrac3r/cadencegq) page and tell him thanks.  This saves me a lot of time. :)

**Comment by tiotrom** [comment]
Any updates on the implementation?

**Comment by PrestonN** [comment]
Closing as 1080p+ options have now been implemented.  I will have more information on the matter when the release blog is available.  Still no ETA on when that will be but 1080p is finished and ready for release.
