### ISSUE TITLE
Some videos displaying quality at a different resolution from what is expected

### ISSUE THREAD

**Issue by Hiers** [FreeTubeApp/FreeTube#604]
**Behavior of the program**
Some videos displaying quality at a different resolution from what is expected, e.g. 960p instead of 1080p.

**Expected behavior**
Videos showing the same resolutions as their YouTube counterpart, at least up to 1080p.

**To Reproduce**
This video is confirmed to display this error: https://www.youtube.com/watch?v=V0JuW6x8lsw

**Desktop:**
 - OS: Artix
 - OS Version: N/A
 - FreeTube version: N/A(commit 971)

**Comment by GilgusMaximus** [comment]
That is not a bug. It is expected behavior. Because the video has black bars, YouTube does not account it for 1080 pixels height but rather 960 pixels. And because it doesn't have have a quality label attached, the quality label is generated from the provided video height. 

I'll think about a solution. Because simply taking the width will not solve this, as YouTube might not account videos with black bars on the left/right for the same resolutions.

**Comment by PrestonN** [comment]
The only thing we could realistically do here is to arbitrarily label these videos as 1080p, 720p, etc. depending on what the closest is, though that isn't really an accurate representation of what quality you're watching any more.  There wouldn't be a difference in quality if we rename them, it would more so be for consistency reasons.  If people prefer we do that then we can change it but as Gilgus said, this isn't really a bug.

**Comment by GilgusMaximus** [comment]
We could go like this: Quality label -if not available> Height -If not standard> width

**Comment by arrowgent** [comment]
confirm, the video is 1920x960

thereby, freetube is reporting it correctly
its youtube in the browser which is reporting it incorrectly
although youtube is very wierd about what resolutions it allows (transcodes DOWN to)

nice finding.  not sure that freetube should need to fix it because its not really a bug.

**Comment by PrestonN** [comment]
I think for now we'll just keep it the way it is.  I can't think of good reason to change this besides simply being consistent with what others expect.  We're technically correct with what we're displaying so changing it would just make it incorrect.
