### ISSUE TITLE
[Feature Request]: Video controls which don't obscure the video when paused

### ISSUE THREAD

**Issue by suy** [FreeTubeApp/FreeTube#6050]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

There are a few occasions where pausing the video is the only way to see something relevant about the it:

* Something is briefly flashed (a clarification, a footnote, an Easter egg).
* Something very long, like a quote, or code, or terminal output, that can't be read in full while the video is playing.
* Other.

The playback controls (play/pause, progress, volume, etc.) are covering the bottom of the video frame. They go away when playing, but not when the video is paused.

Additionally, if what you need to watch needs pausing/unpausing (e.g. looking for artifacts, anything in motion, etc.), repeatedly pausing and unpausing the video will keep the controls fading in and fading out, but always partially shown and always obstructing the bottom of the video. The new player might have made this a bit worse by having it extra space at the bottom (see #5955).

### Proposed Solution

Allow the option to place controls entirely outside the video frame, like other video players do, for example, VLC.

I suppose it would mean implementing at least part of the controls outside the video player, then toggle them off entirely, perhaps as an option if not all the controls are fully reimplemented in the new way. There should be space in the UI for this, as there already unused black margins around the video frame:

![freetube-obscuring-2](https://github.com/user-attachments/assets/fe813058-8edc-4d0d-a165-499b8fe98134)

### Alternatives Considered

There are a few alternatives that would probably require less work, but would be less ideal:

* Make sure that controls fade away when the video is paused, the same way they do fade out when the playback is resumed. Most players on mobile, where full-screen is almost the norm, do this (e.g. VLC and NewPipe on Android). This would not address entirely the issue of repeatedly pausing/unpausing, as the controls would keep fading in/out.
* Don't show the controls if the keyboard is used to pause/unpause or if nothing is hovering the video. This would allow still to pause the video without the controls showing, and still be able to repeatedly pause/unpause with the keyboard.

### Issue Labels

visual improvement

**Comment by absidue** [comment]
The proposed solution is not feasible as it would require creating a completely custom UI (may I remind you that we are volunteers with limited time and we do not have enough time to go wasting it on that) and also would result in the controls not appearing inside fullscreen mode, because they would be outside of the player. You are also using FreeTube maximised, but you have to keep in mind that not everyone does and FreeTube supports all sorts of window sizes, even mobile devices, so that extra space you are talking about is not there is most situations. There are actually even open issues about moving things like the format switching into the player, because their current position requires some people to scroll while watching the video, you would be asking for the opposite which would make that situation significantly worse.

The whole point of the controls showing up when you pause the video is so that you can use, sure you personally might not use FreeTube like that but making the controls much harder to access is a no-go. There are also people that use FreeTube with just a keyboard, screen readers or touchscreens so you cannot rely just on the mouse hovering over the video.

If you have any suggestions that don't require a massive amount of work or make the app unnecessarily harder to use, you are welcome to suggest them, but your current ones are not feasible.

**Comment by suy** [comment]
The proposed solution is just one idea, added there because the issue template steers you into writing it. The main deal of the feature request (at least in this case, in my opinion) is the problem description. I proposed that solution because, while I'm well aware that it might be the least likely to ever happen, it is also the one that seemed the most feature complete. Perhaps too much, though.

I'm not aware of the implementation details of the application and the video player library that it uses, but I considered that, perhaps, there is a slight chance that the controls can be implemented in the library in such a way that they could be rendered as a control that can be positioned elsewhere (perhaps not right now, but in the future, if someone would want to add the feature). That would require not that much work to position the controls on top of the video frame, or adjacent to it. But it's just an idea.

Let me also stress out that I've not suggested just one idea, as the issue template again steers you to propose more things, and I've proposed two. The controls fading away on pause is what Freetube already does when the video is playing, and what most video players do, so it seemed a good usability improvement that I assumed it would not be too time consuming to implement.

I don't understand the remark of "There are also people that use FreeTube with just a keyboard, screen readers or touchscreens so you cannot rely just on the mouse hovering over the video." I already mentioned using the keyboard to pause/unpause as a case where the controls could just not fade in, which would solve the issue. If the user has used the keyboard or other input method other than mouse/touch, there would be no need to show them, I think. Showing the controls on mouse hover is already what it happening right now when the video is playing. It's just not doing that when the video is pausing (and that's basically my feature request in a nutshell). For touch devices: as I said, most video players that I've tested this days (all except one) fade out the controls away when paused. They fade in when tapped the screen. So I see no issue.

Anyway, thanks for your time, and apologies if something was not clear (I'm not a native speaker after all), or I've used the feature request differently to what it was expected.

Cheers.

**Comment by geominorai** [comment]
Bumping this issue hopefully to bring in some new attention.

Shaka player's transparent seek bar shading definitely obscures content behind it that is not present on the official YouTube player:

![Image](https://github.com/user-attachments/assets/5c0c48a5-61e6-4db0-ab33-01a9b696f353)

![Image](https://github.com/user-attachments/assets/c646f707-510f-476e-a213-f60dd47c905c)

[Video Source](https://youtu.be/Pjm8yKr42RQ?t=105)

It is almost impossible to read the text at the bottom on FreeTube while paused, and in this example also impossible while watching the video since it is a fast scrolling ticker.

The two alternatives @suy proposed sound reasonable, especially when combined, since they do not involve creating an entirely new video player or distorting the existing layout.

The video controls already automatically hide themselves when the cursor is moved outside the video during playback.  (I personally do this quite often when not in full-screen mode because it hides too slowly by itself otherwise after clicking to start playback.)  Having the controls hide in the same way (moving the cursor out of the video area) while paused seems consistent with such user intention.  If the user wanted to see or use the controls again, one way or another they would have to move the cursor back into the video area to click anything (consistent with when the video is playing where controls are not visible, moving the mouse back in shows intention to bring them back into view).

**Comment by geominorai** [comment]
If the issue with the current suggestions is the need to avoid accidentally impacting existing normal user interactions, perhaps we could add a toggle for a minimalized playback seek bar via a clickable button in the unused space at the bottom like:

![Image](https://github.com/user-attachments/assets/45be3039-d247-4db3-8a4c-dff6f61a5047)

![Image](https://github.com/user-attachments/assets/3008c883-9b11-4272-b8b1-ce5429d6b99a)

`.shaka-scrim-container`'s background transparency was also reduced from 15% to 2% to match the reduced height of the bar.

The hide/fade-out controls when paused alternative suggestions from above could instead be used exclusively while in this minimized mode to avoid conflicts with the regular player controls.

---
SVG's placed inside `shaka-spacer` (taken from the official YouTube player during full-screen):
```svg
<svg height="100%" viewBox="0 0 24 24" width="100%"><path d="M7.41,8.59L12,13.17l4.59-4.58L18,10l-6,6l-6-6L7.41,8.59z" fill="#fff"></path></svg>
```
Flipped vertically and with added borders:
```svg
<svg width="100%" viewBox="0 0 24 24" height="100%" transform="matrix(1,0,0,-1,0,0)"><path fill="#fff" d="M7.41,8.59L12,13.17l4.59-4.58L18,10l-6,6l-6-6L7.41,8.59z" stroke="grey" stroke-width="1px"></path></svg>
```
