### ISSUE TITLE
[Bug]: In the subscription and playlists pages, unwatched videos does not show it's duration

### ISSUE THREAD

**Issue by BrunoSBorges** [FreeTubeApp/FreeTube#6058]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

Same as title.
Unwatched videos do not show it's duration, but watched videos does.

Search page and history page show the duration for both watched and unwatched videos correctly.

Example from the "watch later" playlist.
![image](https://github.com/user-attachments/assets/f739f7bc-f309-4d21-a056-202df0778b36)

obs:
Using the feature to "Mark as Watched" does nothing. It needs to have played the video for at least 1s to register it...

### Expected Behavior

Duration is always visible regardless of the watched status.

Example from the search page:
![image](https://github.com/user-attachments/assets/d8788198-a714-42ad-b10d-767a61b241f8)

### Issue Labels

visual bug

### FreeTube Version

v0.22.0 Beta

### Operating System Version

Windows 10 version 22H2

### Installation Method

.exe

### Primary API used

Local API

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
When you have lots of subscriptions FreeTube fetches the subscriptions from YouTube's RSS feeds, to avoid getting ratelimited. The RSS feeds don't have the video durations which is why you don't see them.

For videos that you have already watched FreeTube is able to show the duration that was saved into the watch history when you watched the video. As for the missing durations in playlists it sounds like you probably saved a video from the subscriptions page that didn't have a duration to the playlist, which is why it is missing there too.
