### ISSUE TITLE
[Feature Request]: Add a Web browser option 

### ISSUE THREAD

**Issue by Totallynotmwa** [FreeTubeApp/FreeTube#6124]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Because freetube is a electron app i want a version i can browse on my browser i dont really like electron that much.

### Proposed Solution

it can be browsed at any browser in url

### Alternatives Considered

you can use freetube inside of firefox

### Issue Labels

new feature, support for external software

**Comment by absidue** [comment]
FreeTube is not a separate website, it runs inside the Electron app, making a web version would require rewriting large chunks of it to use a client-server architecture. If you want a website I would recommend using Invidious and Piped instead.

**Comment by absidue** [comment]
Rewriting FreeTube to be like that and would come with the same problems that Invidious and Piped have such as requiring lots of expensive servers because you need to proxy everything through them (unlike in Electron where you can make requests directly from the app to YouTube, in normal web browsers that isn't possible because of CORS, so all the requests have to go through a server instead including the video and audio data) which amounts to many hundreds of terabytes of traffic each month and getting blocked by YouTube frequently (as in at least every 5 minutes).
