### ISSUE TITLE
[Bug]: Most videos won't play, API errors

### ISSUE THREAD

**Issue by Dublin1855** [FreeTubeApp/FreeTube#6127]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When opening a video, Errors appear and video does not play.  Most videos not playing with 3 errors given.   Local API Error: [UNPLAYABLE] Please sign in;    Invidious API Error: SyntaxError: Unexpected end of JSON input; Legacy formats are not available for this video;     This is occurring on approx. 75% of videos;   Have tried different Invidious servers (the list has gotten very short!);    Currently using version v0.22.0-RC-4923 Beta on a Mac.

### Expected Behavior

Videos should play without issue.

### Issue Labels

API issue, content not loading

### FreeTube Version

v0.22.0-RC-4923 Beta

### Operating System Version

macOS Sonoma 14.4.1

### Installation Method

.dmg

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.22.0-RC-4923 Beta

### Additional Information

Was working fine ~2-3 weeks ago.

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by orangecoloured** [comment]
Same issue here. Been like this for several days already.

**Comment by absidue** [comment]
The local API error sounds like you are trying to watch an age-restricted YouTube video, which won't work (you need to use the official YouTube website or apps with an age-verified YouTube account).

The Invidious API one means that the instance you are using got ratelimited by YouTube.

**Comment by absidue** [comment]
Could you please provide links to specific videos that you are getting the local API error with?

**Comment by Dublin1855** [comment]
> The local API error sounds like you are trying to watch an age-restricted YouTube video, which won't work (you need to use the official YouTube website or apps with an age-verified YouTube account).
> 
> The Invidious API one means that the instance you are using got ratelimited by YouTube.

isn't that the whole point of Freetube?   to avoid logging into Youtube?   it worked fine a few weeks ago....

**Comment by absidue** [comment]
YouTube fixed the age-restriction bypass (as mentioned in other places) so now you need an age-verified YouTube account for them everywhere.

**Comment by riverpiers** [comment]
@absidue Interestingly, comments are only available under the 'age restricted' videos, in v0.21.3 Beta.

**Comment by orangecoloured** [comment]
@absidue 

> The Invidious API one means that the instance you are using got ratelimited by YouTube.

Thanks. This was the case for me. Now it's working fine.

**Comment by absidue** [comment]
> Edit +: And 'shorts' are visible in the tab under: 'all channels', and are not visible in the tab on the channel page.

@riverpiers That is entirely expected with 0.21.3 as YouTube changed stuff on the shorts tab and FreeTube's local API received support for it with 0.22.0. Please don't report issues unless you are using the latest version of FreeTube or read the changelogs of more recent releases to check if your problems were already solved in a more recent releases before reporting them.

**Comment by rjc3rd** [comment]
For me, yesterday and today, I also received API errors and was not able to watch videos on FreeTube. I could refresh the list but clicking would return an API error. I just accepted it. I would right click the icon and copy the youtube link and open in LibreWolf with uBlock Origin. This worked fine. Except, I also could not properly search YT.com or if it did search, if I clicked on a video thumbnail, it just would not play a video. It actually would tell me I had no internet connectivity. If I put the link provided by FreeTube in the browser it would play that video just fine, but couldn't do anything else on YT.com

Every other site and internet app worked fine on the VPN.

This made me wonder if YT didn't like my VPN (riseupVPN) so I turned off the VPN. The browser and FreeTube work perfectly now. So I turned my VPN back on to a different city, and it still works.

I'm just putting that out there, because it's the only reason I was over here on github looking at the Issues link.
