### ISSUE TITLE
[Bug]: Subscription tab doesn't show video length for any video

### ISSUE THREAD

**Issue by Hulttio0x0** [FreeTubeApp/FreeTube#6212]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

If i delete all of my subscriptions and i subscribe to one channel everything works as expected, subscription tab shows video length, but as soon as i import my subscription file and go to subscription tab, not a single video shows length.

### Expected Behavior

Show video length in subscription tab

### Issue Labels

inconsistent behavior

### FreeTube Version

v0.22.0

### Operating System Version

linux mint

### Installation Method

.deb

### Primary API used

Local API

### Additional Information

![Screenshot from 2024-11-22 07-34-49](https://github.com/user-attachments/assets/0d9a6420-c166-4751-80de-e966b260fe31)

[youtube-subscriptions-2024-11-22.csv](https://github.com/user-attachments/files/17863427/youtube-subscriptions-2024-11-22.csv)

### Nightly Build

- [X] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by absidue** [comment]
When you have 125 or more subscriptions in the currently selected profile, FreeTube uses the RSS feeds instead of requesting the channel data like normal (it shows a toast message telling you that it is doing that) to avoid you getting ratelimited by YouTube. The RSS feeds don't have the video duration or live status, which is why you don't see them.

If FreeTube didn't force RSS for people with too many subscriptions, only some of your subscriptions would get loaded before you hit the rate limit and then you wouldn't be able to use most of the app, including watching videos or even refreshing your subscriptions again for a while because of the rate limit.

**Comment by absidue** [comment]
Closing as this is working as expected.

**Comment by p-himik** [comment]
Just noticed this with around 500 subscriptions. A weird thing is that some videos do display their duration.

Perhaps it's possible to request duration separately for each video, when the subscriptions page is scrolled?
