### ISSUE TITLE
[Feature Request]: Naming scheme for screeshots

### ISSUE THREAD

**Issue by Janaue** [FreeTubeApp/FreeTube#6220]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Currently a screenshot from the button on the player names the picture as the date like 20241124-102600, but that's unusable. 

### Proposed Solution

There needs to be more information in the name of the picture, for instance
CHANNELNAME_DATE[yyy_MM_dd]_VIDEONAME_date_of the picture.png

### Alternatives Considered

NA

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
I'll assume from the fact that you are asking to change the default screenshot pattern, that you didn't even check the screenshot settings before opening this issue? As there is already a "filename pattern" text field that lets you configure what the files should be named, which is hard to miss considering that it is near the "enable screenshot" switch that you needed to turn on yourself, because taking screenshots is disabled by default.

Yes, the channel name and video title are not currently available as variables at the moment (going to be messy to add, **if** we add them as options, as there are various characters that can appear in video titles but are not allowed in filenames), but it is generally a good idea to check what already exists, so you can ask for the right thing before opening an issue.
