### ISSUE TITLE
[Feature Request]: Native Picture-in-picture on macOS

### ISSUE THREAD

**Issue by poweruser82** [FreeTubeApp/FreeTube#6234]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

Current implementation of Picture in Picture on the macOS app is useful only when you are inside the app.
You can't continue to watch the video while having other windows open or switching spaces.

### Proposed Solution

Use macOS native PiP mode

### Alternatives Considered

-

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
Could you please provide screen-recording of what you mean by "You can't continue to watch the video while having other windows open"?

**Comment by poweruser82** [comment]
I'm sorry, I was wrong about that. The player stays on top in a normal space and even when switching to other normal spaces.
However it isn't visible in full screen apps or in spaces with split screen apps.

**Comment by absidue** [comment]
Okay that's good to know.

FreeTube uses Electron which is built on top of Chromium. Chromium uses a custom picture-in-picture implementation so that it works the same on Windows, macOS and Linux.

We do not have control over things that low level, it also seems very unlikely that Chromium would start using the native macOS picture-in-picture APIs as it would require a lot of changes not just to the picture-in-picture handling but also major changes to their video handling pipeline. The amount of time and effort that would be required to make those changes and then fixing all the problems that appear when you make changes that major, are probably not worth it for them, considering that you can easily work around it by not fullscreening another window.
