### ISSUE TITLE
Display PeerTube search results

### ISSUE THREAD

**Issue by jibe-b** [FreeTubeApp/FreeTube#625]
PeerTube is streaming videos peer-to-peer using WebRTC.

There now is a search engine: https://sepiasearch.org/

and one may install their own scraper, index and serve a search portal too, using the code https://framagit.org/framasoft/peertube/search-index

What would be interesting would be that Freetube sends the searched request to a PeerTube search API and displays the results among the results.

**Comment by jibe-b** [comment]
You may mutualize with the NewPipe team to implement this once for both projects https://github.com/TeamNewPipe/NewPipe/issues/4461

**Comment by lucanomax** [comment]
Since freetube doesn't have a peertube tab, I think it might be a good idea working on it. Maybe search results take less priority, but adding somewhere on the roadmap would be perfect.

**Comment by Rik44444** [comment]
I really support the idea of a Peertube tab (and potentially other video services)

**Comment by GilgusMaximus** [comment]
This is very likely not going to be done. One platform alone is a huge undertaking for us already. Adding more platforms is a whole other project. However if someone wants to create a module which does that, converts the data in a way it is easy to hook up to Freetube and is willing to support this into the future actively, we might consider that. But be aware that this will be a lot, and I mean a lot of work

**Comment by roipoussiere** [comment]
> However if someone wants to create a module which does that, converts the data in a way it is easy to hook up to Freetube and is willing to support this into the future actively, we might consider that. But be aware that this will be a lot, and I mean a lot of work

If anyone is interested to develop a such module, since Peertube uses webtorrent to stream videos, I suggest to take a look at the [webtorrent](https://github.com/webtorrent/webtorrent) Javascript library ([docs](https://webtorrent.io/docs)), used [by Peertube](https://github.com/Chocobozzz/PeerTube/blob/develop/package.json#L143) and by [webtorrent-desktop](https://github.com/webtorrent/webtorrent-desktop/blob/master/package.json#L56) to retrieve and seed webtorrent streams.

As pointed out by @jibe-b [sepiasearch](https://sepiasearch.org/) should also be used to as a search engine for peertube videos [here is an example of an API call to sepiasearch](https://sepiasearch.org/api/v1/search/videos?search=freetube).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Going to close this for reasons stated earlier and on https://docs.freetubeapp.io/faq/#will-you-consider-adding-support-for-services-outside-of-youtube-twitch-soundcloud-peertube-etc

I would suggest opening a discussion thread over at the discussions tab If somebody want to discuss something about a potential module.
