### ISSUE TITLE
Subtitles selection and default language

### ISSUE THREAD

**Issue by dimqua** [FreeTubeApp/FreeTube#63]
Currently, you can't select which language of subtitles to show up. Please make it possible to set default subtitle language also.

**Comment by PrestonN** [comment]
In the current version of FreeTube, videos with multiple translated subtitles will show up in the video player.  The problem that you are seeing is that the videos that you are watching are using subtitles that are automatically generated using Google Translate.  It looks like it is possible to obtain these subtitles using the CLI version of youtube-dl, but I haven't been able to figure out how to do it with a youtube-dl server (parameters are sent different and aren't exactly 1:1).  I'll keep this issue open in case I figure anything out but for now FreeTube will be limited to the proper subtitles from a video.

**Comment by dimqua** [comment]
> In the current version of FreeTube, videos with multiple translated subtitles will show up in the video player. 

For me it doesn't work: I always see English subtitles regardless of other subtitles available.

**Comment by PrestonN** [comment]
Finally checked this and it looks like you are right.  I do not know why this ended up broken in 0.2.0 but it should be fixed in the next release.  I'll try to get it fixed for the patch this weekend but the structure has changed a lot due to switching youtube-dl to run locally.  I won't promise anything for this weekend patch but the next beta should have this fixed.  I will go ahead and close this.
