### ISSUE TITLE
Create Web Version of FreeTube

### ISSUE THREAD

**Issue by EnterTheVoid-x86** [FreeTubeApp/FreeTube#633]
I would like you to make an online version of FreeTube so that chromebook users, like I, can use the app without installing crouton or crostini.

**Comment by PrestonN** [comment]
We started work on a web version, however progress has been shelved for now because a web version will have to rely solely on Invidious for backend data.  When Invidious seems to be back to regular development (which looks like it's slowly starting to look that way) then we'll go back to making progress on this.

For now though, this won't be worked on.

**Comment by rozenj** [comment]
@PrestonN any updates?

**Comment by PrestonN** [comment]
There are currently no updates as of now. There will need to be a lot of changes on the backend that need to be made so that FreeTube can run without any Node / Electron specific APIs. A majority of the app doesn't need them however there's some logic that needs to be re-organized / rewritten to check when the APIs are available or not. This will be a very large update and I'll have to dedicate an update to getting it done. As of now, it isn't a priority so that we can instead focus on other features.

**Comment by GabrielLasso** [comment]
I'd like to run freetube on the browser also

**Comment by joelcieslar** [comment]
A web version is a very desirable feature, in my opinion. The transition from the web browser to FreeTube when clicking YouTube links is a bit slow and cumbersome.

It would also allow users to take advantage of browser tabs to have multiple videos open at once.

**Comment by sdfg2** [comment]
With sponsorblock built in, and a far superior interface with freetube, I wish invidious just merged this project in as their front end.

**Comment by DUOLabs333** [comment]
Would FreeTube use an Invidious site for its backend in its web version? I like that I am not dependent on another site (other than Youtube, of course).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
As already Preston mentioned

> As of now, it isn't a priority so that we can instead focus on other features.

So im closing this issue. For anyone that is interested check out this fork of FT that can run in the browser https://github.com/MarmadileManteater/FreeTubeCordova
