### ISSUE TITLE
v0.9.0 Beta is not displaying the video length in the subscription grid overview.

### ISSUE THREAD

**Issue by NotTheReal-Jamie** [FreeTubeApp/FreeTube#638]
v0.9.0 Beta is not displaying the video length in the subscription grid overview. Happened to me after being notified that videos are being fetched using RSS mode. (which I hadn't noticed happening before)

[Image of the issue](https://i.imgur.com/m0ieie3.jpg)

**Comment by PrestonN** [comment]
RSS is being force enabled if you have more than 125 subscriptions in your active profile in an effort to help with any rate limiting that might happen.  If you'd like to change this, please create a profile with less than 125 subscriptions.

When RSS is enabled, the duration of a video cannot be shown, because RSS doesn't return this information.  There isn't anything we can do about this unfortunately.
