### ISSUE TITLE
[Feature Request]: Refresh all subscriptions feeds at the same time

### ISSUE THREAD

**Issue by chrrybmb64** [FreeTubeApp/FreeTube#6380]
### Guidelines

- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the feature request I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.
- [X] This issue contains only one feature request.

### Problem Description

The videos, shorts, live, and community feeds have to be refreshed one at a time which is annoying

### Proposed Solution

Make the refresh button refresh all four feeds at the same time

### Alternatives Considered

n/a

### Issue Labels

improvement to existing feature

**Comment by absidue** [comment]
The feeds are intentionally split and refreshed separately as they fetch data from different channel tabs, doing them all in one go would definitely get you ratelimited by YouTube. The only way it would even be remotely feasible would be if it only used RSS, which doesn't seem to get ratelimited as quickly, that would however mean that you wouldn't see video durations, live status, upcoming status and would be limited to only 15 videos per channel per feed rather than the usual 30.

**Comment by chrrybmb64** [comment]
That's unfortunate. RSS isn't very appealing, so I guess this is a dead-end. Closing the issue.
