### ISSUE TITLE
[Bug]:  Switching profiles does not refresh feed

### ISSUE THREAD

**Issue by Brier1104** [FreeTubeApp/FreeTube#6450]
### Guidelines

- [X] I have encountered this bug in the [latest release of FreeTube](https://github.com/FreeTubeApp/FreeTube/releases).
- [X] I have encountered this bug in the [official downloads of FreeTube](https://github.com/FreeTubeApp/FreeTube#official-downloads).
- [X] I have searched the issue tracker for [open](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aopen+is%3Aissue) and [closed](https://github.com/FreeTubeApp/FreeTube/issues?q=is%3Aissue+is%3Aclosed) issues that are similar to the bug report I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the bug I want to file, without success.
- [X] This issue contains only one bug.

### Describe the bug

When changing profiles the subscription is not automatically updated. The option in Subscription Settings 'Fetch feed automatically' is selected.

This is a follow up on issue #6089.

### Expected Behavior

When changing profiles the subscription is automatically updated if 'Fetch feed automatically' in subscription Settings is selected.

### Issue Labels

feature stopped working

### FreeTube Version

v0.22.1

### Operating System Version

Windows 11 Pro

### Installation Method

.exe

### Primary API used

Local API

### Last Known Working FreeTube Version (If Any)

v0.21.3 ?

### Additional Information

![Screenshot 2024-12-24 170120](https://github.com/user-attachments/assets/5473f681-55d5-447e-b53a-aa7baf89b9f7)

### Nightly Build

- [ ] I have encountered this bug in the latest [nightly build](https://docs.freetubeapp.io/development/nightly-builds).

**Comment by Brier1104** [comment]
Maybe I'm missing something here.  If so, I apologise.  But, as I said above the automatic refreshing when you change to another profile is not working.  If this is an intended improvement then maybe the option should be removed from Settings.

**Comment by kommunarr** [comment]
The problem domain is complicated by the fact that we have some pretty intricate rules related to video caching across sessions and profiles. This can lead to subscription videos not always auto-refreshing because there is recent enough video data already saved in the cache. The author of the previous issue adds on that changing profiles should not trigger a refresh if all of the channels were refreshed relatively recently, which is somewhat difficult to define in more objective terms. As I said on the other issue, this becomes the sub-issues of  "is something actually broken with our caching logic and that's what some people dislike about it in certain situations","should caching be time-limited or have even more complex rules around it to have auto-refresh align with people's expectations," and/or deciding if either or both are what's going on.

**Comment by Brier1104** [comment]
Thanks for the detailed explanation.  Is there a large processor or bandwidth cost to always refreshing? If not, could we have it as an option?

This is my personal preference of course. I have a few profiles and each one has many active subscriptions and therefore there are always new videos being published every few minutes that I want to be notified of.

"changing profiles should not trigger a refresh if all of the channels were refreshed relatively recently"
A quick question - how long is "relatively recently" :D 

~ Thanks again

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Also one of the reason it is implemented like this is to prevent getting rate limited

**Comment by Brier1104** [comment]
Is this me being rate limited?

![Screenshot 2024-12-24 192402](https://github.com/user-attachments/assets/18a0d726-399e-4663-bfc6-6f6dfeba46b3)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
No this has probably todo with being IP blocked, see #6385. Try different VPN servers
