### ISSUE TITLE
A lot of errors after updating libhttpclient-java on debian

### ISSUE THREAD

**Issue by mastercoldcoder** [FreeTubeApp/FreeTube#668]
Hello, this morning there was an update on debian of the following package: libhttpclient-java
Freetube loads but displays a bunch of error messages that I don't have time to copy...

TypeError: Cannot read property 'channelMetadataRenderer' of undefined
Error: Status code 404
Error: Status code 500
.....

I think it's related to the update of the package mentioned above, since Freetube is partly developed in Javascript.
my programming knowledge is limited but I wanted to participate in reporting bugs on this fantastic project.
Thanks to all of you !

**Comment by PrestonN** [comment]
Java and Javascript are two very different languages, so the package you downloaded should have nothing to do with this error.

With this error, there is a specific channel in your subscriptions that is causing the problem.  I'd like to know which channel is causing this problem so that I can look into this further.

I know that this might be a tedious task, but could you please check each channel in your subscriptions and let me know which one(s) is causing the issue?  I won't be able to continue looking into this until I know.

**Comment by mastercoldcoder** [comment]
Yes you're right @PrestonN  I have a "youtuber" subscription that has been banned from youtube, I can't unsubscribe in order to remove it from freetube... I am blocked

**Comment by PrestonN** [comment]
In the future you can delete the channel by opening your profile and deleting it that way.

We'll try to make this more clear in a future update as well.
