### ISSUE TITLE
TypeError: Cannot read property 'sectionListRenderer' of undefined

### ISSUE THREAD

**Issue by lydenyardley** [FreeTubeApp/FreeTube#670]
**Behavior of the program**
Slow to refresh subscriptions pages, and produce errors every time

**Expected behavior**
Subscriptions page to be refreshed without error

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to 'Subscriptions'
2. If videos are already loaded, click on 'Refresh button'
3. See error 'TypeError: Cannot read property 'sectionListRenderer' of undefined' at least 4 times
4. After they disappear, the videos load successfully

**Screenshots**
![Annotation 2020-10-15 123139](https://user-images.githubusercontent.com/2838799/96117729-0dac7f00-0eda-11eb-9804-f209a3ccbcc2.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Version: 10 (up to date)
 - FreeTube version: 0.9

**Comment by PrestonN** [comment]
With this error, there is a specific channel in your subscriptions that is causing the problem.  I'd like to know which channel is causing this problem so that I can look into this further.

I know that this might be a tedious task, but could you please check each channel in your subscriptions and let me know which one(s) is causing the issue?  I won't be able to continue looking into this until I know.

**Comment by lydenyardley** [comment]
Ahhh, I found the culprits:

- 'Porcupine Tree - Topic'
- The Pineapple Thief - Topic'
- 'James Labrie - Topic'
- 'News'

None of these are actual channels - just aggregator channels by YouTube's algorithm! Now I've 'unsubscribed' from these, all is well and without error.

Thanks for your guidance.
(Looking forward to a watch later playlist feature :))
