### ISSUE TITLE
Add support for http(s) links

### ISSUE THREAD

**Issue by 360fun** [FreeTubeApp/FreeTube#672]
In relation to #618 I propose to add the support for http(s) protocol, in order to pass directly YT links to FreeTube.

The purpose is to use apps like https://github.com/will-stone/browserosaurus or https://github.com/johnste/finicky to open directly FreeTube when the user clicks on a YT link outside of the browser (RSS app, Telegram, Thunderbird...).

![image](https://user-images.githubusercontent.com/844090/95446623-d3cefc00-0960-11eb-97a0-96c71c74c9f4.png)

I believe that in order to show FreeTube in the browsers list, it should be registered in the OS as "application able to handle http(s)".

I need this in Mac OS but this would be an interesting feature for Windows and Linux as well.

**Comment by PrestonN** [comment]
This may end up being more troublesome than it's worth.  Not everyone will be using / have the same tools that you're using, and I would have to put this together with the assumption that no other tools are available to the user, which means that i need to keep a list of all browsers on a user's machine.  I'd essentially be integrating the entire functionality of those tools into to FreeTube since then FreeTube would be handling all HTTP links, regardless if they're video links or not.

I also already have troubles getting this type of functionality working on Mac, which would make testing even more difficult for me.

Sorry, I don't see this happening.  If someone comes in willing to implement / support it, I'll accept a PR, though it's unlikely that this will be implemented.

**Comment by 360fun** [comment]
So you plan to make FreeTube the default app for any kind of link, right? In case the link is not a YT link what is going to happen?

**Comment by PrestonN** [comment]
I don't plan on doing anything to implement it, because of what you mentioned.  For FreeTube to support HTTP links, that means that it would handle an HTTP link from every app on your machine.  It would have to determine if the link is a YouTube link (which isn't the hard part) and then keep a list of every other app that can handle HTTP links and then redirect it to them if it's invalid.  Once you throw in cross platform support (which I clearly can't handle well since Mac had so much trouble), this isn't worth the implementation.

**Comment by 360fun** [comment]
You're right, I believe this is the easiest solution then: https://github.com/FreeTubeApp/freetube-redirect/issues/14
