### ISSUE TITLE
50 videos load on a channel

### ISSUE THREAD

**Issue by Joseph65** [FreeTubeApp/FreeTube#69]
when i view a channel it only loads 50 videos. It would be nice to have a "load more" button.

**Comment by aproposnix** [comment]
Good point. 

Though not exactly the same, issue #3 covers search improvements. I think this issue could be resolved by it - adding a "show more" button is essentially a search, right?

**Comment by PrestonN** [comment]
This is planned to be fixed.  The next release is planned to have an overhaul for the channel view so I'll make sure to include this while working on it.

> I think this issue could be resolved by it - adding a "show more" button is essentially a search, right?

More or less.  The way you grab the videos is to perform a search, but the code will need to be slightly different than the generic search function due to how specific the search is.  This includes the "Show More" button needing it's own logic as well.

**Comment by PrestonN** [comment]
This has been fixed.  Expect to see this in the next release.
