### ISSUE TITLE
Don't open on Pinephone

### ISSUE THREAD

**Issue by Transistor4aCPU** [FreeTubeApp/FreeTube#690]
Flatpak Version don't open on Pinephone Manjaro phosh.
`(freetube:2): Gtk-WARNING **: 11:04:23.256: cannot open display: :99.0
[fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...
`

**Comment by PrestonN** [comment]
The Pinephone is not currently supported.  Even if the install was successful, the app wouldn't be very usable due to some sizing problems and some keyboard issues that seem to occur with Electron apps.  When the keyboard issues are fixed and I can get around to fixing the sizing issue, I will then consider the Pinephone as "supported".

**Comment by RangerMauve** [comment]
Is there somewhere we can track the keyboard and sizing issues on Electron?
