### ISSUE TITLE
Change comments font size

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#692]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
The comments font size is pretty small and barely readable. I'd like to be able to change their size.

**Describe the solution you'd like to see implemented**
A parameter allowing users to change the font size.

**Comment by GilgusMaximus** [comment]
Hi, so for the moment you can use Electron's zoom in (Ctrl + Shift + +) and zoom out (Ctrl + -) feature to zoom in and out.

Adding font scaling is on the table however not implemented yet

**Comment by stemy2** [comment]
The command does nothing.

**Comment by linuxgirl22** [comment]
Just to +1 this. Great to have the UI scaling button added, and that makes a really good difference. :-) The only issue I've been having is the comments size; moving the UI scaling slider up higher would make the rest of the UI become too large.

**Comment by PrestonN** [comment]
Does the new release help?  I've slightly increased the text size for comments in the v0.9.1 release.

**Comment by linuxgirl22** [comment]
I've just tried it, and it does! Thank you so much for this. :-) Really appreciate.

**Comment by PrestonN** [comment]
Closing as we have increased the font size for comments since this issue.

**Comment by J-Kappes** [comment]
I'm on v0.19.1 and I still think it's too small.
It seems about 20 - 30% smaller than the video description text for which I see no reason.

**Comment by jasonhenriquez** [comment]
@J-Kappes good call-out. Video description text is 17px, comment text is 14px. We should definitely aim for higher on this [given that it's body text](https://marvelapp.com/blog/body-text-small/).

**Comment by J-Kappes** [comment]
@jasonhenriquez I do zoom in on both YouTube and FreeTube because I often lie in bed and have my screen mirrored to my TV. It's the relative size that bugs me. YouTube's video description box is smaller by default, its text is the same size as the comments, the profile pictures are smaller and the sidebar hides fully. This leaves a lot more space for the comments. At least FreeTube's thumbs are smaller since they don't need to function as buttons.

I think making the comment text size equal to the description would already do a lot for me. Maybe shrinking the profile pics to get some horizontal space.

![image](https://github.com/FreeTubeApp/FreeTube/assets/87168492/e1c53c1a-b4e6-4344-81cc-4672f9ae3a27)

![image](https://github.com/FreeTubeApp/FreeTube/assets/87168492/062e9fbf-79da-48c8-ba04-3fbb5a66ce78)
