### ISSUE TITLE
Title of vid in fullscreen

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [FreeTubeApp/FreeTube#694]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
In YT i noticed when in fullscreen and move ur mouse in any direction u will see the Title of the vid in the left top cornor. It bugs me it is not there. For example if i watch a music vid in fullscreen of an unknown artist and i want to see who it is or what the name of the song is then i have to leave fullscreen.

**Describe the solution you'd like to see implemented**
I would like this to be implemented as the same visual way like YT.

**Describe alternatives you've considered**
None

**Screenshots**
None

**Additional context**
None

**Comment by GilgusMaximus** [comment]
It would be ideal if a videojs plugin for that exists, or one is created.

We are definitely open for either direct implementations (in case Videojs allows this already) or the setup of a VideoJS plugin.

**Comment by TDDR** [comment]
Could I try and use this plugin for the issue?
https://github.com/brightcove/videojs-overlay

**Comment by GilgusMaximus** [comment]
Hi.
So the license looks fine and if you can get this plugin working nicely, that'd be great :)
I'd assign you to this issue if that is okay?

**Comment by TDDR** [comment]
Please do!

**Comment by TDDR** [comment]
Hello,
[I have made some progress](https://github.com/FreeTubeApp/FreeTube/compare/development...TDDR:issue-694) but am stuck on the last detail. As it stands the overlay is stuck in the background. I know it's there because with video's shot in widescreen [(Like this one)](https://www.youtube.com/watch?v=Gz7WMF4wWko), the text appears in the top left as expected because of the gap left at the top. For all other videos though the overlay remains hidden in the background.

[I found this issue](https://github.com/brightcove/videojs-overlay/issues/108) in the overlay closed issues that says I need to include the overlay css, but doing so does not fix the problem.

[I also found this issue](https://github.com/videojs/video.js/issues/929) that says I need to append the overlay to the videoPlayers containing div, which I think is the `relative` class, but have no success with that. 

Any help would be greatly appreciated.

**Comment by GilgusMaximus** [comment]
Hi, so it would be great if you can create a PR and mark is as draft and label it with 'Help wanted'. Then everyone sees that a new PR is available and can take a look. Because we are also not so invested into VideoJS plugins, it might take a bit until help arrives. 

But great work so far that it is working on some videos already. Getting something to work partially is always the first step towards fixing up the last bits 👍

**Comment by TDDR** [comment]
Hey @GilgusMaximus , I made a little more progress since last time but there's still one nagging issue. I made a draft PR like you suggested but I cannot change the labels to it. Could you please add the `help wanted` label to that PR.

**Comment by PrestonN** [comment]
I added the tag for you.  I'll review / help out sometime tomorrow to help finish up the PR.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi i saw the implementation while watching this vid:
https://youtu.be/ipJb4mB5bMA

it seemed fine in the beginning of the vid, but when a white background went by in the vid i couldnt see the title anymore when i moved with my mouse. The title should be clear to see at all times.

![Screenshot (9)](https://user-images.githubusercontent.com/73130443/101463013-c91aee00-3934-11eb-8bd2-2155dd186620.png)

**Comment by GilgusMaximus** [comment]
Please open up a new issue for this bug to make it visible to everyone.
