### ISSUE TITLE
feature request: monitization for creators

### ISSUE THREAD

**Issue by Rik44444** [FreeTubeApp/FreeTube#707]
feature request for implementing monitization possibilities for creators. For example, I will happily voluntarily pay a certain amount of money to creators per minute of watched video, or pay for a voluntary monthly subscription fee for Freetube and Newpipe combined that gets dispersed over the creators of the videos that I watch. Also perhaps a good way to generate some core funding for Freetube itself.

I post this because i think it is important that open alternatives are created to Youtube. The main reason why creators are not yet moving away from Youtube to alternative platforms like Peertube etc is the lack of monitization options there, so i've made a feature request for this on Peertube also. But to professionalise Freetube in the future as well, i think this will be an important step.

**Comment by PrestonN** [comment]
This will likely never happen for any project like FreeTube, which would include NewPipe, Invidious, and any other similar project.

The moment we start trying to monetize the content within FreeTube is the moment we start getting confronted by Google / YouTube.  We would be directly competing with their bottom line revenue and since we're using their content, it would be an easy lawsuit for them to handle.

Many creators have more ways to help them out besides advertisements, and they'll likely have that information somewhere in the description or even in the video itself.  I highly encourage anyone to look at those methods if they'd like to support a certain creator.

One option I'm considering doing (which was actually available in the old FreeTube) was having a new "Format" in the settings which defaults to YouTube's official player.  If you use this player, you'll be exposed to any tracking that may be included in their player, though it also means ads will run, which can be used to support that creator.  So if you truly want to support that creator, then FreeTube will still have an easy option to do so.

If you want to support me and the work that I do, then I can only offer methods of donating to me.  I cannot and will not charge the user for features or enhancements, even if it seems like it's in good intentions.

**Comment by Rik44444** [comment]
hm and perhaps for Peertube content, in collaboration with them, instead of Youtube content?
