### ISSUE TITLE
Make Freetube's Suscription Groups compatible with Pockettube Exports (Allow the importing of PocketTube's json)

### ISSUE THREAD

**Issue by Zhiro90** [FreeTubeApp/FreeTube#719]
(Previously opened this issue albeit  misworded, so I hope it's not counted as spam)

As it says on the tittle, allow importing of pockettube's exports. It would be nice easily swich from one service to another.

**Comment by GilgusMaximus** [comment]
It would be helpful to get the content of an exported file to be able to see how this works.
As mentioned in #700, it would probably fit better into my project for converting legacy formats into FreeTube.
You can it [here](https://github.com/GilgusMaximus/FreeTube-Legacy-Converter).

Implementing it into the main project will likely not happen, as people come with all kinds of add-ons and plugins with all kinds of formats, which we simply do not want to implement, because it is either not a major way of exporting Subscriptions (like NewPipe and Youtube) and it just makes the code base bigger and less easier to maintain.

**Comment by Zhiro90** [comment]
Here's an export (it was actually json, not xml) 

It comes in a very straightforward format, ie:

{"GROUP1":["CHANNEL1ID"],"GROUP2":["CHANNEL1ID","CHANNEL2ID"]}

[youtube_subscription_manager_2020-10-25-14_02.zip](https://github.com/FreeTubeApp/FreeTube/files/5435858/youtube_subscription_manager_2020-10-25-14_02.zip)

Regarding the projects, do I add this suggestion into the other one?

**Comment by GilgusMaximus** [comment]
So first of all, thanks for the information on the export format.
The thing with the establishment of these add-ons is, that we do not have any information on who uses what and how many users of the add-ons and FreeTube intersect. Additionally, user might have converted their subscriptions manually by this point in time.

So while the format is straight forward, I would say that it still requires some additional code work from a converter. Because FreeTube needs additional data like Name, link to the channel picture and more. So requests and data handling must be implemented again. 

It is not as straight forward as from the old FreeTube format to the new one.  
You can leave it here for the moment, if someone wants to implement it, they can please go over to the project I linked above and implement it there. Best case would be in a new file which handles this code in it's own methods and is only called from the existing files. I'm not sure whether I'll have time to do that

**Comment by GilgusMaximus** [comment]
Okay I took the little time I had right now and implemented it, because with the module, most of the code was already there. However, it does **not** add the profiles to already existing ones. So it will create in the case of your file 3 new profiles.

Closing it now. If any issues occur please post them on the converter's repository
