### ISSUE TITLE
Question: Translations?

### ISSUE THREAD

**Issue by MegaArthur** [FreeTubeApp/FreeTube#73]
### (I really don't know whether this should be categorised as an issue, but whatever)

Hello,
I have been really interested in contributing to this project, but without a lot of programming experience, there wasn't much I could do, until I thought of one thing. _Translations._ 

Seen as FreeTube is an amazing project that has a ton of potential, it might be wise to implement different languages and for that, I volounteer as a native speaker of a non-English language.

If translation is a matter that could have any importance at all, I'm ready to help.

**Comment by PrestonN** [comment]
Hey there.  From what limited analytics that I have access to, translations seems to be very important for FreeTube.  A lot of press that has been going around has been in non-English languages, so it's safe to say that the demand for it is definitely there.  I would love to have your help as well as any others that would be willing to help for future translations.

The hard part right now is going to be finding the right time to implement this.  FreeTube is still in it's infancy and there are still plenty of features that need to be implemented.  Whenever translations get implemented, keeping them up to date at this stage with changes being made frequently can possibly get pretty troublesome.  I'd hate to have to release half of a translation because of new changes and I don't have contact with someone who can do the translation.

I'm not sure how I want to prioritize this.  Part of me wants to flesh out the rest of the core features that FreeTube is missing before I focus too much on translations.  If you have the know how on how to implement it though then you're more than welcome to work on it.   I didn't search for very long, but this article seems to be helpful if you (or someone else) wants to take a crack at it.

https://www.christianengvall.se/electron-localization/

If you don't feel comfortable working on it and would rather just do translations, I could make an early template of what a translation file should look like and then you can create a new file for the language(s) you would like to translate.  This would allow you to at least get started and then I can use the translation when I'm ready to implement it.

**Comment by MegaArthur** [comment]
Seen as my experience with electron and JS in general is very limited, I don't think I could do what's written in the linked article, but when you have time and feel that FreeTube is ready for translating, hit me up with that template. 

(I forgot to mention, I would be translating into Polish)
