### ISSUE TITLE
Error parsing info: Cookie header used in request, but unable to find YouTube identity token

### ISSUE THREAD

**Issue by stemy2** [FreeTubeApp/FreeTube#732]
**Important note**
Please check other open and closed issues for a similar bug before reporting a new one. 
Also please leave all headers except this one in the issue, so that it is clear what belongs where.

**Behavior of the program**
When i'm trying to open a video, i have nothing but this error message.
**Expected behavior**
The actual page of the video

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Open any video

**Desktop (please complete the following information):**
 - OS: Debian
 - OS Version: 10.6
 - FreeTube version: 0.9.1

**Comment by Synkky** [comment]
This problem is almost certainly fixed now.

Can you go to the Actions tab (top of the page), click on the "Fix linter issues" result and download a portable version of that build, in order to check if the problem still exists with that executable?
You should choose one of the following links:
- freetube_0.9.1_linux_portable_x64
- freetube_0.9.1_amd64.AppImage (if you prefer an AppImage type)

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Getting the same error.

Im on Win10 1909
freetube 0.9.1

**Comment by GilgusMaximus** [comment]
Did you try to update as @Synkky suggested?

**Comment by GilgusMaximus** [comment]
Okay thanks for the confirmation. I'll close this issue now :)
