### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by Richardsilsa** [FreeTubeApp/FreeTube#757]
**Behavior of the program**
Every time i click an video it gives this error and keeps loading forever

**To Reproduce**
Just try to open any video

**Screenshots**
![Captura de tela de 2020-10-31 21-43-09](https://user-images.githubusercontent.com/63064071/97792890-36fc2900-1bc3-11eb-84ca-5ee569910c51.png)
![Captura de tela de 2020-10-31 21-45-37](https://user-images.githubusercontent.com/63064071/97792916-7a569780-1bc3-11eb-88a6-5cc53670e36a.png)

**Desktop (please complete the following information):**
 - OS: Fedora 33 under Xorg
 - FreeTube version: 0.9.1 beta via flatpak

**Comment by PrestonN** [comment]
Release was made earlier today.  Flatpak is delayed by a couple of hours because of FlatHub's build systems but it's already handled and will be released soon.

Also this is a duplicate issue of #733.  Please look for existing issues before you create new ones.

**Comment by Abdulee** [comment]
Issue is fixed in the latest 0.9.2 release. Get the rpm [here](https://github.com/FreeTubeApp/FreeTube/releases/download/v0.9.2-beta/freetube_0.9.2_amd64.rpm.zip) ... Ps. I would advice against using the flatpak for Fedora since you can just use the rpm. [Why not to use flatpaks](http://flatkill.org/) ...
