### ISSUE TITLE
blocked video behavior

### ISSUE THREAD

**Issue by sean1138** [FreeTubeApp/FreeTube#76]
I think it would be nice if FreeTube could tell you that the video has been blocked, rather than 'video not found', when it has been blocked for some reason.  Is that possible to do?

"This video contains content from WMG, who has blocked it in your country on copyright grounds." is the message i see in the youtube player, hooktube displays this message via the youtube player so maybe it's not possible to detect why or that a video has been blocked, rather than set to private or actually deleted by the uploader.

https://www.youtube.com/watch?v=yqecyQXOezc - should be decent for testing, blocked in US & Canada on copyright grounds, probably other countries as well.

when i search for this video by its title (video dj livestream 2018 spain) in FreeTube, then click the result for it to play, i get an infinite loading animation.  I can't click any of the left menu options when this infinite loading animation is going but i can close and open the left menu.  Could there be a 'stop loading' button of some kind for a case like this?  I resort to closing the window and restarting the program after waiting a few minutes for the loading animation to stop, but it does not stop, because i can't do anything else.

off topic, but if you don't mind, are there any plans to support other video sites?  i think this could be a killer app if i could subscribe/follow or otherwise keep track of any channel i want regardless of the platform!  Other sites like bitchute, vimeo, dailymotion, etc.

**Comment by PrestonN** [comment]
The error message for blocked videos definitely needs to be updated.  I appreciate the example video as that should help me implement this faster.

I've thought about having a timeout for the loading screen, to force it to turn off after a certain amount of time.  This should at least prevent the users from having to restart the application in order to continue using it.

As for other websites like @LexHimself mentioned, I'd like to stick with YouTube for now.  Having said that, youtube-dl does provide support for these platforms so it should be possible on that standpoint.  With the eventual switch over to the NewPipe extractor, that also opens up the possibility of getting the information for FreeTube.  It's something to think about, but for now there are no plans for other sites.

**Comment by PrestonN** [comment]
This should be fixed in the new / current release.
