### ISSUE TITLE
black flashes and artefacts

### ISSUE THREAD

**Issue by yepyepyep4711** [FreeTubeApp/FreeTube#762]
**Behavior of the program**
during playback, picture will flash black in parts or totally, or briefly display some encoding/compression artefacts.
While it definitely happens if the program switches video quality, it also happens if I select the quality myself

**Expected behavior**
same picture quality as youtube.

**To Reproduce**
Please add all steps to reproduce the behavior:
1. Go to any video, preferably hi-res and studio recorded
2. Click on play
3. Wait

**Screenshots**
Sadly, this is too fast to screenshot.

**Desktop (please complete the following information):**
 - OS: Win 7
 - FreeTube version: 0.9.2 Beta

**Comment by GilgusMaximus** [comment]
This is probably more relevant for VideoJS and the vhs plugin used. This could simply be because of the switch from one stream to another and then the player not getting all data fast enough from the new stream.

I do not see how we could change things about that that as the whole playback and streaming is not our project.

Therefore I am going to close this for now.
If more people experience that frequently, we can open it up again and discuss how we approach this error with the people behind the modules we use
