### ISSUE TITLE
Importing old history.

### ISSUE THREAD

**Issue by AmandaONeilll** [FreeTubeApp/FreeTube#764]
**Behavior of the program**
when importing db. history file from a previous freetube instance it states "history object has insufficient data skipping item." 4 times before "all watch history has been successfully imported."
looking at the Subscription list shows it didnt do so.

**Expected behavior**
Import history and show what videos has been watched or not.

**Screenshots**
[
![Screenshot from 2020-11-02 19-05-40](https://user-images.githubusercontent.com/65868299/97903457-5750f280-1d3f-11eb-8992-40bb8bcf6a56.png)
](url)

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon
 - OS Version: 20
 - FreeTube version: v0.9.2
 - FreeTube build: Release

**Additional context**
importing data has worked flawlessly before, using a previous freetube version shows the same problem.

**Comment by GilgusMaximus** [comment]
The problem is that the history import, as far as I know, is only for the new format. So when you export it from the button to the right and then import it again.

However I am maintaining a Legacy Converter project which is made specifically for your use case because PrestoN and I do not want to clutter the project with backwards compatibility.

You can find the project [here](https://github.com/GilgusMaximus/FreeTube-Legacy-Converter). I provide pre-built binaries for download, but you can also install NodeJS and run the source code.

However always backup your files before, as it is always possible that one of your files has some sort of corruption or similar and it might break your new files as well if the program errors out during writing.

**Comment by AmandaONeilll** [comment]
thank you for this info, however when it ry to use this project it will throw me one of two errors.
if i use the release version it will say:
"Aborting: Wrong number of arguments were supplied. Expected 5, got 1"

if i try to run the sourcecode:
"internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'yt-channel-info'"

further help would be appreciated as i am a bit of a novice here.
