### ISSUE TITLE
Update via app [stable, beta(pre-relese), edge]

### ISSUE THREAD

**Issue by gistsy** [FreeTubeApp/FreeTube#767]
**Describe the solution you'd like to see implemented**
I'm really mad with download edge builds from github actions (edge)

Can you implement a method to update via app? user can select required update channel and tap 'update'
For edge, you can display commit id then it help to verify the build.

**Comment by gistsy** [comment]
About portable app: it needs to have same feature similar telegram desktop

**Comment by GilgusMaximus** [comment]
Hi, so first of all the way people update their programs really depends on their OS.
On Linux many people use Flatpak or the OS's repositories, while on Windows and Mac you have to use the normal installer.
And e.g. for Arch there seems to be the option to pull from the git repository and build automatically, basically updating every time a new commit comes in. 

Because of the way we are currently working, updating the program from within itself for every new commit will not happen for 3 reasons.

1. We do not have an update process in place. Not even for the releases. And implementing that for e.g. Windows will take some time
2. The way we are currently developing, updates will pore in multiple times a day because of Weblate. Additionally we implement features that have not been tested much by some voluntary testers and then updating it for a lot of people will break their apps from time to time, which is really annoying for everyone. Especially for the Github issues as they will get flooded with new issues every day.
3. Without an account it is not possible to update from Github actions, so FreeTube wouldn't be able to get the new updates

So I am sorry to say that at the moment the easiest way is to either look at the Commit history and spot where the last non-Weblate commit was, so you know whether you are running the most recent feature updates and bug fixes or clone the repository and build from source for your platform. (And for things like Arch Linux there is the option to use the mentioned repository)
