### ISSUE TITLE
Cannot open any video nor search

### ISSUE THREAD

**Issue by andrejdam** [FreeTubeApp/FreeTube#770]
Hi there,

I am not a technical person, so excuse my ignorance. 

**Behavior of the program**
I installed FreeTube some time ago, let's say two weeks, and in the beginning everything went smoothly. However, since several days ago FreeTube simply doesn't open ANY videos nor it can search.

When I try to open a video from a subscription, it says:

`TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined`

When I try to search it says:

`TypeError: Cannot read property 'runs' of undefined`

I am very suspicious of YouTube / Google here, because NewPipe on Android stopped opening videos around the same time.

So what's going on here? Let me guess, Google changed the website code for the 186th time this year, and it cannot be parsed anymore. The question is, how to avoid these kinds of stupidities from YouTube's side, and be able to dynamically adjust the parsing algorithm so that it works regardless of what Google does i.e. like their website opens within a browser.

**Expected behavior**
To play videos and perform search.

**To Reproduce**

1. Just try to search for anything or play any video

**Desktop (please complete the following information):**
 - OS: Win 10
 - OS Version:
 - FreeTube version: 0.9.1 beta
 - FreeTube build: Release (I guess?)

**Additional context**

**Comment by GilgusMaximus** [comment]
Hi,
no problem, we are here for everyone from beginner to absolute master programmer and hacker.

The problem is indeed as mentioned that YouTube changed something in the layout of __some__ videos and searches leading to no results and no playback. If you could install the newest release v0.9.2, it solves most of the problems (at least most of the time, a better and more consistent fix is on the way). If you want to get the very newest version with the probably best working fix, you'd have to download the newest pre-release build in the Github Actions tab.

Also for more information, please refer to #733
