### ISSUE TITLE
record freetube in obs (windows 7)  it works, kinda.

### ISSUE THREAD

**Issue by barsupi** [FreeTubeApp/FreeTube#775]
hi. I've been using freetube and it seems like a very nice program and very lightweight.

Just as many other browser software, when hardware acceleration is activated, things just don't work in OBS. 
and that's the case of freetube as well. UNLESS. you set the .exe file compatibility mode to "windows vista"
nice.

I wonder if new releases of freetube are needed to keep supporting youtube in the future, but can you guys keep this weird support for windows 7and obs working, or as an option/feature?

btw 
windows 7x64
fretube v90.9.2 beta
obs studio: 26.0.2

**Comment by PrestonN** [comment]
I can't guarantee support for your setup, especially since Windows 7 is no longer supported by Microsoft. It's possible that a future update will no longer work on your system, depending on if Electron eventually drops support. If you come across an issue on more up to date software, feel free to open a new issue.
