### ISSUE TITLE
No compatible source was found for this media

### ISSUE THREAD

**Issue by ghost** [FreeTubeApp/FreeTube#822]
**Behavior of the program**
Certain videos result in "No compatible source was found for this media", with an X in the middle of the video.  

**Expected behavior**
Videos to load and play. 

**To Reproduce**
It does not occur for all videos, but a large subset of them. It seems to be limited to archived streams, however, I have not tested enough to confirm this. All of them load fine on the YouTube site. 

**Environment Information (please complete the following information):**
Arch
Freetube v0.9.2 Beta
Tried AUR and Flathub. 
Local API

**Additional context**
This has been occurring for a while, and as I couldn't find an issue opened, it is perhaps a problem on my end, however, as it has followed me across machines I'm not so sure. If you've a solution I'd appreciate it.

**Comment by GilgusMaximus** [comment]
Hi, so currently there is not much we can fix here at the moment. This error persists since the first implementation of the DASH format. The DASH file is most likely correct, because it works on a lot of videos and after some trying and reloading it usually works also with the videos that initially didn't work. The most likely problem here is that the player tries to access the file while it is written, so that the content is not completely written at that point..

However there are two things you can change to make it work:
1) use the legacy format. This allows you to watch the video up to 720p. 
2) Try to go to another page and then open the video again a few times. This will not always work, but in many cases.

So I'd like to keep this open for anyone to document when videos do not load. Because I expected this to pop up much much earlier and more frequent than it did now with this post. I'll also look into communicating with the people over at the video player to try and fix it at some point, once I am back at developing.

**Comment by Darkorz** [comment]
Good to know it wasn't a problem on my end. Unfortunately switching to legacy format (or audio format) did not make a difference.

**Comment by dorianvalerian** [comment]
It's happening with me too sometimes. Along with the "No compatible source" message, its giving me these errors in succession:
1. Error: Unable to retrieve video metadata
2. TypeError: Cannot read property '4' of null

**Comment by GilgusMaximus** [comment]
Could you please update to the newest nightly build @dorianvalerian and see whether it occurs again. This should be fixed in there

**Comment by dorianvalerian** [comment]
Great! It's working perfectly, thank you! There are no errors regarding any API to be seen 👍

**Comment by Flashwalker** [comment]
Same issue with dash and legacy in `freetube_0.11.2-nightly-514_amd64.deb` with some videos

**Comment by Svallinn** [comment]
This appears to be a rather stale issue, so we'll need to know if this is still happening
If we don't get a report 7 days from now, I'll assume this doesn't happen anymore and close the issue.

**Comment by Svallinn** [comment]
Considering this stale. Closing.
