### ISSUE TITLE
Time of the video do not appear in Subscription

### ISSUE THREAD

**Issue by e471wo** [FreeTubeApp/FreeTube#833]
Hi guys, 

Dunno if bug or not, but in subscription, the time of the video does not appear on the small image. But this arrive only in the subscribe tab.

here a screenshort.
![Screenshot 2020-12-06 at 08 34 37](https://user-images.githubusercontent.com/64007061/101274392-f7b29080-379d-11eb-8595-75c4918d6b04.png)

To reproduce: 
* Open Freetube
* go to subscribe tab. -> missing time on all videos.

**Comment by GilgusMaximus** [comment]
Hi, so this is intended. What happens here is that you fetch subscription data via RSS. This does not provide all information, like the time when videos were released. If you did not manually activate RSS though, FreeTube activated it automatically because you have too many subscriptions which without RSS would get you rate limited instantly when fetching subscriptions.

You can reduce your subscriptions, split them into profiles or leave RSS on.
