### ISSUE TITLE
No proper icon or ability to add to favorite on Linux using GNOME

### ISSUE THREAD

**Issue by luuknieuwdorp** [FreeTubeApp/FreeTube#869]
**Behavior of the program**
When using GNOME, you cannot add the freetube app to your favorites dash and the icon that is displayed in the dock is different from how it shows in the app launcher.

I searched around in the issues and it seems to me this issue https://github.com/FreeTubeApp/FreeTube/issues/257 has made a return after the rewrite.

**Environment Information:**
 - OS: Manjaro
 - OS Version: 20.2
 - FreeTube version: 0.9.3
 - Installation Method (If applicable): AUR

**Comment by PrestonN** [comment]
This might be a problem with the AUR version, since this doesn't appear to be an issue with any official release. I do not maintain the AUR version so I might not be able to provide a fix for this. I can only suggest you download one of the official downloads that I provide to prevent this.

**Comment by luuknieuwdorp** [comment]
Interesting, using the AppImage or using the AUR version that's built straight from git exhibits the same issues, but using the flatpak version seems to work fine. I'll just use that, thanks for your help (:

**Comment by PrestonN** [comment]
I believe the reason for this is because AppImage and the AUR builds are considered portable releases, which limits some of of the OS specific things that the build is able to do.

If anyone has ideas for allowing this on AppImages, then I'd be willing to implement it.

Since this seems to be resolved, I'll go ahead and close this.
