### ISSUE TITLE
Option for higher playback speeds?

### ISSUE THREAD

**Issue by narekboghozian** [FreeTubeApp/FreeTube#892]
Hi, thanks for developing this! I'm loving this application so far. 

As someone who watches a lot of slow paced lectures, it would be great to have a higher top speed to watch videos at - up to 3.5x or 4x. Could there be a setting to increase/modify the available playback speeds?

**Comment by rddim** [comment]
At this time up to 3x is already available at the bottom right of the video player.

**Comment by narekboghozian** [comment]
I have been using the 3x speed, but I am asking about speeds higher than that.

**Comment by shivasagarrao** [comment]
I think it's better to have custom playback speed as official YouTube website.

![Screenshot from 2020-12-20 01-50-27](https://user-images.githubusercontent.com/46630255/102698785-069d4680-4266-11eb-9c0e-5166a221d857.png)

**Comment by GilgusMaximus** [comment]
Hi, so if you reeeaaally want to get higher speeds at the moment, I would recommend looking at the way the pull request #854 reordered the playback speed menu and simply compile the app yourself. The description for that can be found in the wiki.

Hope this helps. I'm also closing this because a similar issue exists #616
