### ISSUE TITLE
new v0.10.0 release unavailable for Raspberry Pi

### ISSUE THREAD

**Issue by BugHunterPhilosopher** [FreeTubeApp/FreeTube#899]
**Behavior of the program**
I use a Raspberry Pi 3 B+ with Raspbian Buster. I installed latest version available, namely V. 0.7.3 Beta and I'm facing the "no search result" bug because of changes upstream.

**Expected behavior**
Can you please provide us with new v0.10.0 release for this platform? I tried 

$sudo dpkg -i --force-architecture freetube_0.10.0-nightly-391_arm64.deb

but if fails with dependencies architecture problems. And the file "freetube_0.10.0-nightly-391_arm64.AppImage" execution fails for the same bad architecture reasons.

Please, can you provide us with v0.10.0 in Flathub or .deb format for Pi 3?

$ flatpak list

Description             Application                              Version         Branch      Arch      Origin       Installation
FreeTube                io.freetubeapp.FreeTube        0.7.3 Beta      stable      arm       flathub      system

Thanks in advance!

**Comment by PrestonN** [comment]
FreeTube is currently only supported on 64 bit operating systems. There is nothing that I can do to change this as this was a decision made by the Electron team a long time ago.

Raspbian (or Raspberry Pi OS as it's now called) is not a 64 bit operating system and therefore is unable to run FreeTube. You will need to install a 64 bit OS on to your Pi in order to properly install the .deb or Flatpak versions of FreeTube.

[Ubuntu MATE](https://ubuntu-mate.org/ports/raspberry-pi/) appears to support the 3B+ however they do not recommend running it on that Pi due to the poor performance that will likely occur.

Ubuntu Desktop supports 64 bit for the Pi 4 and I've had no issues running the Flatpak version of FreeTube on this system.

You will very likely need to upgrade to a Pi 4 as the experience on a 3B+ will be degraded compared to other systems. Changing your operating system is the only way to run FreeTube on a 3B+ however.
