### ISSUE TITLE
Download only a part of video/audio

### ISSUE THREAD

**Issue by tiwarys** [FreeTubeApp/FreeTube#903]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
Currently users can only download a full video/audio but I can't download only some custom part of video/audio.

**Describe the solution you'd like to see implemented**
Downloading only a part of video/audio by allowing user to enter a start and end time .

**Describe alternatives you've considered**
youtube-dl, ffmpeg

**Comment by GilgusMaximus** [comment]
Hi, so this is not really possible at the moment because the app itself does not allow you to download the video. You are always downloading it through your default browser, which basically opens the whole video.

However PrestoN mentioned that he wanted to implement an already existing [project](https://github.com/Tzahi12345/YoutubeDL-Material) to make a nicer download feature. However that is still somewhere in the future #582 .

On a quick look into the documentation this project does not allow for downloading only a part of the video. So we are likely not gonna add that ourselves once the other project is integrated, since this just creates an additional code basis to maintain. For the best effect I would suggest posting this request over there, because they already employ video and audio processing.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Closing, see https://github.com/FreeTubeApp/FreeTube/discussions/5235#discussioncomment-9700089
