### ISSUE TITLE
Display D.Tube search results

### ISSUE THREAD

**Issue by Victor239** [FreeTubeApp/FreeTube#919]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
I'd like to be able to view D.Tube videos integrated into the same app rather than have to use a web browser. 

**Describe the solution you'd like to see implemented**
D.Tube is a decentralized video streaming platform, backed by the IPFS Network and the STEEM Blockchain.

**Describe alternatives you've considered**
A browser is a decent alternative for the moment but FreeTube would be an ideal all-in-one app for watching videos.

**Comment by PrestonN** [comment]
I currently have no plans to support services outside of YouTube. I want to keep my focuses on one platform so that we can get the YouTube implementation as best as we can. Juggling more services than that will split off our work and make it more difficult to focus on one aspect.

If / when I ever decide to incorporate a new service, PeerTube will be the first one on the list. Either way we are too far away from from having any sort of discussion about anything outside of YouTube so I will go ahead and close this issue.
