### ISSUE TITLE
Add an option to disable forced fetching of subscriptions using RSS

### ISSUE THREAD

**Issue by rootedetc** [FreeTubeApp/FreeTube#924]
**Is your feature request related to a usage problem (not a bug)? Please describe.**
After being subscribed to a certain number of channels on Freetube, it forces fetching new videos (subscriptions) using RSS, instead of the default method.

**Describe the solution you'd like to see implemented**
It would be great if we were given an option to disable force fetching subscriptions using RSS (with a warning maybe?).

<img width="2032" alt="Screenshot 2021-01-12 at 12 35 30" src="https://user-images.githubusercontent.com/61841347/104309587-b155fd00-54d2-11eb-8995-b1ca678c084c.png">

**Comment by PrestonN** [comment]
Sorry, but I don't think I'll be doing this.

YouTube is very picky when it comes to rate limiting, and we were flooded with rate limiting reports early on when the rewrite released. If we removed the safe guard then your IP will likely get blocked by YouTube. How fast it gets blocked is very dependent on the number of subscriptions in your profile. I feel like even if we add a warning, it'll likely get ignored and isn't worth doing even if users find it somewhat annoying.

We currently have a limit of 125 subscriptions per profile before FreeTube will force RSS for that profile's feed. This number is a safe number of subscriptions where you could realistically refresh them throughout a day and not get blocked by YouTube. If your subscription count is much higher than this, then you can possibly get immediately blocked from YouTube for the day the moment FreeTube opens up. We can possibly look into slightly increasing this limit in the future, however I don't see it getting much higher than it already is.

You can also create a profile with less than 125 subscriptions to not force RSS, as the subscriptions page will only fetch channels within your current active profile.

If this still isn't enough for you, you're welcome to remove the line forcing the limit and creating a binary from source. We keep instructions for doing so over [here](https://github.com/FreeTubeApp/FreeTube/wiki/Environment-Setup-and-Building-from-Source).

**Comment by fabianski7** [comment]
and if the proxy via invidious is active? couldn't that be the condition for passing that limit?

**Comment by PrestonN** [comment]
I wouldn't want to do that because the Invidious instances have the exact same limit that FreeTube does. Removing the limit for Invidious instances would put even more load on them and increase their costs to run the service. Most instances are forced to run an anti-captcha service to handle the blocking by YouTube which occurs even more costs to them. Some instances also do their own internal blocking to prevent too many rapid requests from coming in at one time which complicates it even further.

As far as the limit and how it's currently handled, I do not foresee any major changes to the current logic.
