### ISSUE TITLE
Errors when refreshing Subscriptions

### ISSUE THREAD

**Issue by kgr0** [FreeTubeApp/FreeTube#941]
**Behavior of the program**
Errors when refreshing Subscriptions

**Expected behavior**
No errors

**To Reproduce**
Initial conditions
In out tests we had 27 and 117 subscriptions (you can import 27 subscriptions from attached file)
   [27_youtube-subscriptionsjson.zip](https://github.com/FreeTubeApp/FreeTube/files/5824331/27_youtubesubscriptionsjson.zip)

1. Go to 'Subscriptions' section
2. Click on Refresh Subscriptions icon
3. See error messages

**Screenshots**

https://user-images.githubusercontent.com/50838031/104811538-ec26a080-5804-11eb-9459-c910c640ebdc.mp4

**Environment Information (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10
 - FreeTube version: v0.11.1 Beta
 - Installation Method: .exe
 - Primary API Used: Invidious API

**Additional context**
When using Local API this error occurs

![image](https://user-images.githubusercontent.com/50838031/104811713-22b0eb00-5806-11eb-88c0-3b8049197695.png)

Our team (@Vovany4, @abulenok) has experienced this bug.

**Comment by GilgusMaximus** [comment]
So the first error is due to Invidious. We cannot change anything about that.

The second error happens to me too for a few days.

**Comment by PrestonN** [comment]
To elaborate a little more, the default Invidious instance (https://invidious.snopyta.org) has safeguards in place to prevent misuse of their API. Refreshing subscriptions causes their safeguard to trigger and therefore blocks FreeTube from making the request. FreeTube will fallback to RSS in this case so that you can still see a feed.

The second issue has to do with our channel scraper module. It's something that I need to look into and already has an issue here somewhere. Again, FreeTube will revert to RSS in this instance when the issue occurs, so your feed will still be available.

**Comment by Svallinn** [comment]
The Invidious error can be solved by changing the instance (unless every instance out there is rate-limited; if that's the case, not even the Almighty Creator can help you)
I'm confident that the second issue has become irrelevant for quite some time now.
With that being said, I'm closing this.
