### ISSUE TITLE
Picture-in-picture - Material is not changed in the player after user clicks on a different material

### ISSUE THREAD

**Issue by Jimmymax297** [FreeTubeApp/FreeTube#967]
**Behavior of the program**
When user tries to change material that is played via picture-in-picture player the normal player changes while picture-in-picture player stays with the same video.

**Expected behavior**
When user changes video with video playing in picture-in-picture player the picture-in-picture player should change to the new video.

**Preconditions**
- User is watching a video

**To Reproduce**
Please add all steps to reproduce the behavior:
1. User clicks on the player bar to watch video in the picture-in-picture mode
2. User clicks on a different material on the right of the normal player
3. See error

**Screenshots**
![PiP - Two materials](https://user-images.githubusercontent.com/33980616/105411514-c863c000-5c33-11eb-96a7-72c1bc24b21d.PNG)

**Environment Information (please complete the following information):**
 - OS: [Windows]
 - OS Version: [Windows 10]
 - FreeTube version: [0.11.1]
 - Primary API Used: [Local API]

**Comment by PrestonN** [comment]
I'm going to mark this as intended, because I'd rather not force a video to stop playing just because the user navigates to another video. A user may want to have several videos ready in the background for playing and changing the current behavior to your suggestion would prevent this from being possible. This functionality will not be changed.
