### ISSUE TITLE
Alt brings up context menu

### ISSUE THREAD

**Issue by darknuju** [FreeTubeApp/FreeTube#984]
**Behavior of the program**
When pressing alt, a context menu pops up at the top of the window.

**Expected behavior**
This is not exactly unexpected behavior, but I use a tiling window manager and thus regularly use the alt key for various things. It is quite annoying to have the context menu popping in and out and it would be nice to be able to disable that.

**To Reproduce**
Simply press alt on any part of the program.

**Environment Information (please complete the following information):**
 - OS: Arch
 - FreeTube version: 0.11.2 beta
 - Installation Method (If applicable): I installed using an aur package
 - Primary API Used: invidious

![screenshot](https://user-images.githubusercontent.com/7081025/105637356-0dbb0400-5e65-11eb-8a6c-5154a71015af.png)

**Comment by saideepesh000** [comment]
[windows user here] Hey @wesley-as, I think this is the behaviour off the OS side, because in every desktop app we see, pressing alt opens/focus up the file menu of its corresponding app,

**Comment by GilgusMaximus** [comment]
This is something that has to stay, although not on that key in particular. I'm not sure whether this can actually be mapped to another shortcut because that simply comes from Electron.

**Comment by wesley-as** [comment]
If this isn't fixable, then I guess I will have to live with it. Thank you for your time. Should I close the issue now?

**Comment by GilgusMaximus** [comment]
No all good. We'll leave it open for now and if someone wants to check that out in Electron itself this is a good issue to tackle for newcomers or at latest if we do the hotkey remapping

**Comment by theforbiddenpool** [comment]
I spend a bit investigating this issue, and it seems to have been fixed on electron with electron/electron#29328, which was then released on version 13.1.0. FreeTube currently uses electron 21.

I tested it myself, and the Alt menu is only displayed after I release the Alt key. Meaning, the Alt key + another key should not trigger the menu. For context, I'm using Arch Linux.
I also tested when the menu was already open, and the Alt key does trigger the menu closing, but I'm still able to do the shortcut. Since it's unlikely somebody will have the Alt menu open anyway, I don't think this is much of a problem.

With this, I would suggest this issue to be closed, as it seems to have been fixed.
