### ISSUE TITLE
hide the stars on top of the thumbnail

### ISSUE THREAD

**Issue by Donkey-Doug** [FreeTubeApp/FreeTube#999]
I really like that FreeTube has distraction free settings. I suggest an option to hide the stars on top of the thumbnail. These stars can be used to save a video. Perhaps the option "save video" could be placed under the 3-dots menu.

**Comment by GilgusMaximus** [comment]
So this is more of an opinion based discussion, rather than an enhancement. Therefore I am changing the tag for this.

I'm just gonna throw my opinion in as well, which is that moving it to the three dots is probably not such a good idea, because it is getting very cluttered already. Adding more fields would make things even worse to identify.

But an option to disable the icon would be possible.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @Donkey-Doug does it needs to be hidden or would something like https://github.com/FreeTubeApp/FreeTube/issues/1746 also be alright with u?

**Comment by jasonhenriquez** [comment]
@Donkey-Doug To boost @efb4f5ff-1298-471a-8973-3d47447115dc's question, does #3954 adequately count as "hiding" for your purposes?
